import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import path from 'node:path';
import {createHash,timingSafeEqual} from 'node:crypto';
const DAY=86400000,uuid=/^[a-f0-9-]{36}$/i,action=/^(sign|inventory|repair|buy|receive|accept|reject|pack|load|dispatch|approve|upgrade|hire|unlock|buyDevelopment|contract(?::(?:bakery|dairy|pantry|frozen))?|chooseStory(?::[a-z_]{1,30}:[a-z_]{1,30})?)$/;
const digest=s=>createHash('sha256').update(s).digest();
export function summarize(sessions,{now=Date.now(),days=7}={}){const list=Object.values(sessions).filter(s=>s.lastSeen>=now-days*DAY),visitors=new Set(list.map(s=>s.visitor)),daily={},devices={},actions={},errors={},stages=Array(5).fill(0),missions=Array(17).fill(0),lastMissions=Array(17).fill(0);let active=0,starts=0,duration=0;
 for(const s of list){const date=new Date(s.firstSeen).toISOString().slice(0,10);daily[date]??={sessions:0,visitors:new Set()};daily[date].sessions++;daily[date].visitors.add(s.visitor);devices[s.device]=(devices[s.device]||0)+1;starts+=Number(s.started);active+=Number(s.lastSeen>now-90000);duration+=s.activeSeconds;stages[s.maxStage]++;for(let i=0;i<=s.maxMission;i++)missions[i]++;lastMissions[s.mission]++;for(const [k,v]of Object.entries(s.actions))actions[k]=(actions[k]||0)+v;for(const [k,v]of Object.entries(s.errors))errors[k]=(errors[k]||0)+v;}
 return {generatedAt:now,days,visitors:visitors.size,sessions:list.length,starts,active,activeSeconds:duration,averageSeconds:starts?Math.round(duration/starts):0,devices,actions,errors,stages,missions,lastMissions,daily:Object.entries(daily).sort().map(([date,v])=>({date,sessions:v.sessions,visitors:v.visitors.size})),recent:list.sort((a,b)=>b.lastSeen-a.lastSeen).slice(0,40).map(s=>({id:s.id.slice(0,8),device:s.device,version:s.version,started:s.started,lastSeen:s.lastSeen,mission:s.mission,stage:s.maxStage,day:s.day,delivered:s.delivered,activeSeconds:s.activeSeconds})),retentionDays:30};}
export async function createAnalytics(dir,{key=process.env.ANALYTICS_ADMIN_KEY||'',origins=(process.env.ANALYTICS_ORIGINS||'').split(',').map(v=>v.trim()).filter(Boolean),now=Date.now,maxSessions=25000}={}){
 await mkdir(dir,{recursive:true});const file=path.join(dir,'analytics.json');let db={sessions:{}};try{db=JSON.parse(await readFile(file,'utf8'));if(!db.sessions||typeof db.sessions!=='object')throw Error('Invalid analytics database')}catch(e){if(e.code!=='ENOENT')throw e}let serial=Promise.resolve();const rates=new Map();
 const send=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data))};
 const persist=async()=>{await writeFile(file+'.tmp',JSON.stringify(db));await rename(file+'.tmp',file)};
 return async function(req,res,url){if(!url.pathname.startsWith('/api/telemetry'))return false;const origin=req.headers.origin;if(origin&&!origins.includes(origin)){send(res,403,{error:'مصدر غير مسموح'});return true}if(origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','POST,GET,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization')}if(req.method==='OPTIONS'){res.writeHead(204);res.end();return true}
 if(key.length<32){send(res,503,{error:'خادم الإحصائيات لم يتم تفعيله بعد'});return true}
 if(url.pathname==='/api/telemetry/summary'&&req.method==='GET'){if(!timingSafeEqual(digest(req.headers.authorization||''),digest('Bearer '+key))){send(res,401,{error:'مفتاح الإدارة غير صحيح'});return true}await serial;const days=Number(url.searchParams.get('days')||7);if(![1,7,30].includes(days)){send(res,400,{error:'فترة غير صالحة'});return true}send(res,200,summarize(db.sessions,{now:now(),days}));return true}
 if(url.pathname!=='/api/telemetry'||req.method!=='POST'){send(res,404,{error:'غير موجود'});return true}
 const ip=req.socket.remoteAddress||'unknown',t=now(),rate=rates.get(ip)||{until:t+60000,count:0};if(rate.until<t){rate.until=t+60000;rate.count=0}rate.count++;rates.set(ip,rate);if(rates.size>5000)for(const [k,v]of rates)if(v.until<t)rates.delete(k);if(rate.count>600){send(res,429,{error:'طلبات كثيرة؛ أعد المحاولة لاحقًا'});return true}
 try{let raw='',length=0;for await(const chunk of req){length+=chunk.length;if(length>32768){send(res,413,{error:'حجم الطلب كبير'});return true}raw+=chunk.toString('utf8')}const body=JSON.parse(raw);if(body.testMode||!uuid.test(body.visitor)||!uuid.test(body.session)||!['mobile','desktop'].includes(body.device)||!/^\d+\.\d+\.\d+$/.test(body.version)||!Array.isArray(body.events)||body.events.length<1||body.events.length>20)throw Error('Invalid envelope');
 const num=(v,max)=>Number.isInteger(v)&&v>=0&&v<=max;for(const e of body.events){if(!num(e.seq,1e9)||!['visit','start','heartbeat','action','error'].includes(e.kind)||!e.snapshot)throw Error('Invalid event');const s=e.snapshot;if(!num(s.mission,16)||!num(s.stage,4)||!num(s.day,1e6)||!num(s.delivered,1e6)||!num(s.activeSeconds,2592000))throw Error('Invalid snapshot');if(e.kind==='action'&&!action.test(e.key))throw Error('Invalid action');if(e.kind==='error'&&(!e.error||!['Error','TypeError','ReferenceError','RangeError','SyntaxError','URIError','EvalError'].includes(e.error.kind)||!/^([a-zA-Z0-9_-]+\.js|runtime)$/.test(e.error.file)||!num(e.error.line,100000)))throw Error('Invalid error');}
 const work=serial.then(async()=>{const time=now();for(const [id,s]of Object.entries(db.sessions))if(time-s.lastSeen>30*DAY)delete db.sessions[id];const existing=db.sessions[body.session];if(existing&&existing.visitor!==body.visitor)throw Error('Session mismatch');if(!existing&&Object.keys(db.sessions).length>=maxSessions){send(res,503,{error:'سعة الإحصائيات ممتلئة'});return}
 const s=existing?structuredClone(existing):{id:body.session,visitor:body.visitor,device:body.device,version:body.version,firstSeen:time,lastSeen:time,seq:-1,started:false,activeSeconds:0,maxMission:0,mission:0,maxStage:0,day:1,delivered:0,actions:{},errors:{}};let updated=false;
 for(const e of [...body.events].sort((a,b)=>a.seq-b.seq)){if(e.seq<=s.seq)continue;updated=true;s.seq=e.seq;s.lastSeen=time;s.version=body.version;s.mission=e.snapshot.mission;s.maxMission=Math.max(s.maxMission,s.mission);s.maxStage=Math.max(s.maxStage,e.snapshot.stage);s.day=e.snapshot.day;s.delivered=e.snapshot.delivered;s.activeSeconds=Math.max(s.activeSeconds,Math.min(e.snapshot.activeSeconds,Math.floor((time-s.firstSeen)/1000)+35));if(e.kind==='start')s.started=true;if(e.kind==='action'){s.actions[e.key]=Math.min(1e6,(s.actions[e.key]||0)+1)}if(e.kind==='error'){const k=e.error.kind+' · '+e.error.file+':'+e.error.line;if(Object.keys(s.errors).length<12||s.errors[k])s.errors[k]=Math.min(100,(s.errors[k]||0)+1)}}
 if(updated){db.sessions[body.session]=s;try{await persist()}catch(e){if(existing)db.sessions[body.session]=existing;else delete db.sessions[body.session];throw e}}send(res,200,{ok:true});});serial=work.catch(()=>{});await work;
 }catch{if(!res.writableEnded)send(res,400,{error:'تعذر قبول بيانات الإحصائيات'})}return true;
 };
}
