import * as T from './vendor/three.module.js';
import {createManager,updateManagerPose} from './world/manager.js';
const canvas=document.getElementById('preview'),renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color(0x263138);const camera=new T.PerspectiveCamera(34,1,.01,40),target=new T.Vector3(0,.98,0);scene.add(new T.HemisphereLight(0xe7edf1,0x514941,2));
for(const [color,power,pos]of [[0xffeee0,2.5,[-3,5,4]],[0xc5deff,.8,[3,2,1]],[0xfff1da,1.8,[1,3,-3]]]){const light=new T.DirectionalLight(color,power);light.position.fromArray(pos);scene.add(light);if(power===2.5){light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-2,right:2,top:3,bottom:-2});light.shadow.normalBias=.018}}
const stage=new T.Mesh(new T.CylinderGeometry(.7,.72,.035,64),new T.MeshStandardMaterial({color:0x38454b,roughness:.9}));stage.position.y=-.025;stage.receiveShadow=true;scene.add(stage);const actor=createManager({mats:{},cb:{}});scene.add(actor);const box=new T.Mesh(new T.BoxGeometry(.60,.46,.46),new T.MeshStandardMaterial({color:0xb99b6b,roughness:.95}));box.position.set(0,1.03,.5);box.visible=false;scene.add(box);
let yaw=.3,pitch=.10,distance=3.7,mode='idle',auto=false,last=performance.now(),time=0,pinch=0;const pointers=new Map(),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);pinch=0;e.preventDefault()});canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const a=[...pointers.values()],d=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);if(pinch)distance=clamp(distance*pinch/d,.65,6);pinch=d}else{yaw-=(e.clientX-old[0])*.008;pitch=clamp(pitch+(e.clientY-old[1])*.005,-.22,.75)}e.preventDefault()});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{pointers.delete(e.pointerId);pinch=0});window.addEventListener('blur',()=>{pointers.clear();pinch=0});canvas.addEventListener('wheel',e=>{distance=clamp(distance*Math.exp(e.deltaY*.001),.65,6);e.preventDefault()},{passive:false});
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{const v=button.dataset.view;if(v==='face'){target.y=1.68;distance=.85;yaw=0;pitch=0}else{target.y=.98;distance=3.7;pitch=.10;yaw=({front:0,side:Math.PI/2,back:Math.PI,three:.5})[v]}}));document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b===button))}));document.getElementById('turn').addEventListener('click',e=>{auto=!auto;e.currentTarget.classList.toggle('active',auto)});
function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();
function tick(now){requestAnimationFrame(tick);const dt=Math.min(.05,(now-last)/1000);last=now;if(document.hidden)return;time+=dt;if(auto)yaw+=dt*.35;const carry=mode==='carry',step=mode==='walk'?Math.sin(time*7)*.38:0;actor.userData.legs[0].rotation.x=step;actor.userData.legs[1].rotation.x=-step;for(const leg of actor.userData.legs)leg.userData.knee.rotation.x=Math.max(0,-leg.rotation.x)*.65;actor.userData.arms[0].rotation.x=-step;actor.userData.arms[1].rotation.x=step;for(const arm of actor.userData.arms)arm.userData.elbow.rotation.x=-.08;updateManagerPose(actor,time,carry);box.visible=carry;camera.position.set(Math.sin(yaw)*distance*Math.cos(pitch),target.y+Math.sin(pitch)*distance,Math.cos(yaw)*distance*Math.cos(pitch));camera.lookAt(target);renderer.render(scene,camera)}requestAnimationFrame(tick);
