import {businessDefaults,installBusiness} from './simulation/business.js';
import {CITY_CLIENTS,CITY_WIDTH,CITY_HEIGHT} from './city-catalog.js';
import {installStory,storyDefaults} from './simulation/story.js';
import {installDevelopment,developmentDefaults} from './simulation/development.js';
import {installLogistics,logisticsDefaults} from './simulation/logistics.js';
import {installExpansion,expansionDefaults} from './simulation/expansion.js';
/* وكالة سعيد — simulation independent from rendering, monetary amounts in EGP. */
import {installEconomyFeatures,featureDefaults} from './sim-features.js';
'use strict';
const PRODUCTS={
 bread:{name:'خبز معبأ',company:'bakery',buy:90,sell:132,life:4,color:0xd5a66a},
 pastry:{name:'معجنات',company:'bakery',buy:145,sell:207,life:3,color:0xc99256},
 milk:{name:'لبن',company:'dairy',buy:170,sell:229,life:5,color:0xabc9c8},
 yogurt:{name:'زبادي',company:'dairy',buy:115,sell:164,life:3,color:0xc6d8d4},
 ghee:{name:'سمنة',company:'dairy',buy:420,sell:549,life:14,color:0xc8b875},
 juice:{name:'عصائر',company:'dairy',buy:150,sell:204,life:10,color:0xd2aa69},
 whiteCheese:{name:'جبن أبيض',company:'dairy',buy:280,sell:375,life:6,color:0xd6d9c6},
 triangleCheese:{name:'جبن مثلثات',company:'dairy',buy:230,sell:312,life:12,color:0xc6cbb8},
 milkMix:{name:'ميكس لبن',company:'dairy',buy:195,sell:264,life:6,color:0xb3bba1},
 cookedCheese:{name:'جبن مطبوخ',company:'dairy',buy:270,sell:362,life:10,color:0xcfc3a4},
 rice:{name:'أرز معبأ',company:'pantry',sell:288,life:60,color:0xd5c999},
 oil:{name:'زيت طعام',company:'pantry',sell:455,life:90,color:0xc8aa4d},
 pasta:{name:'مكرونة',company:'pantry',sell:251,life:90,color:0xc98b53},
 sugar:{name:'سكر معبأ',company:'pantry',sell:310,life:90,color:0xd9d8c3},
 peas:{name:'بسلة مجمدة',company:'frozen',sell:340,life:30,color:0x87b69f},
 fries:{name:'بطاطس مجمدة',company:'frozen',sell:460,life:30,color:0xcbd6a8},
 chicken:{name:'دجاج مجمد',company:'frozen',sell:680,life:25,color:0xb6cfd9}
};
const MONEY=n=>Math.round((n+Number.EPSILON)*100)/100,DAY_SECONDS=900,ORDER_SECONDS=10;
const VEHICLES={jumbo:{name:'جامبو صندوق كبير — حمولة ١٢٠',price:48000,capacity:120,color:0x34596b},normal:{name:'عربية توزيع عادية',price:12000,color:0x275a5b},chilled:{name:'عربية مبردة +٤°',price:18500,color:0xd4e8de},frozen:{name:'عربية تجميد −١٨°',price:26000,color:0x9fc3d7}};
const ROLES={driver:{name:'سائق توزيع',fee:1500,salary:1600,max:1},worker:{name:'عامل مخزن',fee:1200,salary:1200,max:1},rep:{name:'مندوب مبيعات',fee:2000,salary:1500,max:3},accountant:{name:'محاسب',fee:1800,salary:1400,max:1}};
const COMPANIES={
 bakery:{name:'المخابز الذهبية',short:'المخبوزات',fee:2000,target:12000,discount:.12,deferred:.02,warehouse:160,warehouseCost:2000,vehicle:'normal',storage:'dry',deliveries:0,reputation:0,cycles:0,reps:0,previous:null},
 dairy:{name:'مزارع نور لمنتجات الألبان',short:'مزارع نور',fee:3500,target:22000,discount:.12,deferred:.02,warehouse:160,warehouseCost:3000,vehicle:'chilled',storage:'chilled',deliveries:8,reputation:55,cycles:1,reps:0,previous:'bakery'},
 pantry:{name:'دلتا فودز للمواد الغذائية',short:'دلتا فودز',fee:6500,target:36000,discount:.12,deferred:.02,warehouse:240,warehouseCost:6000,vehicle:'normal',storage:'dry',deliveries:25,reputation:65,cycles:3,reps:1,previous:'dairy'},
 frozen:{name:'قطوف للأغذية المجمدة',short:'قطوف',fee:9500,target:52000,discount:.12,deferred:.02,warehouse:240,warehouseCost:9000,vehicle:'frozen',storage:'frozen',deliveries:60,reputation:75,cycles:6,reps:2,previous:'pantry'}
};
const MAP={width:CITY_WIDTH,height:CITY_HEIGHT,depot:{x:85,y:105,name:'وكالة سعيد'},clients:CITY_CLIENTS.map(c=>({x:c.x,y:c.y}))};
function routePoints(from,to,fast=false){const points=[from,{x:from.x,y:105},{x:to.x,y:105},to];return points.filter((p,i)=>!i||p.x!==points[i-1].x||p.y!==points[i-1].y).length>=2?points.filter((p,i)=>!i||p.x!==points[i-1].x||p.y!==points[i-1].y):[from,to]}
function pathDistance(points){return points.slice(1).reduce((a,p,i)=>a+Math.hypot(p.x-points[i].x,p.y-points[i].y),0)}
function routePosition(t){if(!t?.legs?.length)return MAP.depot;const leg=t.legs[Math.min(t.legIndex,t.legs.length-1)];if(leg.kind==='unload')return MAP.clients[leg.client];const pts=leg.points,dist=pathDistance(pts);let left=Math.min(1,t.legElapsed/leg.duration)*dist;for(let i=1;i<pts.length;i++){const d=Math.hypot(pts[i].x-pts[i-1].x,pts[i].y-pts[i-1].y);if(left<=d||i===pts.length-1){const a=d?Math.min(1,left/d):0;return {x:pts[i-1].x+(pts[i].x-pts[i-1].x)*a,y:pts[i-1].y+(pts[i].y-pts[i-1].y)*a}}left-=d;}return pts.at(-1)}

const CLIENTS=CITY_CLIENTS;
const MISSIONS=[
 {title:'استلام وكالة سعيد',hint:'وقّع استلام الإدارة في المكتب.',target:'desk'},
 {title:'جرد وتخصيص أول مخزن',hint:'راجع المخزن الموروث؛ هنخصصه لتوكيل المخبوزات.',target:'shelf'},
 {title:'تجهيز عربية التوزيع',hint:'صلّح العربية من ساحة التحميل.',target:'truck'},
 {title:'أول موظف: السائق',hint:'عيّن سائق براتب من مكتب التوظيف.',target:'staff'},
 {title:'توقيع أول توكيل',hint:'افتح عقد المخابز الذهبية وراجع الشروط ووقّع.',target:'desk'},
 {title:'أول طلبية للتوكيل',hint:'أكد طلب ماركت الأمانة من التليفون. الطلبات تصل كل ١٠ ثوانٍ.',target:'phone'},
 {title:'مسحوبات من الشركة',hint:'اطلب ١٠ كراتين خبز بسعر قائمة الشركة ناقص خصمك الفوري.',target:'supplier'},
 {title:'استلام المسحوبات',hint:'استلم البضاعة من البالتة. المسحوبات المستلمة تدخل في التارجت.',target:'receiving'},
 {title:'تجهيز وتحميل',hint:'جهّز أول طلب من الرف وحمّله في العربية.',target:'shelf'},
 {title:'رحلة توزيع حقيقية',hint:'ابدأ الرحلة وتابع الوصول والتفريغ والرجوع على الخريطة.',target:'truck'},
 {title:'التحصيل',hint:'راجع فاتورة البيع بعد التسليم وحصّلها من الحسابات.',target:'accounts'},
 {title:'الاستعداد لمزارع نور',hint:'حقق دورة مسحوبات ناجحة و٨ طلبيات محصلة وسمعة ٥٥، ثم جهّز مخزنًا وتبريدًا وعربية مبردة للعقد.',target:'desk'},
 {title:'تكوين فريق المبيعات',hint:'وظّف مندوبًا. المندوب له راتب وعمولة على مبيعاته المحصلة.',target:'staff'},
 {title:'توكيل المواد الغذائية',hint:'وصل إلى ٢٥ طلبية و٣ دورات ناجحة وسمعة ٦٥ وافتح عقد دلتا فودز.',target:'desk'},
 {title:'فتح سوق الدقهلية',hint:'افتح خط الدقهلية ثم نفّذ وحصّل طلبية هناك.',target:'map'},
 {title:'دخول سوق المجمدات',hint:'٦٠ طلبية و٦ دورات ناجحة وسمعة ٧٥ ومندوبان؛ بعدها جهّز مخزن تجميد وعربية تجميد لعقد قطوف.',target:'desk'},
 {title:'إدارة شبكة التوكيلات',hint:'حقق ١٠٠ ألف ج.م صافي ربح و١٢ دورة مسحوبات ناجحة مع التوكيلات الأربعة.',target:'desk'}
];
const fresh=()=>({...businessDefaults(),...storyDefaults(),...developmentDefaults(),...logisticsDefaults(),...featureDefaults(),...expansionDefaults(),version:4,name:'التاجر',money:25000,debt:8000,day:1,time:0,elapsed:0,signed:false,inventoried:false,repaired:false,mission:0,chapter:1,completed:false,firstReward:false,rep:50,capacity:160,cooling:false,freezer:false,officeLevel:0,truckCount:1,truckCondition:100,vehicles:[{id:1,kind:'normal',condition:100,capacity:60}],selectedVehicle:1,staff:{driver:0,worker:0,rep:0,accountant:0},commissionDue:0,commissionPaid:0,autoTick:0,auto:false,contracts:{bakery:false,dairy:false,pantry:false,frozen:false},warehouses:{bakery:{owned:false,capacity:160},dairy:{owned:false,capacity:160},pantry:{owned:false,capacity:240},frozen:{owned:false,capacity:240}},cycles:{},successfulCycles:0,cycleHistory:[],purchases:{bakery:0,dairy:0,pantry:0,frozen:0},netPurchases:{bakery:0,dairy:0,pantry:0,frozen:0},stock:[],incoming:[],orders:[],trip:null,tripHistory:[],cargo:[],carry:null,invoices:[],ledger:[],clients:CLIENTS.map(c=>({...c,served:0,outstanding:0})),regions:['دمياط'],served:[],revenue:0,cogs:0,expenses:0,delivered:0,seq:1,orderTick:0,event:null,nextEvent:3,lastStatement:null,notices:[],settings:{sound:true,quality:'high'},position:{x:-6,z:4}});
class Simulation{
 constructor(state){this.s=state?Simulation.validate(state):fresh();this.onChange=()=>{};this.onNotice=()=>{};this.rng=Math.random;this.advance();this.unlockDevelopment();this.assignFleetBrands();}
 get stockTotal(){return this.s.stock.reduce((a,b)=>a+b.qty,0)}
 get reservedStorage(){return (this.s.carry?.qty||0)+this.s.cargo.reduce((a,b)=>a+b.qty,0)+(this.s.trip?.cargo||[]).reduce((a,b)=>a+b.qty,0)}
 get pendingStock(){return this.s.incoming.reduce((a,b)=>a+b.qty,0)}
 get profit(){return this.s.revenue-this.s.cogs-this.s.expenses}
 get mission(){return MISSIONS[Math.min(this.s.mission,MISSIONS.length-1)]}
 qty(pid){return this.s.stock.filter(b=>b.pid===pid).reduce((a,b)=>a+b.qty,0)}
 cost(pid){const p=PRODUCTS[pid];return MONEY(p.sell*(this.s.contracts[p.company]?1-COMPANIES[p.company].discount:1))}
 enabled(pid){return !!PRODUCTS[pid]&&this.s.contracts[PRODUCTS[pid].company]}
 notice(text,type='good'){this.s.notices.unshift({text,day:this.s.day});this.s.notices=this.s.notices.slice(0,30);this.onNotice(text,type)}
 change(){this.advance();this.onChange(this.s)}
 fail(msg){this.notice(msg,'bad');return false}
 spend(amount,expense=false,reason=''){if(!Number.isFinite(amount)||amount<0||this.s.money<amount)return false;this.s.money-=amount;if(expense)this.s.expenses+=amount;if(reason)this.log(reason,-amount);return true}
 log(text,amount){this.s.ledger.unshift({id:this.s.seq++,day:this.s.day,text,amount});this.s.ledger=this.s.ledger.slice(0,150)}
 advance(){const s=this.s,old=s.mission;let m=0;
 if(s.signed)m=1;if(m===1&&s.inventoried)m=2;if(m===2&&s.repaired)m=3;if(m===3&&s.staff.driver)m=4;if(m===4&&Object.values(s.contracts).some(Boolean))m=5;
 if(m===5&&(s.orders.some(o=>o.accepted)||s.carry||s.pickingJob||s.cargo.length||this.otherLoads().length||s.trip||s.fleetTrips.length||s.delivered))m=6;
 if(m===6&&(s.incoming.length||this.stockTotal||s.carry||s.pickingJob||s.cargo.length||this.otherLoads().length||s.trip||s.fleetTrips.length||s.delivered))m=7;
 if(m===7&&(this.stockTotal||s.carry||s.pickingJob||s.cargo.length||this.otherLoads().length||s.trip||s.fleetTrips.length||s.delivered))m=8;
 if(m===8&&(s.cargo.length||s.trip||s.fleetTrips.length||s.delivered))m=9;if(m===9&&(s.trip||s.fleetTrips.length||s.delivered))m=10;
 if(m===10&&s.delivered){m=11;if(!s.firstReward){s.firstReward=true;s.money+=3000;this.log('دعم رأس مال التشغيل لأول توكيل',3000);this.notice('أول طلبية اتحصّلت! عم سعيد أضاف ٣٬٠٠٠ ج.م لرأس مال التشغيل.');}}
 if(m===11&&s.contracts.dairy)m=12;if(m===12&&s.staff.rep)m=13;if(m===13&&s.contracts.pantry)m=14;if(m===14&&s.clients.some(c=>c.area==='الدقهلية'&&c.served))m=15;if(m===15&&s.contracts.frozen)m=16;
 s.mission=m;s.chapter=m<11?1:m<13?2:m<15?3:4;
 if(m===16&&!s.completed&&this.profit>=100000&&s.successfulCycles>=12){s.completed=true;this.notice('وكالة سعيد حققت أهداف شبكة التوكيلات. تقدر تكمل إدارة الدورات والتوسع بحرية.');}
 if(m!==old)this.log('المرحلة الحالية: '+this.mission.title,0);
 }
 get vehicle(){return this.s.vehicles.find(v=>v.id===this.s.selectedVehicle)||this.s.vehicles[0]}
 canCarry(pid,v=this.vehicle){const c=COMPANIES[PRODUCTS[pid].company];return c.vehicle==='normal'?v.kind!=='frozen':v.kind===c.vehicle}
 companyUsage(cid){let items=[...this.s.stock,...this.s.incoming,...this.s.cargo,...(this.s.trip?.cargo||[])];if(this.s.carry)items.push(this.s.carry);return items.filter(b=>PRODUCTS[b.pid].company===cid).reduce((a,b)=>a+b.qty,0)}
 eligibility(cid){const s=this.s,c=COMPANIES[cid];return [
 {text:'استلام الوكالة والجرد',met:s.signed&&s.inventoried},
 {text:'سجل '+c.deliveries+' طلبيات محصّلة',met:s.delivered>=c.deliveries},
 {text:'سمعة '+c.reputation+' أو أكثر',met:s.rep>=c.reputation},
 {text:c.cycles+' دورات مسحوبات ناجحة',met:s.successfulCycles>=c.cycles},
 {text:'التوكيل السابق: '+(c.previous?COMPANIES[c.previous].short:'لا يشترط'),met:!c.previous||s.contracts[c.previous]}
 ]}
 requirements(cid){const s=this.s,c=COMPANIES[cid];return [...this.eligibility(cid),
 {text:'مخزن مخصص '+c.warehouse+' كرتونة',met:s.warehouses[cid].owned&&s.warehouses[cid].capacity>=c.warehouse},
 {text:c.storage==='dry'?'تخزين جاف':c.storage==='chilled'?'غرفة تبريد +٤°':'غرفة تجميد −١٨°',met:c.storage==='dry'||(c.storage==='chilled'?s.cooling:s.freezer)},
 {text:VEHICLES[c.vehicle].name,met:s.repaired&&s.vehicles.some(v=>c.vehicle==='normal'?v.kind!=='frozen':v.kind===c.vehicle)},
 {text:'سائق موظف براتب',met:s.staff.driver>=1},
 {text:c.reps+' مندوب مبيعات',met:s.staff.rep>=c.reps}
 ]}
 setupWarehouse(cid){const s=this.s,c=COMPANIES[cid];if(!c||s.warehouses[cid].owned)return false;if(!this.eligibility(cid).every(r=>r.met))return this.fail('استوفِ شروط فتح التوكيل أولًا.');if(!this.spend(c.warehouseCost,false,'تجهيز مخزن '+c.short))return this.fail('الخزنة لا تكفي.');s.warehouses[cid].owned=true;s.capacity=Object.values(s.warehouses).filter(w=>w.owned).reduce((a,w)=>a+w.capacity,0);this.notice('اتجهز مخزن مخصص لـ'+c.short+'.');this.change();return true}
 chooseVehicle(id){const v=this.s.vehicles.find(v=>v.id===Number(id));if(!v)return false;if(this.s.trip||this.s.cargo.length||this.s.carry)return this.fail('انتظر رجوع الرحلة وفرّغ الحمولة قبل تبديل العربية.');this.s.selectedVehicle=v.id;this.s.truckCondition=v.condition;this.change();return true}
 buyVehicle(kind){const s=this.s,v=VEHICLES[kind];if(!v||s.vehicles.length>=5)return this.fail('الأسطول يسمح بـ٥ عربيات، والجامبو ضمن الخمسة.');if(kind==='jumbo'&&s.delivered<25)return this.fail('الجامبو يتفتح بعد ٢٥ طلبية مسلّمة.');if(kind==='chilled'&&!this.eligibility('dairy').every(r=>r.met))return this.fail('افتح شروط مزارع نور الأول.');if(kind==='frozen'&&!this.eligibility('frozen').every(r=>r.met))return this.fail('افتح شروط قطوف الأول.');if(!this.spend(v.price,false,'شراء '+v.name))return this.fail('الخزنة لا تكفي.');s.vehicles.push({id:Math.max(...s.vehicles.map(v=>v.id))+1,kind,condition:100,capacity:v.capacity||60});s.truckCount=s.vehicles.length;this.notice('انضمت '+v.name+' للأسطول.');this.change();return true}
 convertVehicle(kind){const s=this.s;if(this.vehicle.kind==='jumbo')return this.fail('الجامبو مخصص للبضاعة الجافة ولا يتحول للتبريد.');if(!['chilled','frozen'].includes(kind)||this.vehicle.kind===kind)return false;if(s.trip||s.cargo.length||s.carry)return this.fail('العربية لازم تكون فاضية وموجودة في الوكالة.');const cid=kind==='chilled'?'dairy':'frozen';if(!this.eligibility(cid).every(r=>r.met))return this.fail('استوفِ شروط فتح التوكيل قبل تجهيز العربية.');const cost=kind==='chilled'?4500:8500;if(!this.spend(cost,false,'تحويل إلى '+VEHICLES[kind].name))return this.fail('الخزنة لا تكفي.');this.vehicle.kind=kind;this.vehicle.capacity=60;this.notice('العربية اتجهزت بصندوق عازل ووحدة '+(kind==='chilled'?'تبريد.':'تجميد.'));this.change();return true}

 sign(name){if(this.s.signed)return false;this.s.name=String(name||'التاجر').trim().slice(0,30)||'التاجر';this.s.signed=true;this.notice('المكتب والمخزن والعربية بقوا تحت إدارتك. راجع المخزن الأول.');this.change();return true}
 inventory(){if(!this.s.signed)return this.fail('استلم الوكالة من المكتب الأول.');if(this.s.inventoried)return false;this.s.inventoried=true;this.s.warehouses.bakery.owned=true;this.notice('الجرد: مخزن فاضي بسعة ١٦٠ كرتونة، عربية عطلانة، و٨٬٠٠٠ ج.م التزامات قديمة.');this.change();return true}
 repair(){if(!this.s.inventoried)return this.fail('راجع جرد الوكالة الأول.');if(this.s.trip)return this.fail('استنى رجوع العربية.');if(this.s.repaired&&this.s.truckCondition>=95)return this.fail('العربية حالتها ممتازة.');let cost=this.s.repaired?Math.ceil((100-this.s.truckCondition)*15):3000;if(!this.spend(cost,false,'صيانة العربية'))return this.fail('الخزنة لا تكفي للصيانة.');this.s.repaired=true;this.s.truckCondition=100;this.vehicle.condition=100;this.notice('الموتور اشتغل. العربية جاهزة لأول رحلة.');this.change();return true}
 generateOrder(first=false){const s=this.s;if(!s.repaired||!Object.values(s.contracts).some(Boolean))return;const limit=12+s.staff.rep*4;if(s.orders.filter(o=>!o.accepted).length>=limit){const i=s.orders.findIndex(o=>!o.accepted&&!o.first&&!o.special);if(i>=0){const bundle=s.orders[i].bundle;if(bundle)s.orders=s.orders.filter(o=>o.bundle!==bundle);else s.orders.splice(i,1);}else return;}
 let clients=s.clients.filter(c=>s.regions.includes(c.area)&&s.delivered>=(c.unlock||0));let c=first?s.clients[0]:clients[Math.floor(this.rng()*clients.length)];
 // Rotate the first three customers to guarantee a teachable progression.
 if(!first&&s.served.length<3){c=clients.find(c=>!s.served.includes(c.id)&&!s.orders.some(o=>o.client===c.id))||c;}
 let available=Object.keys(PRODUCTS).filter(p=>this.enabled(p));if(!available.length)return;if(s.weather==='heat'||s.season==='ramadan')available.push(...available.filter(id=>['juice','milkMix'].includes(id)));if(s.season==='school')available.push(...available.filter(id=>['bread','pastry','milkMix'].includes(id)));if(s.season==='eid')available.push(...available.filter(id=>['ghee','rice','chicken'].includes(id)));let pid=first&&available.includes('bread')?'bread':available[Math.floor(this.rng()*available.length)];
 const qty=first?10:10+Math.floor(this.rng()*3)*10;let margin=(c.area==='الدقهلية'?1.12:1)*(s.rep>=70?1.04:1);
 s.orders.push({id:s.seq++,client:c.id,pid,qty,price:Math.round(PRODUCTS[pid].sell*margin),accepted:false,discount:0,payment:'cash',expires:s.elapsed+(first?999999:210),first});this.onChange(s);
 }
 accept(id,discount=0,payment='cash'){const s=this.s,o=s.orders.find(o=>o.id===id);if(!o||o.accepted)return false;if(s.orders.filter(o=>o.accepted).length>=4)return this.fail('نفّذ الطلبات الحالية الأول (٤ طلبات كحد أقصى).');discount=Number(discount);if(![0,5,10].includes(discount)||!['cash','credit'].includes(payment))return false;
 const client=s.clients[o.client];const total=Math.round(o.qty*o.price*(1-discount/100));const reserved=s.orders.filter(v=>v.accepted&&v.payment==='credit'&&v.client===o.client).reduce((a,v)=>a+Math.round(v.qty*v.price*(1-v.discount/100)),0);
 if(payment==='credit'&&(client.trust<50||client.outstanding+reserved+total>client.credit))return this.fail('ثقة العميل أو حد الائتمان لا يسمح بالبيع الآجل.');
 if(total-o.qty*this.cost(o.pid)<0)return this.fail('الخصم هياكل هامش الربح. اختار خصم أقل.');o.accepted=true;o.discount=discount;o.payment=payment;o.deadline=s.elapsed+(o.first?999999:480);this.notice('تم تأكيد الطلب. جهّز البضاعة من المخزن.');this.change();return true}
 reject(id){const i=this.s.orders.findIndex(o=>o.id===id&&!o.accepted);if(i<0)return false;this.s.orders.splice(i,1);this.change();return true}
 buy(pid,qty){const s=this.s;qty=Number(qty);if(!PRODUCTS[pid]||!Number.isInteger(qty)||qty<1||qty>500)return this.fail('اختار كمية صحيحة من ١ إلى ٥٠٠ كرتونة.');if(!s.inventoried)return this.fail('اعمل الجرد الأول.');if(!this.enabled(pid))return this.fail('المنتج محتاج عقد توكيل.');const cid=PRODUCTS[pid].company;if(!s.warehouses[cid].owned)return this.fail('الشركة محتاجة مخزن مخصص.');if(cid==='dairy'&&!s.cooling||cid==='frozen'&&!s.freezer)return this.fail('تجهيزات درجة الحرارة المطلوبة غير متوفرة.');if(this.companyUsage(cid)+qty>s.warehouses[cid].capacity)return this.fail('مخزن '+COMPANIES[cid].short+' لا يسع الكمية.');if(this.stockTotal+this.pendingStock+this.reservedStorage+qty>s.capacity)return this.fail('مفيش مساحة كفاية في المخزن.');const unit=this.cost(pid),total=MONEY(unit*qty),gross=MONEY(this.listPrice(pid)*qty);if(!this.spend(total,false,'شراء '+qty+' كرتونة '+PRODUCTS[pid].name))return this.fail('الخزنة لا تكفي.');s.incoming.push({id:s.seq++,pid,qty,unit,total,gross,eta:s.elapsed+8,ready:false});this.notice('أمر الشراء اتبعت. العربية هتوصل على بالته الاستلام بعد ٨ ثواني لعب.');this.change();return true}
 receive(id){let s=this.s,i=s.incoming.findIndex(b=>b.id===id&&b.ready);if(i<0)return false;const b=s.incoming[i];s.stock.push({pid:b.pid,qty:b.qty,unit:b.unit,expires:s.day+PRODUCTS[b.pid].life});const cid=PRODUCTS[b.pid].company;s.purchases[cid]=MONEY(s.purchases[cid]+(b.gross??b.total));s.netPurchases[cid]=MONEY(s.netPurchases[cid]+b.total);s.incoming.splice(i,1);const error=b.id%4===0?Math.round(b.total*.07):0;s.invoices.push({id:s.seq++,type:'purchase',pid:b.pid,qty:b.qty,gross:b.gross??b.total,onCredit:!!b.onCredit,expected:b.total,amount:b.total+error,corrected:false,settled:false,day:s.day});this.notice('استلمت '+b.qty+' كرتونة '+PRODUCTS[b.pid].name+'؛ موجودين على الرف.');this.change();return true}
 consume(pid,qty){let need=qty,cost=0;const batches=this.s.stock.filter(b=>b.pid===pid).sort((a,b)=>a.expires-b.expires);for(const b of batches){let n=Math.min(need,b.qty);b.qty-=n;need-=n;cost+=n*b.unit;if(!need)break;}this.s.stock=this.s.stock.filter(b=>b.qty>0);return cost}
 pack(id){let s=this.s,o=s.orders.find(o=>o.id===id&&o.accepted);if(!o)return false;if(!this.canCarry(o.pid))return this.fail('الصنف يحتاج '+VEHICLES[COMPANIES[PRODUCTS[o.pid].company].vehicle].name+'. اختر العربية المناسبة.');if(s.carry)return this.fail('حمّل اللي في إيدك أو رجّعه الأول.');if(s.trip)return this.fail('استنى رجوع العربية عشان تجهز التحميل.');const loaded=s.cargo.filter(b=>b.order===id).reduce((a,b)=>a+b.qty,0);let n=Math.min(s.staff.worker?o.qty:10,o.qty-loaded);if(o.partialOK)n=Math.min(n,this.qty(o.pid));if(n<=0)return this.fail('الطلب محمّل بالكامل.');if(this.qty(o.pid)<n)return this.fail('المخزون لا يكفي. اطلب البضاعة الناقصة.');const expires=Math.min(...s.stock.filter(b=>b.pid===o.pid).map(b=>b.expires));let cost=this.consume(o.pid,n);s.carry={order:id,pid:o.pid,qty:n,cost,expires};this.notice('شايل '+n+' كرتونة '+PRODUCTS[o.pid].name+'. اتجه للعربية وحمّل.');this.change();return true}
 returnCarry(){let s=this.s,b=s.carry;if(!b)return false;s.stock.push({pid:b.pid,qty:b.qty,unit:b.cost/b.qty,expires:b.expires??s.day+1});s.carry=null;this.change();return true}
 load(){let s=this.s;if(!s.carry)return this.fail('جهّز بضاعة من الرف الأول.');if(s.trip)return this.fail('العربية في رحلة.');if(!this.canCarry(s.carry.pid))return this.fail('العربية غير مناسبة لدرجة حرارة البضاعة.');let cap=this.vehicle.capacity,loaded=s.cargo.reduce((a,b)=>a+b.qty,0);if(loaded+s.carry.qty>cap)return this.fail('الحمولة القصوى '+cap+' كرتونة. رجّع اللي في إيدك للمخزن.');s.cargo.push(s.carry);s.carry=null;this.notice('البضاعة اتحملت فعليًا في العربية.');this.change();return true}
 unload(){const s=this.s;if(s.trip)return false;for(const b of s.cargo)s.stock.push({pid:b.pid,qty:b.qty,unit:b.cost/b.qty,expires:b.expires??s.day+1});s.cargo=[];this.change();return true}
 dispatch(route='safe'){let s=this.s;if(!['safe','fast'].includes(route))return false;if(!s.repaired)return this.fail('العربية محتاجة إصلاح.');if(s.trip)return this.fail('فيه رحلة شغالة بالفعل.');if(!s.staff.driver)return this.fail('عيّن سائق أولًا.');if(s.cargo.some(b=>!this.canCarry(b.pid)))return this.fail('نوع العربية لا يناسب أحد أصناف الحمولة.');if(s.truckCondition<20)return this.fail('حالة العربية سيئة. اعمل صيانة.');if(s.carry)return this.fail('حمّل الكراتين اللي في إيدك الأول.');let ids=[...new Set(s.cargo.map(b=>b.order))];if(!ids.length)return this.fail('العربية فاضية.');const orders=ids.map(id=>s.orders.find(o=>o.id===id));if(orders.some(o=>!o||s.cargo.filter(b=>b.order===o.id).reduce((a,b)=>a+b.qty,0)!==o.qty))return this.fail('كمّل تحميل كل طلب قبل خروج العربية.');const far=orders.some(o=>s.clients[o.client].area==='الدقهلية');let fee=far?180:70;fee+=Math.max(0,new Set(orders.map(o=>o.client)).size-1)*20;if(route==='fast')fee+=60;if(!this.spend(fee,true,'وقود ومصاريف خط التوزيع'))return this.fail('الخزنة لا تكفي لمصاريف الرحلة.');let duration=(far?50:28)+orders.length*4;if(route==='fast')duration=Math.round(duration*.65);s.trip=this.buildTrip(orders,s.cargo,route);s.trip.vehicleId=this.vehicle.id;s.orders=s.orders.filter(o=>!ids.includes(o.id));s.cargo=[];s.truckCondition=Math.max(0,s.truckCondition-(route==='fast'?9:4));this.vehicle.condition=s.truckCondition;this.notice('العربية خرجت بـ'+orders.length+' طلب. '+(s.staff.driver?'السائق ماسك خط التوزيع.':'أنت بتتابع رحلة التوصيل؛ استنى الرجوع.'));this.change();return true}
 buildTrip(orders,cargo,route='safe',start=MAP.depot){
 const legs=[],remainingOrders=[...orders],fast=route==='fast';let from=start;
 while(remainingOrders.length){remainingOrders.sort((a,b)=>{const plan=this.s?.routePriorities?.[this.s.selectedVehicle]||[],ai=plan.indexOf(a.client),bi=plan.indexOf(b.client);if(ai!==bi&&(ai>=0||bi>=0))return (ai<0?99:ai)-(bi<0?99:bi);const ap=MAP.clients[a.client],bp=MAP.clients[b.client];return Math.hypot(ap.x-from.x,ap.y-from.y)-Math.hypot(bp.x-from.x,bp.y-from.y)});const client=remainingOrders[0].client,stopOrders=remainingOrders.filter(o=>o.client===client);for(const o of stopOrders)remainingOrders.splice(remainingOrders.indexOf(o),1);
 const to=MAP.clients[client],points=routePoints(from,to,fast);legs.push({kind:'drive',points,duration:Math.max(7,pathDistance(points)/(fast?18:12)),client,returning:false});legs.push({kind:'unload',client,orderIds:stopOrders.map(o=>o.id),duration:5+stopOrders.length*2});from=to;}
 const points=routePoints(from,MAP.depot,fast);legs.push({kind:'drive',points,duration:Math.max(7,pathDistance(points)/(fast?18:12)),returning:true});const total=legs.reduce((a,l)=>a+l.duration,0);
 return {orders:JSON.parse(JSON.stringify(orders)),cargo:JSON.parse(JSON.stringify(cargo)),legs,legIndex:0,legElapsed:0,total,remaining:total,route,returning:false,delivered:false,deliveredOrders:[]};
 }
 deliverOrder(o,t){const s=this.s;if(t.deliveredOrders.includes(o.id))return;const c=s.clients[o.client],late=s.elapsed>o.deadline;const amount=MONEY(o.price*o.qty*(1-o.discount/100)),cost=MONEY(t.cargo.filter(b=>b.order===o.id).reduce((a,b)=>a+b.cost,0));s.revenue=MONEY(s.revenue+amount);s.cogs=MONEY(s.cogs+cost);c.outstanding=MONEY(c.outstanding+amount);c.trust=Math.max(0,Math.min(100,c.trust+(late?-6:4)));s.rep=Math.max(0,Math.min(100,s.rep+(late?-2:1)));s.invoices.push({id:s.seq++,type:'sale',client:o.client,pid:o.pid,qty:o.qty,expected:amount,amount,cost,repAssigned:o.repAssigned||0,payment:o.payment,due:s.day+(o.payment==='credit'?3:0),approved:false,settled:false,day:s.day});t.deliveredOrders.push(o.id);t.cargo=t.cargo.filter(b=>b.order!==o.id);this.log('تسليم إلى '+c.name+' — مستحق التحصيل',0);this.notice('تم تفريغ '+o.qty+' كرتونة عند '+c.name+'. الفاتورة وصلت الحسابات.');}
 moveTrip(dt){const s=this.s,t=s.trip;if(!t)return;let left=dt;while(left>0&&s.trip){const leg=t.legs[t.legIndex],step=Math.min(left,Math.max(0,leg.duration-t.legElapsed));t.legElapsed+=step;t.remaining=Math.max(0,t.remaining-step);left-=step;if(t.legElapsed+1e-8<leg.duration)break;if(leg.kind==='unload'){for(const id of leg.orderIds){const o=t.orders.find(o=>o.id===id);if(o)this.deliverOrder(o,t);}t.delivered=t.deliveredOrders.length===t.orders.length;}t.legIndex++;t.legElapsed=0;if(t.legIndex>=t.legs.length){this.arrive();break;}t.returning=!!t.legs[t.legIndex].returning;this.change();}}
 arrive(){const s=this.s,t=s.trip;if(!t)return;for(const o of t.orders)this.deliverOrder(o,t);s.tripHistory.unshift({day:s.day,clients:t.orders.map(o=>o.client),route:t.route,orders:t.orders.length});s.tripHistory=s.tripHistory.slice(0,20);s.trip=null;this.notice('العربية رجعت فاضية وركنت في الوكالة.');this.change();}

 correct(id){const v=this.s.invoices.find(v=>v.id===id&&!v.settled);if(!v)return false;if(v.amount===v.expected)return this.fail('الفاتورة مطابقة للمستند؛ مفيش فرق للتصحيح.');v.amount=v.expected;v.corrected=true;this.notice('اتصحح فرق الفاتورة طبقًا لأمر الشراء؛ مفيش مبالغ وهمية اتضافت.');this.change();return true}
 approve(id){let s=this.s,v=s.invoices.find(v=>v.id===id&&!v.settled);if(!v)return false;if(v.amount!==v.expected)return this.fail('المبلغ مختلف عن المستند المرجعي. صحّح الفرق قبل الاعتماد.');if(v.type==='purchase'){v.approved=true;v.settled=true;this.notice(v.onCredit?'فاتورة الشراء الآجل اتراجعت؛ السداد منفصل في دفتر علاقات الشركات.':'فاتورة الشراء اتراجعت. الدفع تم وقت طلب البضاعة.');}else{v.approved=true;if(s.day<v.due){this.notice('الفاتورة معتمدة؛ موعد التحصيل يوم '+v.due);this.change();return true;}s.money=MONEY(s.money+v.amount);v.settled=true;if(v.repAssigned){const commission=MONEY(v.amount*.01);s.commissionDue=MONEY(s.commissionDue+commission);s.expenses=MONEY(s.expenses+commission);}s.clients[v.client].outstanding=Math.max(0,s.clients[v.client].outstanding-v.amount);s.clients[v.client].served++;if(!s.served.includes(v.client))s.served.push(v.client);s.delivered++;this.log('تحصيل من '+s.clients[v.client].name,v.amount);this.notice('اتحصّل '+v.amount.toLocaleString('ar-EG')+' ج.م من '+s.clients[v.client].name);}
 this.change();return true}
 contract(cid){const s=this.s,c=COMPANIES[cid];if(!c||s.contracts[cid])return false;const missing=this.requirements(cid).filter(r=>!r.met);if(missing.length)return this.fail('شروط ناقصة: '+missing.map(r=>r.text).join('، '));if(!this.spend(c.fee,false,'توقيع توكيل '+c.name))return this.fail('الخزنة لا تكفي لرسوم العقد.');s.contracts[cid]=true;s.purchases[cid]=0;s.netPurchases[cid]=0;s.cycles[cid]={startDay:s.day,endDay:s.day+7,target:c.target,successes:0,misses:0};this.notice('وكالة سعيد موزع معتمد لـ'+c.name+'؛ خصم فوري ١٢٪ ومؤجل ٢٪ بشروط التارجت.');if(!s.delivered&&!s.orders.length)this.generateOrder(true);this.change();return true}
 settleCycles(){const s=this.s;for(const [cid,c]of Object.entries(COMPANIES)){let period=s.cycles[cid];if(!s.contracts[cid]||!period)continue;while(s.day>=period.endDay){const achieved=s.purchases[cid]>=period.target,rebate=achieved?MONEY(s.purchases[cid]*c.deferred):0;s.money=MONEY(s.money+rebate);s.expenses=MONEY(s.expenses-rebate);if(achieved){period.successes++;s.successfulCycles++;period.misses=0;s.rep=Math.min(100,s.rep+2);this.log('خصم مؤجل ٢٪ — '+c.short,rebate);this.notice('حققت تارجت '+c.short+'؛ خصم مؤجل '+rebate.toFixed(2)+' ج.م.');}else{period.misses++;s.rep=Math.max(0,s.rep-(period.misses>=2?2:0));this.notice('تارجت '+c.short+' لم يتحقق. '+(period.misses>=2?'إنذار أداء: السمعة انخفضت نقطتين.':'الدورة القادمة فرصة تصحيح؛ لا يوجد خصم مؤجل.'),'bad');}s.cycleHistory.unshift({cid,endDay:period.endDay,gross:s.purchases[cid],net:s.netPurchases[cid],target:period.target,achieved,rebate});s.cycleHistory=s.cycleHistory.slice(0,60);s.purchases[cid]=0;s.netPurchases[cid]=0;period.startDay=period.endDay;period.endDay+=7;if(achieved)period.target=Math.min(c.target*2,Math.round(period.target*1.05));}}}
 payCommissions(){const amount=this.s.commissionDue;if(!amount)return false;if(!this.spend(amount,false,'صرف عمولات المناديب'))return this.fail('الخزنة لا تكفي.');this.s.commissionPaid=MONEY(this.s.commissionPaid+amount);this.s.commissionDue=0;this.change();return true}

 upgrade(type,cid='bakery'){const s=this.s;const prices={warehouse:4000,cooling:3000,freezer:7000,office:6000};if(type==='truck')return this.buyVehicle('normal');if(!prices[type])return false;if(type==='warehouse'&&(!s.warehouses[cid]?.owned||s.warehouses[cid].capacity>=640))return this.fail('اختر مخزنًا مخصصًا قائمًا؛ الحد ٦٤٠ كرتونة لكل توكيل.');if(type==='cooling'&&(s.cooling||!s.warehouses.dairy.owned))return this.fail('جهّز مخزن مزارع نور أولًا؛ التبريد منفصل عن العربية.');if(type==='freezer'&&(s.freezer||!s.warehouses.frozen.owned))return this.fail('جهّز مخزن قطوف أولًا.');if(type==='office'&&s.officeLevel>=2)return false;if(!this.spend(prices[type],false,'تطوير تجهيزات الوكالة'))return this.fail('الخزنة لا تكفي.');if(type==='warehouse'){const added=Math.min(160,640-s.warehouses[cid].capacity);s.warehouses[cid].capacity+=added;s.capacity+=added;}if(type==='cooling')s.cooling=true;if(type==='freezer')s.freezer=true;if(type==='office')s.officeLevel++;this.notice('التطوير تم وظهر في تجهيزات الوكالة.');this.change();return true}
 hire(role){const s=this.s,c=ROLES[role];if(!c||s.staff[role]>=c.max)return false;if(!s.inventoried)return this.fail('اعتمد الجرد أولًا.');if(role!=='driver'&&(!s.staff.driver||s.delivered<(role==='rep'?3:1)))return this.fail('عيّن السائق واكتسب خبرة توزيع أولًا: المندوب بعد ٣ طلبيات، وباقي الفريق بعد أول طلبية.');if(!this.spend(c.fee,false,'تعيين '+c.name))return this.fail('الخزنة لا تكفي.');s.staff[role]++;this.notice(c.name+' انضم براتب '+c.salary+' ج.م لكل ٧ أيام'+(role==='rep'?' وعمولة ١٪ على مبيعاته المحصلة.':'.'));this.change();return true}

 unlock(){let s=this.s;if(s.regions.includes('الدقهلية'))return false;if(!s.staff.driver||!Object.values(s.contracts).some(Boolean))return this.fail('خط الدقهلية محتاج سائق وتوكيل واحد على الأقل.');if(!this.spend(5000,false,'فتح خط الدقهلية'))return this.fail('الخزنة لا تكفي.');s.regions.push('الدقهلية');this.notice('اتفتح خط الدقهلية. طلبات المحافظة هتبدأ توصل.');this.generateOrder();this.change();return true}
 loan(){let s=this.s;if(s.debt>8000)return this.fail('سدّد التمويل الحالي قبل قرض جديد.');s.debt+=10000;s.money+=10000;this.log('تمويل إضافي',10000);this.change();return true}
 repay(amount){let s=this.s;amount=Math.min(s.debt,Number(amount));if(!Number.isFinite(amount)||amount<=0||!this.spend(amount,false,'سداد التزامات'))return this.fail('راجع مبلغ السداد والخزنة.');s.debt-=amount;this.change();return true}
 resolveEvent(option){let s=this.s,e=s.event;if(!e)return false;
 if(e.kind==='power'){if(option==='pay'){if(!this.spend(300,true,'تشغيل مولد التبريد'))return this.fail('الخزنة لا تكفي.');this.notice('المولد حافظ على شحنة الألبان.');}else{for(const b of s.stock.filter(b=>PRODUCTS[b.pid].company==='dairy')){let n=Math.ceil(b.qty*.2);b.qty-=n;s.expenses+=n*b.unit;}this.notice('انقطاع الكهرباء أتلف ٢٠٪ من مخزون الألبان.','bad');}}
 if(e.kind==='rival'){if(option==='pay'){if(!this.spend(450,true,'حملة خدمة العملاء'))return this.fail('الخزنة لا تكفي.');s.rep=Math.min(100,s.rep+5);s.clients.forEach(c=>c.trust=Math.min(100,c.trust+2));this.notice('خدمة العملاء رفعت ثقة السوق في وكالة سعيد.');}else{s.rep=Math.max(0,s.rep-3);this.notice('المنافس جذب جزء من الاهتمام. سمعة الوكالة انخفضت ٣ نقاط.','bad');}}
 s.event=null;this.change();return true}
 nextDay(){let s=this.s;s.day++;s.time=0;let expired=0;for(const b of s.stock){if(b.expires<=s.day){expired+=b.qty*b.unit;b.qty=0;}}s.stock=s.stock.filter(b=>b.qty>0);s.cargo=s.cargo.filter(b=>{if((b.expires??Infinity)<=s.day){expired+=b.cost;return false;}return true;});if(s.carry&&(s.carry.expires??Infinity)<=s.day){expired+=s.carry.cost;s.carry=null;}if(expired){s.expenses+=expired;this.log('تالف انتهاء صلاحية',0);this.notice('بضاعة بقيمة '+expired+' ج.م انتهت صلاحيتها. راجع الشراء على قد الطلب.','bad');}
 const utility=90+(s.cooling?80:0)+(s.freezer?120:0)+s.officeLevel*25;s.money-=utility;s.expenses+=utility;this.log('مصاريف تشغيل يومية',-utility);
 if((s.day-1)%7===0){let salary=s.staff.driver*1600+s.staff.worker*1200+s.staff.rep*1500+s.staff.accountant*1400;let debtPay=Math.min(s.debt,1000,Math.max(0,s.money-salary));s.money-=salary+debtPay;s.expenses+=salary;s.debt-=debtPay;this.log('رواتب وسداد أسبوعي',-salary-debtPay);let rebates=0;s.lastStatement={day:s.day,revenue:s.revenue,cogs:s.cogs,profit:this.profit,salary,debtPay,rebates};this.notice('إقفال الأسبوع جاهز في دفتر الحسابات.');}
 this.settleCycles();if(s.day>=s.nextEvent&&s.mission>=9&&!s.event){s.event={kind:s.cooling&&s.day%2===0?'power':'rival'};s.nextEvent=s.day+3;this.notice('فيه قرار جديد محتاجك في التليفون.');}
 if(s.money<0)this.notice('الخزنة بالسالب. حصّل المستحقات أو اطلب تمويل من المكتب.','bad');this.change();}
 tick(dt){const s=this.s;if(!s.signed||!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,60);s.elapsed+=dt;s.time+=dt*(DAY_SECONDS/(s.dayLength||DAY_SECONDS));
 for(const b of s.incoming)if(!b.ready&&s.elapsed>=b.eta){b.ready=true;this.notice('شحنة جديدة وصلت على بالته الاستلام.');this.onChange(s)}
 this.moveTrip(dt);
 if(s.repaired&&Object.values(s.contracts).some(Boolean)){s.orderTick+=dt;while(s.orderTick>=ORDER_SECONDS){s.orderTick-=ORDER_SECONDS;this.generateOrder();}s.orders=s.orders.filter(o=>o.accepted||o.first||o.expires>s.elapsed);}
 if(s.staff.worker&&s.auto)for(const b of [...s.incoming])if(b.ready)this.receive(b.id);
 if(s.staff.accountant&&s.auto)for(const v of [...s.invoices])if(!v.settled&&v.amount===v.expected&&(v.type==='purchase'||s.day>=v.due))this.approve(v.id);
 s.autoTick+=dt;
 if(!s.pickingJob&&!s.workerJob&&s.staff.rep&&s.auto&&s.autoTick>=8/s.staff.rep&&!s.trip&&!s.carry&&s.staff.driver&&s.staff.worker){s.autoTick=0;let o=s.orders.find(o=>!o.accepted&&this.qty(o.pid)>=o.qty&&this.canCarry(o.pid));if(o){this.accept(o.id,0,this.terms(o.client).payment==='credit'?'credit':'cash');o.repAssigned=1+Math.floor(this.rng()*s.staff.rep);}o=s.orders.find(o=>o.accepted&&this.canCarry(o.pid)&&this.qty(o.pid)>=o.qty&&!s.cargo.some(b=>b.order===o.id)&&!this.otherLoads().some(b=>b.order===o.id));if(o&&s.cargo.length===0){o.repAssigned=o.repAssigned||1;if(this.pack(o.id)&&!s.pickingJob){this.load();this.dispatch();}}}
 if(s.time>=DAY_SECONDS)this.nextDay();
 }

 static validate(data){
 if(data?.testMode&&!Simulation.allowOwnerStates)throw Error('ده حفظ نسخة الاختبار الخاصة؛ افتحه في نسخة المالك فقط.');
 const error=()=>{throw Error('ملف الحفظ غير صالح أو تالف.');};
 if(!data||![3,4].includes(data.version))throw Error('الحفظ لازم يكون من وكالة سعيد ٣ أو ٤.');
 let d=JSON.parse(JSON.stringify(data));
 if(d.version===3){const old=d,base=fresh(),alias={cleaner:'rice',detergent:'oil',dish:'pasta'};for(const list of [old.stock,old.incoming,old.orders,old.cargo,old.invoices,old.trip?.orders,old.trip?.cargo])if(Array.isArray(list))for(const b of list)if(alias[b.pid])b.pid=alias[b.pid];if(old.carry&&alias[old.carry.pid])old.carry.pid=alias[old.carry.pid];
 d={...base,...old,version:4,contracts:{bakery:!!old.contracts?.bakery,dairy:!!old.contracts?.dairy,pantry:!!old.contracts?.clean,frozen:false},purchases:{bakery:old.purchases?.bakery||0,dairy:old.purchases?.dairy||0,pantry:old.purchases?.clean||0,frozen:0},netPurchases:{bakery:old.purchases?.bakery||0,dairy:old.purchases?.dairy||0,pantry:old.purchases?.clean||0,frozen:0},warehouses:base.warehouses,cycles:{},successfulCycles:0,firstReward:old.delivered>0,completed:false,freezer:false,vehicles:[],selectedVehicle:1,commissionDue:0,commissionPaid:0,cycleHistory:[],tripHistory:[],autoTick:0};
 if(d.repaired&&((d.stock||[]).length||(d.orders||[]).length||(d.incoming||[]).length||(d.cargo||[]).length||d.carry||d.trip||d.delivered))d.contracts.bakery=true;
 if(!Number.isInteger(old.truckCount)||old.truckCount<1||old.truckCount>3)error();for(let i=0;i<old.truckCount;i++)d.vehicles.push({id:i+1,kind:i===0&&old.cooling&&old.contracts?.dairy?'chilled':'normal',condition:old.truckCondition,capacity:60});
 for(const [cid,c]of Object.entries(COMPANIES)){const used=[...(d.stock||[]),...(d.incoming||[]),...(d.cargo||[])].filter(b=>PRODUCTS[b.pid]?.company===cid).reduce((a,b)=>a+(Number.isFinite(b.qty)?b.qty:0),0);d.warehouses[cid]={owned:cid==='bakery'?d.inventoried:!!d.contracts[cid],capacity:Math.max(c.warehouse,used,cid==='bakery'?old.capacity:0)};if(d.contracts[cid])d.cycles[cid]={startDay:d.day,endDay:d.day+7,target:c.target,successes:0,misses:0};}
 d.capacity=Math.max(160,Object.values(d.warehouses).filter(w=>w.owned).reduce((a,w)=>a+w.capacity,0));d.mission=Math.min(16,old.delivered?11:0);d.time=(Number(d.time)||0)/180*DAY_SECONDS;
 if(d.trip){d.trip=Simulation.prototype.buildTrip(d.trip.orders,d.trip.cargo,d.trip.route||'safe');d.trip.vehicleId=1;}
 }
 const base=fresh();for(const k of Object.keys(base))if(!(k in d))error();
 const number=(n,min=-1e12,max=1e12)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;
 for(const k of ['money','debt','day','time','elapsed','rep','capacity','mission','seq','revenue','cogs','expenses','chapter','officeLevel','truckCount','truckCondition','delivered','orderTick','nextEvent','successfulCycles','commissionDue','commissionPaid','autoTick'])if(!number(d[k]))error();
 for(const k of ['day','mission','seq','chapter','officeLevel','truckCount','capacity','delivered','successfulCycles'])if(!Number.isInteger(d[k]))error();
 if(!number(d.day,1,100000)||!number(d.mission,0,MISSIONS.length-1)||!number(d.capacity,1,100000)||!number(d.debt,0)||!number(d.officeLevel,0,2)||!number(d.truckCount,1,5)||!number(d.truckCondition,0,100)||!number(d.rep,0,100)||!number(d.time,0,DAY_SECONDS)||!number(d.commissionDue,0)||!number(d.commissionPaid,0))error();
 for(const k of ['stock','incoming','orders','cargo','invoices','clients','ledger','regions','served','notices','vehicles','cycleHistory','tripHistory'])if(!Array.isArray(d[k])||d[k].length>2000)error();
 for(const k of ['signed','inventoried','repaired','cooling','freezer','firstReward','completed','auto'])if(typeof d[k]!=='boolean')error();
 if(!d.staff||Object.entries(ROLES).some(([k,r])=>!Number.isInteger(d.staff[k])||!number(d.staff[k],0,r.max)))error();
 if(d.vehicles.length<1||d.vehicles.length>5||d.vehicles.some(v=>!v||!Number.isInteger(v.id)||!VEHICLES[v.kind]||!number(v.condition,0,100)||v.capacity!==(VEHICLES[v.kind]?.capacity||60))||new Set(d.vehicles.map(v=>v.id)).size!==d.vehicles.length||!d.vehicles.some(v=>v.id===d.selectedVehicle)||d.truckCount!==d.vehicles.length)error();
 for(const cid of Object.keys(COMPANIES)){if(!d.contracts||typeof d.contracts[cid]!=='boolean'||!d.purchases||!number(d.purchases[cid],0)||!d.netPurchases||!number(d.netPurchases[cid],0))error();const w=d.warehouses?.[cid];if(!w||typeof w.owned!=='boolean'||!Number.isInteger(w.capacity)||!number(w.capacity,1,100000))error();const c=d.cycles?.[cid];if(d.contracts[cid]&&(!c||!number(c.startDay,1)||!number(c.endDay,c.startDay+1)||!number(c.target,1)||!number(c.successes,0)||!number(c.misses,0)))error();}
 const batch=b=>b&&PRODUCTS[b.pid]&&Number.isInteger(b.qty)&&number(b.qty,1,100000);
 const order=o=>batch(o)&&number(o.id,1)&&Number.isInteger(o.client)&&o.client>=0&&o.client<CLIENTS.length&&number(o.price,0)&&[0,5,10].includes(o.discount)&&['cash','credit'].includes(o.payment)&&typeof o.accepted==='boolean'&&number(o.expires,0)&&(!o.accepted||number(o.deadline,0));
 if(d.stock.some(b=>!batch(b)||!number(b.unit,0)||!number(b.expires,0)))error();if(d.incoming.some(b=>!batch(b)||!number(b.unit,0)||!number(b.total,0)||!number(b.id,1)||!number(b.eta,0)||typeof b.ready!=='boolean'))error();if(d.orders.some(o=>!order(o)))error();
 const cargo=b=>batch(b)&&number(b.cost,0)&&number(b.order,1);if(d.cargo.some(b=>!cargo(b))||(d.carry&&!cargo(d.carry)))error();
 if(d.trip){const t=d.trip;if(t.refusedOrders&&(!Array.isArray(t.refusedOrders)||t.refusedOrders.some(id=>!t.orders.some(o=>o.id===id))))error();if(!Array.isArray(t.orders)||t.orders.length>4||t.orders.some(o=>!order(o))||!Array.isArray(t.cargo)||t.cargo.some(b=>!cargo(b))||!number(t.remaining,0,10000)||!number(t.total,.1,10000)||!Array.isArray(t.legs)||!t.legs.length||t.legs.length>16||!Number.isInteger(t.legIndex)||!number(t.legIndex,0,t.legs.length-1)||!Array.isArray(t.deliveredOrders)||t.deliveredOrders.some(id=>!t.orders.some(o=>o.id===id)))error();for(const l of t.legs){if(!number(l.duration,.1,10000)||!['drive','unload'].includes(l.kind))error();if(l.kind==='drive'&&(!Array.isArray(l.points)||l.points.length<2||l.points.length>8||l.points.some(p=>!number(p.x,0,MAP.width)||!number(p.y,0,MAP.height))))error();if(l.kind==='unload'&&(!Number.isInteger(l.client)||!number(l.client,0,CLIENTS.length-1)||!Array.isArray(l.orderIds)||l.orderIds.some(id=>!t.orders.some(o=>o.id===id))))error();}if(!number(t.legElapsed,0,t.legs[t.legIndex].duration))error();}
 if(d.invoices.some(v=>!v||!['sale','purchase'].includes(v.type)||!PRODUCTS[v.pid]||!number(v.id,1)||!number(v.qty,1)||!number(v.amount,0)||!number(v.expected,0)||typeof v.settled!=='boolean'||(v.type==='sale'&&(!Number.isInteger(v.client)||v.client<0||v.client>=CLIENTS.length||!number(v.due,0)))))error();
 if(d.clients.length===6)d.clients.push(...CLIENTS.slice(6).map(c=>({...c,served:0,outstanding:0})));if(d.clients.length!==CLIENTS.length)error();d.clients=d.clients.map((c,i)=>{if(!c||!number(c.trust,0,100)||!number(c.served,0)||!number(c.outstanding,0))error();return {...CLIENTS[i],trust:c.trust,served:c.served,outstanding:c.outstanding};});
 if(d.regions.some(r=>!['دمياط','الدقهلية'].includes(r))||d.served.some(i=>!Number.isInteger(i)||i<0||i>=CLIENTS.length))error();if(d.event&&!['power','rival'].includes(d.event.kind))error();
 if(d.settings?.lighting!==undefined&&!['balanced','bright','soft'].includes(d.settings.lighting))error();if(!d.position||!number(d.position.x,-60,14)||!number(d.position.z,-45,18))error();if(!d.settings||typeof d.settings.sound!=='boolean'||!['high','low'].includes(d.settings.quality))error();
 d.name=String(d.name).slice(0,30);d.ledger=d.ledger.filter(v=>v&&number(v.day,1)&&number(v.amount)).map(v=>({...v,text:String(v.text).slice(0,200)}));d.notices=d.notices.filter(v=>v&&number(v.day,1)).map(v=>({...v,text:String(v.text).slice(0,300)}));
 if(d.lastStatement&&['day','revenue','cogs','profit','salary','debtPay','rebates'].some(k=>!number(d.lastStatement[k])))error();
 if(d.cycleHistory.some(h=>!COMPANIES[h.cid]||['endDay','gross','net','target','rebate'].some(k=>!number(h[k],0))||typeof h.achieved!=='boolean'))error();
 return d;
 }

}
installEconomyFeatures(Simulation,{PRODUCTS,COMPANIES,ROLES,MAP,routePosition,DAY_SECONDS,MONEY,fresh});
installExpansion(Simulation,{PRODUCTS,COMPANIES,ROLES,MAP,MONEY});
installLogistics(Simulation,{PRODUCTS,COMPANIES,MAP,MONEY,DAY_SECONDS});
installDevelopment(Simulation,{PRODUCTS});
installStory(Simulation);
installBusiness(Simulation,{PRODUCTS,COMPANIES,MAP,DAY_SECONDS,MONEY});
export {Simulation,PRODUCTS,COMPANIES,MISSIONS,VEHICLES,ROLES,MAP,routePosition,DAY_SECONDS,ORDER_SECONDS,MONEY,fresh};
