import {DevelopmentUI} from './ui-development.js';
import {LogisticsUI} from './ui-logistics.js';
import {installMobileUI} from './mobile.js';
import {VoiceUI} from './voice.js';
import {EditorUI} from './ui-editor.js';
import {CloudUI} from './ui-cloud.js';
import {ExpansionUI} from './ui-expansion.js';
import {GuideUI} from './guide.js';
import * as Agency from './economy.js';
import {AgencyWorld} from './world.js';
import {AgencyUI} from './ui-v4.js';
import {installFeatureUI} from './ui-features.js';
import {AgencyNetwork} from './network.js';
import {SaveSlots} from './save-slots.js';
import {registerPWA,notifyLocal} from './pwa.js';
(function(){'use strict';
const {Simulation,PRODUCTS:P,COMPANIES:C,MISSIONS,DAY_SECONDS}=Agency,$=s=>document.querySelector(s);const localStore=(()=>{try{return localStorage}catch{return {getItem(){return null},setItem(){throw Error('الحفظ المحلي غير متاح')}}}})();let slots;try{slots=new SaveSlots(localStore)}catch{slots=new SaveSlots({getItem(){return null},setItem(){throw Error('الحفظ المحلي غير متاح')}})}const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const num=n=>Math.round(n).toLocaleString('ar-EG'),egp=n=>Number(n).toLocaleString('ar-EG',{maximumFractionDigits:2})+' ج.م';let saved=null,saveError=false;try{const raw=slots.load();if(raw)saved=Simulation.validate(raw)}catch(e){saveError=true}let sim=new Simulation(saved||undefined),started=false,paused=false,panel=null,world,saveTick=0,audio=null,ambientGain=null,dialogFocus=null,v4=null,panelDirty=false,mapTick=0;
const staffNames={driver:'سائق',worker:'عامل مخزن',rep:'مندوب مبيعات',accountant:'محاسب'};
function sound(type){if(!sim.s.settings.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const t=audio.currentTime;
 if(!ambientGain){const buffer=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const wind=audio.createBufferSource(),filter=audio.createBiquadFilter();wind.buffer=buffer;wind.loop=true;filter.type='lowpass';filter.frequency.value=450;ambientGain=audio.createGain();ambientGain.gain.value=.014;wind.connect(filter);filter.connect(ambientGain);ambientGain.connect(audio.destination);wind.start();}
 if(type==='box'||type==='stamp'||type==='step'){let buffer=audio.createBuffer(1,audio.sampleRate*.12,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/data.length*9);let source=audio.createBufferSource(),gain=audio.createGain(),filter=audio.createBiquadFilter();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=type==='stamp'?1800:500;gain.gain.value=type==='step'?.025:.12;source.connect(filter);filter.connect(gain);gain.connect(audio.destination);source.start();return;}
 const count=type==='phone'?4:type==='good'?2:1;for(let i=0;i<count;i++){let o=audio.createOscillator(),g=audio.createGain();o.type=type==='engine'?'sawtooth':'sine';o.frequency.setValueAtTime(type==='bad'?180:type==='engine'?55:type==='phone'?660:440+i*220,t+i*.12);if(type==='engine')o.frequency.linearRampToValueAtTime(95,t+.6);g.gain.setValueAtTime(0,t+i*.12);g.gain.linearRampToValueAtTime(type==='engine'?.035:.025,t+i*.12+.015);g.gain.exponentialRampToValueAtTime(.001,t+i*.12+(type==='engine'?.9:.16));o.connect(g);g.connect(audio.destination);o.start(t+i*.12);o.stop(t+i*.12+1);}}catch(e){}}

function toast(text,type='good'){const el=document.createElement('div');el.className='toast '+type;el.textContent=text;$('#toasts').appendChild(el);sound(text.includes('الموتور')||text.includes('العربية خرجت')?'engine':text.includes('كراتين')||text.includes('كرتونة')?'box':text.includes('اتحصّل')||text.includes('اتراجعت')?'stamp':type);setTimeout(()=>el.remove(),6500)}
function save(){if(!started)return;try{slots.save(sim.s);if(sim.s.mode==='challenge'&&sim.s.challenge?.result!==null&&sim.s.challenge){const key='saeed_local_scores',scores=JSON.parse(localStorage.getItem(key)||'[]'),id=slots.active+':'+sim.s.name+':'+sim.s.challenge.result;if(!scores.some(v=>v.id===id)){scores.push({id,name:sim.s.name,score:sim.s.challenge.result});localStorage.setItem(key,JSON.stringify(scores.sort((a,b)=>b.score-a.score).slice(0,20)))}}saveError=false}catch(e){if(!saveError){toast('الحفظ التلقائي غير متاح في المتصفح ده. صدّر نسخة من الإعدادات.','bad');saveError=true;}}}
function bind(){let lastOrder=0;sim.onNotice=(text,type)=>{toast(text,type);notifyLocal('وكالة سعيد',text)};sim.onChange=()=>{let latest=Math.max(0,...sim.s.orders.map(o=>o.id));if(started&&latest>lastOrder){sound('phone');voices.play('order');}lastOrder=latest;panelDirty=true;refresh();save()};}bind();
function refresh(){const s=sim.s;$('#cash').textContent=egp(s.money);$('#rep').textContent=num(s.rep)+' / ١٠٠';$('#day').textContent='اليوم '+num(s.day);const minutes=(8*60+Math.floor(s.time/DAY_SECONDS*24*60))%(24*60);$('#clock').textContent=String(Math.floor(minutes/60)).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');const m=sim.mission;$('#mission').hidden=!started||s.mode==='endless';$('#mission').innerHTML='<small>الفصل '+num(s.chapter)+' / '+(s.chapter===1?'بداية جديدة':s.chapter===2?'اسم في السوق':'من دمياط للدلتا')+'</small><h3>'+m.title+'</h3><p>'+m.hint+'</p><div class="progress"><i style="width:'+Math.max(4,s.mission/(MISSIONS.length-1)*100)+'%"></i></div><button class="mission-link" data-go="'+m.target+'">خدني للمكان ←</button><div class="mission-step"><b>'+num(s.mission+1)+'</b> / '+num(MISSIONS.length)+' مرحلة'+(s.completed?' · الحكاية اكتملت':'')+'</div>';$('#carrying').hidden=!s.carry;if(s.carry)$('#carrying').textContent='شايل '+num(s.carry.qty)+' كرتونة '+P[s.carry.pid].name;world?.sync(s);const inbox=$('#inbox');if(inbox){inbox.hidden=!started;inbox.innerHTML='<small>طلبات مستمرة كل ١٠ ثوانٍ</small><b>'+num(s.orders.filter(o=>!o.accepted).length)+' طلب جديد · '+num(s.orders.filter(o=>o.accepted).length)+' مؤكد</b>';}
 const mini=$('#dispatch-mini');if(mini){const trips=sim.allTrips();mini.hidden=!started||!(trips.length||s.repRoutes.length);document.body.classList.toggle('traveling',trips.length>0);const signature=trips.map(t=>t.vehicleId+':'+t.legIndex).join(',')+'|'+s.repRoutes.map(r=>r.index+':'+r.stop+':'+r.phase).join(',');if(mini.dataset.route!==signature){mini.dataset.route=signature;mini.innerHTML='<span>الأسطول والمناديب ↗</span>'+expansion.fleetMap();}}}


function open(id){if(id==='diary')voices.play('diary');if(!started&&!['settings','reset','guide'].includes(id))return;world?.resetInput?.();panel=id;dialogFocus=document.activeElement;$('#panel-backdrop').hidden=false;renderPanel();$('#close-panel').focus();}
function close(){if(panel==='voice')voices.stop();panel=null;$('#panel-backdrop').hidden=true;dialogFocus?.focus?.();}
function renderPanel(preserve=false){const render=panels[panel];if(!render)return;const container=$('#panel-content'),values=preserve?[...container.querySelectorAll('input,select,textarea')].map(el=>({id:el.id,name:el.name,type:el.type,value:el.value,checked:el.checked})):[],scroll=container.scrollTop||0,focusId=preserve?document.activeElement?.id:null;const view=render();$('#panel-kicker').textContent=view[0];$('#panel-title').textContent=view[1];container.innerHTML=view[2];$('#panel').classList.toggle('map-panel',panel==='map'||panel==='fleet');$('#panel').classList.toggle('guide-panel',panel==='guide');for(const v of values){const el=v.id?document.getElementById(v.id):[...container.querySelectorAll('input')].find(e=>e.name===v.name&&e.value===v.value);if(el){if(v.type==='radio'||v.type==='checkbox')el.checked=v.checked;else el.value=v.value;}}if(preserve){container.scrollTop=scroll;if(focusId)document.getElementById(focusId)?.focus({preventScroll:true});}panelDirty=false;}

const row=(a,b)=>'<div class="row"><span>'+a+'</span><b>'+b+'</b></div>';
const btn=(label,action,extra='',disabled=false,kind='primary')=>'<button class="'+kind+'" data-action="'+action+'" '+extra+' '+(disabled?'disabled':'')+'>'+label+'</button>';
const go=(id,label)=>'<button class="secondary" data-go="'+id+'">'+label+' ←</button>';
const empty=text=>'<div class="empty">'+text+'</div>';
const note=text=>'<p class="note">'+text+'</p>';
const oid=o=>'data-id="'+o.id+'"';
function chapterTasks(){return '<div class="tasks">'+MISSIONS.map((m,i)=>'<div class="row '+(i<sim.s.mission?'done':'')+'"><span>'+num(i+1)+'. '+m.title+'</span><b>'+(i<sim.s.mission?'✓':i===sim.s.mission?'دلوقتي':'')+'</b></div>').join('')+'</div>'}
const panels={
 desk(){let s=sim.s;if(!s.signed)return ['استلام المسؤولية','عقد وكالة سعيد','<div class="paper"><h3>وكالة سعيد للتجارة والتوزيع</h3><p>«اشتغلت هنا تلاتين سنة. بسيب لك المكان، واسم لازم تحافظ عليه.» — عم سعيد</p>'+row('المقر والمخزن','موروثان')+row('العربية','تحتاج صيانة')+row('رأس المال المتاح',egp(25000))+row('التزامات قديمة',egp(8000))+'<div class="contract-sign">توقيع استلام إدارة الوكالة</div></div><label for="player-name">اسمك على دفتر الوكالة</label><input id="player-name" maxlength="30" value="'+esc(s.name)+'"><div class="actions">'+btn('وقّع واستلم المفاتيح','sign')+'</div>'+note('دي محاكاة داخل اللعبة. المكتب والمخزن ملك الوكالة بالفعل، وأول شغلك الجرد وإصلاح العربية.')];
 return ['مكتب المدير · '+esc(s.name),'إدارة وكالة سعيد','<p>من هنا تتعاقد مع المصانع، تطوّر المقر، وتراجع تمويل الشغل.</p><div class="split"><div class="card"><small>صافي الربح التشغيلي</small><div class="big-number">'+num(sim.profit)+'</div><small>جنيه</small></div><div class="card"><small>طلبيات محصّلة</small><div class="big-number">'+num(s.delivered)+'</div><small>'+num(s.served.length)+' عملاء مختلفين</small></div></div>'+Object.entries(C).map(([id,c])=>'<div class="card"><h3>'+c.name+'</h3><p>خصم شراء '+num(c.discount*100)+'٪ · تارجت أسبوعي '+egp(c.target)+' · حافز ٢٪ عند تحقيقه</p>'+row('مشتريات الأسبوع',egp(s.purchases[id]))+(id==='dairy'?'<p>يشترط تبريد للمخزن، والتطوير يشمل تجهيز نقل الألبان.</p>':'')+(s.contracts[id]?'<span class="tag">توكيل موقّع وساري ✓</span>':'<div class="actions">'+btn('عرض العقد · '+egp(c.fee),'contractPreview','data-cid="'+id+'"',s.delivered<3)+'</div>')+'</div>').join('')+'<div class="card"><h3>تطوير المقر</h3><p>التجديد يغيّر أثاث المكتب وشكله. كل مستوى يزيد مصروف التشغيل اليومي ٢٥ ج.م.</p>'+row('المستوى',num(s.officeLevel)+' / ٢')+btn('تجديد المكتب · ٦٬٠٠٠ ج.م','upgrade','data-type="office"',s.officeLevel>=2)+'</div><div class="card"><h3>التمويل والالتزامات</h3>'+row('المتبقي',egp(s.debt))+'<div class="actions">'+btn('سداد ٢٬٠٠٠','repay','',!s.debt,'secondary')+btn('تمويل ١٠٬٠٠٠','loan','',s.debt>8000,'secondary')+'</div><p class="muted">الالتزامات الموروثة منفصلة عن القرض البنكي الجديد بفائدة. يُسدّد حتى ١٬٠٠٠ أسبوعيًا حسب السيولة.</p></div><div class="actions">'+btn('دفتر الحكاية','journal','','','secondary')+btn('إنهاء يوم العمل','endDayConfirm','','','secondary')+'</div>'];},
 journal(){return ['أهداف الوكالة','حكايتك لحد دلوقتي',chapterTasks()]},
 shelf(){let s=sim.s;if(!s.inventoried)return ['مخزن عم سعيد','الجرد الافتتاحي','<p>الرفوف فاضية، لكن المكان صالح للشغل. سجّل الأصول والالتزامات قبل أول شراء.</p>'+row('سعة المخزن','١٦٠ كرتونة')+row('بضاعة موجودة','٠ كرتونة')+row('عربية توزيع','١ — عطلانة')+row('ديون قديمة',egp(8000))+'<div class="actions">'+btn('اعتماد الجرد الافتتاحي','inventory')+'</div>'];
 const orders=s.orders.filter(o=>o.accepted);return ['مخزن الوكالة','الرفوف وتجهيز الطلبات',row('إشغال المخزن',num(sim.stockTotal)+' / '+num(s.capacity)+' كرتونة')+row('شحنات في الطريق',num(sim.pendingStock)+' كرتونة')+(s.carry?note('شايل '+num(s.carry.qty)+' كرتونة. اتجه للعربية للتحميل.')+'<div class="actions">'+go('truck','اتجه للعربية')+btn('رجّع البضاعة للرف','returnCarry','','','secondary')+'</div>':'')+'<h4>طلبيات مؤكدة للتجهيز</h4>'+(!orders.length?empty('افتح التليفون وأكّد طلبية الأول.'):orders.map(o=>{let loaded=s.cargo.filter(b=>b.order===o.id).reduce((a,b)=>a+b.qty,0);return '<div class="card"><h3>'+s.clients[o.client].name+'</h3><p>'+P[o.pid].name+' · '+num(o.qty)+' كرتونة</p>'+row('متاح على الرف',num(sim.qty(o.pid)))+row('في العربية',num(loaded)+' / '+num(o.qty))+'<div class="actions">'+btn(s.staff.worker?'جهّز الطلب بالعامل':'شيل ١٠ كراتين','pack',oid(o),!!s.carry||loaded>=o.qty||!!s.trip)+go('supplier','شراء الناقص')+'</div></div>'}).join(''))+'<h4>المخزون والصلاحية</h4>'+Object.entries(P).filter(([id])=>sim.qty(id)>0).map(([id,p])=>'<div class="row"><span>'+p.name+'</span><b>'+num(sim.qty(id))+' كرتونة</b><small>حتى يوم '+num(Math.min(...s.stock.filter(b=>b.pid===id).map(b=>b.expires)))+'</small></div>').join('')+'<div class="actions">'+btn('توسعة +١٦٠ · ٤٬٠٠٠ ج.م','upgrade','data-type="warehouse"',s.capacity>=480,'secondary')+'</div>'+note('الكراتين بتقل من الرف وقت التجهيز، وتظهر في إيدك ثم في العربية. ترتيب الصرف: الأقرب انتهاءً أولًا.')];},
 supplier(){let s=sim.s;return ['دفتر المشتريات','اطلب بضاعة على قد شغلك','<p>الأسعار للكرتونة. التسليم خلال ٨ ثواني لعب، وبعدها لازم تستلم الشحنة من البالته.</p>'+row('مساحة متاحة',num(s.capacity-sim.stockTotal-sim.pendingStock-sim.reservedStorage)+' كرتونة')+Object.entries(P).filter(([id])=>sim.enabled(id)).map(([id,p])=>'<div class="card"><h3>'+p.name+'</h3><div class="meta"><span>'+C[p.company].name+'</span><span>صلاحية '+num(p.life)+' أيام</span></div>'+row('شراء / بيع إرشادي',egp(sim.cost(id))+' / '+egp(p.sell))+'<div class="formrow"><label for="qty-'+id+'">الكمية</label><input id="qty-'+id+'" type="number" min="1" max="500" step="1" value="10">'+btn('طلب الشحنة','buy','data-pid="'+id+'"')+'</div></div>').join('')+note('توكيلات الأغذية الجديدة تفتح باقي الأصناف. التارجت بيتحسب على البضاعة المستلمة، مش بمجرد ختم الفاتورة.')];},
 receiving(){let s=sim.s;return ['رصيف الاستلام','راجع الكمية واستلم الشحنة',s.incoming.length?s.incoming.map(b=>'<div class="card"><h3>'+P[b.pid].name+'</h3>'+row('أمر الشراء',num(b.qty)+' كرتونة')+row('السعر المتفق عليه',egp(b.unit))+row('إجمالي المدفوع',egp(b.total))+'<p>'+(b.ready?'الشحنة وصلت. الكراتين موجودة على البالته.':'المورد في الطريق. باقي '+num(Math.max(0,b.eta-s.elapsed))+' ثواني لعب. الوقت مستمر أثناء المراجعة.')+'</p>'+btn('عدّ واستلم البضاعة','receive','data-id="'+b.id+'"',!b.ready)+'</div>').join(''):empty('مفيش شحنات مستنية. اطلب بضاعة من دفتر المشتريات.')+go('supplier','دفتر المشتريات')];},
 truck(){let s=sim.s;if(!s.repaired)return ['ساحة التحميل','عربية عم سعيد','<p>الموتور محتاج صيانة والبطارية محتاجة تغيير. دي أول عربية للوكالة؛ تصليحها أرخص من شراء بديل.</p>'+row('الإصلاح الأول',egp(3000))+row('الحمولة','٦٠ كرتونة')+'<div class="actions">'+btn('غيّر البطارية وصلّح الموتور','repair','',!s.inventoried)+'</div>'];if(s.trip)return ['خط التوزيع','العربية على الطريق','<div class="card"><h3>'+s.trip.orders.map(o=>s.clients[o.client].name).join(' ← ')+'</h3><div class="progress"><i style="width:'+(1-s.trip.remaining/s.trip.total)*100+'%"></i></div><p>باقي '+num(s.trip.remaining)+' ثانية لعب للرجوع.</p></div>'+note('الوقت مستمر أثناء المتابعة. فلوس البيع هتظهر كمستحقات عند التسليم؛ التحصيل من الحسابات.')];
 let qty=s.cargo.reduce((a,b)=>a+b.qty,0);return ['ساحة التحميل','تحميل وخطوط التوزيع',row('حالة العربية',num(s.truckCondition)+'٪')+row('الحمولة الحالية',num(qty)+' / '+num(s.truckCount*60)+' كرتونة')+(s.carry?'<div class="card"><h3>الكراتين اللي معاك</h3><p>'+num(s.carry.qty)+' كرتونة '+P[s.carry.pid].name+'</p>'+btn('حمّل الكراتين في العربية','load')+'</div>':'')+s.cargo.map(b=>'<div class="row"><span>'+P[b.pid].name+'</span><b>'+num(b.qty)+' كرتونة</b></div>').join('')+'<div class="card"><h3>اختار خط الرحلة</h3><label><input type="radio" name="route" value="safe" checked> الطريق المعتاد — وقود أقل وصيانة أقل</label><label><input type="radio" name="route" value="fast"> طريق سريع — أسرع ٣٥٪، زيادة ٦٠ ج.م وتآكل أكبر</label><p class="muted">وقود دمياط ٧٠ ج.م، الدقهلية ١٨٠ ج.م، و٢٠ ج.م لكل توقف إضافي. تقدر تجمع أكتر من طلب في نفس الرحلة.</p>'+btn('ابدأ رحلة التوزيع','dispatch','',!qty)+'</div><div class="actions">'+go('shelf','ارجع للمخزن')+btn('تفريغ الحمولة','unload','',!qty,'secondary')+'</div><div class="card"><h3>صيانة وتوسعة الأسطول</h3><div class="actions">'+btn('صيانة · '+egp(Math.ceil((100-s.truckCondition)*15)),'repair','',s.truckCondition>=95,'secondary')+btn('عربية إضافية · ١٢٬٠٠٠','upgrade','data-type="truck"',s.truckCount>=3,'secondary')+'</div><p class="muted">العربيات الإضافية بتزود حمولة خط التوزيع الجماعي؛ حد الأسطول ٣ عربيات.</p></div>'];},
 phone(){let s=sim.s;if(s.event)return ['تليفون الوكالة','قرار محتاجك',s.event.kind==='power'?'<p>الكهرباء قطعت. وفر طاقة احتياطية أو تابع انقطاع ٣ دقائق وراقب الحرارة؛ التحذير يسبق التلف.</p><div class="actions">'+btn(s.ops.generator?'تشغيل المولد الاحتياطي':'استئجار مولد · ٣٠٠ ج.م','event','data-choice="pay"')+btn('راقب الانقطاع والحرارة','event','data-choice="skip"',false,'secondary')+'</div>':'<p>موزع جديد بينافسك على عملاء المنطقة. تقدر تستثمر ٤٥٠ ج.م في خدمة العملاء فتزيد السمعة ٥ نقاط والثقة نقطتين، أو تكمّل عادي وتخسر ٣ نقاط سمعة.</p><div class="actions">'+btn('استثمر في الخدمة','event','data-choice="pay"')+btn('كمّل بالموجود','event','data-choice="skip"',false,'secondary')+'</div>'];
 return ['مبيعات وكالة سعيد','التليفون وطلبات العملاء',(!s.orders.length?empty(s.repaired?'مفيش طلبات دلوقتي. كمّل شغلك؛ طلبات السوق بتوصل كل ١٠ ثوانٍ.':'صلّح العربية الأول عشان نقدر نوعد العملاء بالتوصيل.'):s.orders.map(o=>{let c=s.clients[o.client];return '<div class="card"><h3>'+c.name+' '+(o.accepted?'<span class="tag">مؤكد</span>':'')+'</h3><div class="meta"><span>'+c.area+'</span><span>ثقة '+num(c.trust)+'٪</span><span>'+P[o.pid].name+'</span></div>'+row('الكمية',num(o.qty)+' كرتونة')+row('إجمالي قبل الخصم',egp(o.qty*o.price))+row('متاح بالمخزن',num(sim.qty(o.pid)))+(o.accepted?'<div class="actions">'+go('shelf','جهّز الطلب')+'</div>':'<div class="formrow"><label for="discount-'+o.id+'">الخصم</label><select id="discount-'+o.id+'"><option value="0">بدون خصم</option><option value="5">٥٪</option><option value="10">١٠٪</option></select><select id="payment-'+o.id+'" aria-label="طريقة السداد"><option value="cash">نقدي</option><option value="credit">آجل ٣ أيام</option></select></div><div class="actions">'+btn('أكد الطلب','accept',oid(o))+btn('اعتذار','reject',oid(o),false,'secondary')+'</div>')+'</div>'}).join(''))+'<h4>علاقات العملاء</h4>'+s.clients.filter(c=>s.regions.includes(c.area)).map(c=>'<div class="row"><span>'+c.name+'<br><small class="muted">حد آجل '+egp(c.credit)+' · مستحق '+egp(c.outstanding)+'</small></span><b>'+num(c.trust)+'٪</b></div>').join('')+note('الطلبات بتعكس السوق حتى لو الصنف مش عندك. جهّز طلبك في ٥ دقائق لعب عشان تحافظ على الثقة. الوقت مستمر أثناء المراجعة؛ استخدم زر الإيقاف المؤقت عند الحاجة.')];},
 accounts(){let s=sim.s,v=s.invoices.filter(v=>!v.settled);return ['الأستاذ فاروق · الحسابات','مراجعة وتحصيل','<div class="split"><div class="card"><small>إيرادات مُحققة</small><div class="big-number">'+num(s.revenue)+'</div></div><div class="card"><small>مستحقات عملاء</small><div class="big-number">'+num(s.clients.reduce((a,c)=>a+c.outstanding,0))+'</div></div></div>'+row('تكلفة البضاعة المباعة',egp(s.cogs))+row('مصاريف التشغيل والتالف',egp(s.expenses))+row('صافي الربح التشغيلي',egp(sim.profit))+'<h4>فواتير بانتظار المراجعة</h4>'+(!v.length?empty('الدفتر متراجع. مفيش فواتير مستنية.'):v.map(v=>'<div class="paper"><h3>'+(v.type==='sale'?'فاتورة بيع — '+s.clients[v.client].name:'فاتورة شراء — '+P[v.pid].name)+'</h3><p>رقم '+num(v.id)+' · يوم '+num(v.day)+' · '+num(v.qty)+' كرتونة</p>'+row('المستند المرجعي',egp(v.expected))+row('المبلغ في الفاتورة',egp(v.amount))+(v.type==='sale'?row('الاستحقاق','يوم '+num(v.due)):row('الدفع','مدفوع عند الطلب'))+(v.corrected?'<span class="stamp">تم التصحيح</span>':'')+'<div class="actions">'+btn(v.type==='purchase'?'اعتماد المراجعة':s.day<v.due?'اعتماد الآجل':'اعتماد وتحصيل','approve','data-id="'+v.id+'"')+btn('تصحيح الفرق','correct','data-id="'+v.id+'"',v.amount===v.expected,'secondary')+'</div></div>').join(''))+(s.lastStatement?'<div class="card"><h3>آخر إقفال أسبوعي — يوم '+num(s.lastStatement.day)+'</h3>'+row('رواتب',egp(s.lastStatement.salary))+row('سداد التزامات',egp(s.lastStatement.debtPay))+row('حافز تارجت',egp(s.lastStatement.rebates))+'</div>':'')+'<h4>حركة الخزنة</h4>'+s.ledger.slice(0,18).map(v=>row('<small>يوم '+num(v.day)+'</small> '+esc(v.text),v.amount?egp(v.amount):'—')).join('')+note('الأصول والتجهيزات لا تُحسب مصروف تشغيل في هذا النموذج المبسط. الربح منفصل عن الخزنة، والآجل لا يتحصل قبل موعده.')];},
 staff(){let s=sim.s;return ['إدارة الفريق','كبر شغلك بالناس الصح',Object.entries({driver:['١٬٥٠٠','١٬٦٠٠','يقود خطوط التوزيع ويفتح التوسع للدقهلية.'],worker:['١٬٢٠٠','١٬٢٠٠','يجهز الطلب كاملًا بدل حمل ١٠ كراتين، ويستلم الوارد مع التفويض.'],rep:['٢٬٠٠٠','١٬٥٠٠','مع فريق كامل وتفعيل التفويض ينفذ الطلبات المتاحة في المخزون تلقائيًا.'],accountant:['١٬٨٠٠','١٬٤٠٠','مع التفويض يراجع الفواتير المطابقة ويحصّل المستحق منها؛ الأخطاء تفضل لك.']}).map(([role,info])=>'<div class="card"><h3>'+staffNames[role]+'</h3><p>'+info[2]+'</p>'+row('راتب أسبوعي',info[1]+' ج.م')+(s.staff[role]?'<span class="tag">ضمن الفريق ✓</span>':btn('تعيين · '+info[0]+' ج.م','hire','data-role="'+role+'"',s.delivered<1))+'</div>').join('')+'<div class="card"><h3>تفويض العمليات المعتادة</h3><p>شراء البضاعة والتعاقد وتصحيح الفواتير تفضل تحت إشرافك. الرواتب كل ٧ أيام.</p>'+btn(s.auto?'إيقاف التفويض':'تفعيل التفويض','auto','','','secondary')+'</div>'];},
 map(){let s=sim.s;return ['خريطة الدلتا','خطوط وكالة سعيد','<div class="card"><h3>دمياط</h3><div class="route-line"><span>الوكالة</span><i></i><span>عملاء دمياط</span></div><p>متاحة من البداية · رحلة أساسية ١٠ ثوانٍ · وقود ٧٠ ج.م</p><span class="tag">خط شغّال</span></div><div class="card"><h3>الدقهلية</h3><div class="route-line"><span>دمياط</span><i></i><span>المنصورة</span><i></i><span>عملاء الدقهلية</span></div><p>سعر بيع أعلى ١٢٪ · وقت ووقود أكتر · تحتاج سائق وتوكيل.</p>'+(s.regions.includes('الدقهلية')?'<span class="tag">الخط مفتوح ✓</span>':btn('فتح الخط · ٥٬٠٠٠ ج.م','unlock'))+'</div>'+go('phone','راجع طلبات المناطق')];},
 cooling(){let s=sim.s;return ['تجهيزات المخزن','غرفة التبريد','<p>تجهيز تبريد للمخزن ونقل منتجات الألبان. يحافظ على البضاعة حتى تاريخ صلاحيتها ويفتح شروط توكيل مزارع نور.</p>'+row('مصاريف إضافية يومية',egp(80))+(s.cooling?'<span class="tag">التبريد شغّال ✓</span>':btn('تركيب التبريد · ٦٬٠٠٠ ج.م','upgrade','data-type="cooling"'))+note('التبريد لا يلغي الصلاحية. تابع مخزونك، ولو الكهرباء قطعت هيجيلك قرار لتشغيل مولد.')];},
 settings(){let s=sim.s;return ['وكالة سعيد · النسخة ٥.٠','اللعب والحفظ','<div class="card"><h3>التحكم</h3><p>WASD أو الأسهم للحركة. E للتفاعل مع أقرب عنصر. الضغط على اسم عنصر يمشيك له ويفتحه عند الوصول. الضغط على الأرض للمشي. اسحب المشهد لتدوير الكاميرا، وعجلة الماوس للتقريب.</p></div><div class="actions">'+btn(s.settings.sound?'إيقاف الصوت':'تشغيل الصوت','sound','','','secondary')+btn(s.settings.quality==='high'?'جودة خفيفة':'جودة عالية','quality','','','secondary')+'</div><div class="card"><h3>الحفظ</h3><p>حفظ تلقائي على نفس المتصفح. صدّر نسخة قبل نقل الملفات أو تغيير الجهاز. الحفظ القديم يُنقل للخانة الأولى لو موجود على نفس عنوان التشغيل. لو كنت بتفتح الإصدار القديم كملف، صدّر الحفظ منه واستورده هنا.</p><div class="actions">'+btn('تصدير الحفظ','export')+btn('استيراد الحفظ','importView','','','secondary')+'</div></div><div class="actions">'+btn('بداية جديدة','resetConfirm','','','danger')+'</div><p class="muted">اللعبة تعمل محليًا بلا إنترنت. الرسوم مجسمات WebGL فعلية؛ لا توجد صور خلفية للمكتب أو المخزن.</p>'];},
 import(){return ['نسخة احتياطية','استيراد الحفظ','<p>الصق محتوى ملف الحفظ بصيغة JSON من النسخة ٣ أو ٤. الاستيراد يستبدل تقدمك الحالي بعد التحقق من الملف.</p><textarea id="import-data" aria-label="محتوى الحفظ"></textarea><div class="actions">'+btn('تحقق واسترجع','import')+'</div>'];},
 reset(){return ['بداية جديدة','تبدأ من أول وجديد؟',note('الحفظ الحالي هيتستبدل. تقدر تصدّره الأول وتحتفظ بيه.')+'<div class="actions">'+btn('صدّر الحفظ الحالي','export','','','secondary')+btn('ابدأ حكاية جديدة','reset','','','danger')+'</div>'];},
 endDay(){return ['إنهاء اليوم','تقفل الوكالة لليوم؟',note('هتتطبق مصاريف يوم جديد والصلاحية. لازم تخلص الرحلة الحالية وتفرّغ الحمولة وترجّع البضاعة اللي في إيدك الأول. الطلبات المفتوحة ممكن تتأخر.')+'<div class="actions">'+btn('إنهاء اليوم','endDay','',sim.hasWork())+'</div>'];}
};
v4=AgencyUI({getSim:()=>sim,base:{...panels},row,btn,go,note,empty,num,egp,esc});Object.assign(panels,v4.panels);
const network=new AgencyNetwork(()=>sim,slots,localStore);
const features=installFeatureUI({network,panels,getSim:()=>sim,btn,row,egp,esc,slots,open,toast,switchSlot(slot){save();const previous=slots.active;try{slots.select(slot);const raw=slots.load();const next=new Simulation(raw||undefined);sim=next;bind();saved=raw;world.lastVisual='';world.player.position.set(sim.s.position.x,0,sim.s.position.z);world.quality(sim.s.settings.quality);close();started=false;start(false);toast('فتحت خانة الحفظ '+slot);}catch(e){slots.select(previous);toast('الخانة غير صالحة؛ الحفظ الحالي لم يتغير.','bad')}}});
const expansion=ExpansionUI({panels,getSim:()=>sim,btn,row,egp,esc,go,open});
const guide=GuideUI({panels,getSim:()=>sim,btn,go,esc});
registerPWA({canReload:()=>!panel&&!network.busy&&!world?.isGestureActive?.(),beforeReload(){if(started){save();if(saveError)return false;try{sessionStorage.setItem('saeed_update_resume',String(slots.active))}catch{}}return true},onUpdate:message=>toast(message)});


const logistics=LogisticsUI({panels,getSim:()=>sim,btn,row,egp,esc,open});
const development=DevelopmentUI({panels,getSim:()=>sim,getWorld:()=>world,btn,row,egp,open});
const voices=VoiceUI({panels,btn,esc,open,toast});
const editor=EditorUI({panels,getSim:()=>sim,getWorld:()=>world,btn,open,toast});
const cloud=CloudUI({panels,network,getSim:()=>sim,slots,btn,esc,open,toast,replaceState(data){const next=new Simulation(Simulation.validate(data));slots.save(next.s);sim=next;bind();world.lastVisual='';world.player.position.set(sim.s.position.x,0,sim.s.position.z);world.quality(sim.s.settings.quality);refresh();}});
function interact(id){if(id==='development'){open('development');return;}if(id==='garage'){open('garage');return;}if(id.startsWith('vehicle:')){if(sim.chooseVehicle(Number(id.split(':')[1])))open('truck');return;}if(id.startsWith('customer:')){open('customers');return;}if(id.startsWith('batch:')){open('layout');return;}if(id==='dialogue'){voices.play('driver');sim.talk();open('staff');return;}if(id==='truck'&&sim.s.carry){sim.load();close();return;}if(id==='desk')sound('good');open(id)}
function start(fresh){if(fresh&&saved){open('reset');return;}if(fresh){sim=new Simulation();bind();}started=true;voices.play('welcome');world.active=true;$('#welcome').hidden=true;for(const id of ['hud','mission','location','camera-nav','controls','mobile-controls','inbox','map-dock','mobile-toolbar'])$('#'+id).hidden=false;world.player.position.set(sim.s.position.x,0,sim.s.position.z);world.setView('all');refresh();if(!sim.s.signed){world.goTo('desk');}else toast('رجعت تنوّر وكالة سعيد. كمّل من '+sim.mission.title);if(!sim.s.guideSeen){sim.s.guideSeen=true;open('guide')}save();}
$('#start').onclick=()=>start(true);$('#continue').hidden=!saved;$('#continue').onclick=()=>start(false);$('#settings').onclick=()=>open('settings');$('#close-panel').onclick=close;$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'▶':'Ⅱ';toast(paused?'الوقت متوقف. اضغط ▶ للاستمرار.':'رجعنا للشغل.');};$('#dispatch-mini').onclick=()=>open('fleet');$('#tablet-open').onclick=()=>open('tablet');$('#help').onclick=()=>open('guide');$('#welcome-guide').onclick=()=>open('guide');$('#rotate').onclick=()=>world.angle+=Math.PI/4;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>world.setView(b.dataset.view));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(panel)close();else if(started)$('#pause').click();}if(e.key==='Tab'&&panel){let focusable=[...$('#panel').querySelectorAll('button:not(:disabled),input,select,textarea')];let first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}});
document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g){close();world.goTo(g.dataset.go);return;}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=Number(b.dataset.id);let refreshPanel=true;if(network.busy&&['reset','import'].includes(a)){toast('استنى اكتمال عملية التبادل.');return;}if(development.handle(b)||logistics.handle(b)||voices.handle(b)||editor.handle(b)||cloud.handle(b)||expansion.handle(b)||guide.handle(b)||features.handle(b)){refresh();if(panel)renderPanel();save();return;}switch(a){
 case 'sign':if(sim.sign($('#player-name').value)){close();refreshPanel=false;}break;
 case 'inventory':if(sim.inventory()){close();refreshPanel=false;}break;
 case 'repair':if(sim.repair()){close();refreshPanel=false;}break;
 case 'buy':if(sim.buy(b.dataset.pid,Number($('#qty-'+b.dataset.pid).value))){close();refreshPanel=false;}break;
 case 'receive':sim.receive(id);break;
 case 'accept':if(sim.accept(id,Number($('#discount-'+id).value),$('#payment-'+id).value)){close();refreshPanel=false;}break;
 case 'reject':sim.reject(id);break;
 case 'pack':if(sim.pack(id)){world.spawnDust(world.player.position.x,1,world.player.position.z);close();world.goTo('truck');refreshPanel=false;}break;
 case 'load':if(sim.load()){world.spawnDust(1.3,1.3,7.3);close();refreshPanel=false;}break;
 case 'returnCarry':sim.returnCarry();break;
 case 'unload':sim.unload();break;
 case 'dispatch':if(sim.dispatch($('input[name=route]:checked').value)){world.spawnDust(1.3,.5,7.3);close();world.setView('yard');refreshPanel=false;}break;
 case 'approve':sim.approve(id);break;
 case 'correct':sim.correct(id);break;
 case 'contractPreview':v4.selectCompany(b.dataset.cid);open('company');break;
 case 'contract':sim.contract(b.dataset.cid);break;
 case 'upgrade':sim.upgrade(b.dataset.type,b.dataset.cid||'bakery');break;
 case 'warehouseSetup':sim.setupWarehouse(b.dataset.cid);break;
 case 'chooseVehicle':sim.chooseVehicle(Number(b.dataset.vehicle));break;
 case 'buyVehicle':sim.buyVehicle(b.dataset.kind);break;
 case 'convertVehicle':sim.convertVehicle(b.dataset.kind);break;
 case 'payCommissions':sim.payCommissions();break;
 case 'openMap':open('map');break;
 case 'hire':sim.hire(b.dataset.role);break;
 case 'unlock':sim.unlock();break;
 case 'loan':sim.loan();break;
 case 'repay':sim.repay(2000);break;
 case 'auto':sim.s.auto=!sim.s.auto;sim.change();break;
 case 'event':sim.resolveEvent(b.dataset.choice);break;
 case 'journal':open('journal');break;
 case 'endDayConfirm':open('endDay');break;
 case 'endDay':if(!sim.hasWork()){sim.s.elapsed+=(DAY_SECONDS-sim.s.time)*(sim.s.dayLength/DAY_SECONDS);sim.nextDay();close();refreshPanel=false;}break;
 case 'sound':sim.s.settings.sound=!sim.s.settings.sound;if(ambientGain)ambientGain.gain.value=sim.s.settings.sound?.014:0;sim.change();break;
 case 'quality':sim.s.settings.quality=sim.s.settings.quality==='high'?'low':'high';world.quality(sim.s.settings.quality);sim.change();break;
 case 'export':{const blob=new Blob([JSON.stringify(sim.s,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='Saeed-Agency-Save-Day-'+sim.s.day+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('تم تجهيز ملف الحفظ للتنزيل.');break;}
 case 'importView':open('import');break;
 case 'import':try{const data=Simulation.validate(JSON.parse($('#import-data').value));sim=new Simulation(data);bind();world.player.position.set(data.position.x,0,data.position.z);world.quality(data.settings.quality);refresh();save();close();toast('رجع حفظ وكالة سعيد بنجاح.');refreshPanel=false;}catch(e){toast('تعذر الاستيراد: '+e.message,'bad')}break;
 case 'resetConfirm':open('reset');break;
 case 'reset':sim=new Simulation();bind();saved=null;started=false;close();world.lastVisual='';world.player.position.set(-6,0,4);start(true);refreshPanel=false;break;
 }refresh();if(refreshPanel&&panel)renderPanel();save();});
installMobileUI(()=>world);
try{world=new AgencyWorld({interact,blocked:()=>!started||paused||!!panel,target:()=>sim.mission.target,footstep:()=>sound('step')});world.quality(sim.s.settings.quality);$('#loading').hidden=true;world.setView('all');world.angle=.48;refresh();let last=performance.now();function frame(now){let dt=Math.min((now-last)/1000,.1);last=now;if(started&&!paused&&!['settings','import','reset','endDay','guide','cloud','editor','voice'].includes(panel)&&!document.hidden){sim.tick(dt);saveTick+=dt;if(saveTick>1){saveTick=0;refresh();if(['garage','cold'].includes(panel))panelDirty=true;save();}}if(panelDirty&&panel&&!['settings','import','reset','endDay','guide','cloud','editor','voice'].includes(panel))renderPanel(true);mapTick+=dt;if(mapTick>.12){mapTick=0;v4.updateMap();expansion.update();}world.update(dt,sim.s);requestAnimationFrame(frame)}requestAnimationFrame(frame);}catch(e){$('#loading').innerHTML='<strong>تعذر تشغيل الرسوم</strong><span>افتح اللعبة بمتصفح Chrome أو Edge مع تفعيل تسريع الرسوم.</span><small>'+esc(e.message)+'</small>';console.error(e);}
try{const resume=sessionStorage.getItem('saeed_update_resume');sessionStorage.removeItem('saeed_update_resume');if(resume===String(slots.active)&&saved&&world)start(false)}catch{}
window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden){save();if(world)world.keys={};}});
})();
