import {COMPANIES as C,PRODUCTS as P,VEHICLES as V} from './economy.js';
import {brandImage,productImage,TRUCK_BRANDS} from './brands.js';
import {tripStatus} from './trip-status.js';
export const MENU_GROUPS=[
 ['overview','الإدارة',[['tablet','نظرة عامة'],['sitePlan','مخطط التوسعات'],['upgradePreview','معاينة التطوير'],['desk','التوكيلات'],['company','العقد'],['strategy','السوق والتمويل'],['development','التطوير'],['districts','الأحياء']]],
 ['stock','المخازن',[['supplier','المشتريات'],['receiving','الاستلام'],['shelf','المخزون والتجهيز'],['layout','تخطيط المخزن'],['cooling','التجهيزات الباردة'],['cold','الحرارة والطاقة']]],
 ['orders','المبيعات',[['phone','الطلبات'],['journeys','مراحل الطلب'],['supply','التوريد الدوري'],['tradeDesk','الربح والسيولة'],['customers','العملاء'],['specials','الطلبات الخاصة'],['relations','علاقات الشركات'],['territories','مناطق التوزيع']]],
 ['fleet','التوزيع',[['fleet','الأسطول'],['truck','تحميل العربية'],['loadPlan','خطة الحمولة'],['map','خريطة الرحلة'],['planner','تخطيط المسار'],['garage','الجراج'],['fleetStyle','هوية العربيات'],['roadDecisions','قرارات الطريق']]],
 ['money','الحسابات',[['accounts','الفواتير'],['daily','تقرير اليوم'],['custody','العهد والتسويات']]],
 ['team','الفريق والمزيد',[['staff','الموظفون'],['reps','خطوط المناديب'],['story','دفتر الحكاية'],['guide','الدليل'],['settings','الإعدادات'],['owner','أدوات المطوّر']]]
];
const paths={overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',stock:'M3 8l9-5 9 5v11l-9 3-9-3zM3 8l9 4 9-4M12 12v10',orders:'M5 4h14v17l-3-2-4 2-4-2-3 2zM8 8h8M8 12h8',fleet:'M2 6h12v12H2zM14 10h4l4 4v4h-8M7 18a2 2 0 1 1-4 0M21 18a2 2 0 1 1-4 0',money:'M3 5h18v14H3zM3 9h18M7 14h3M15 14h3',team:'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8M4 22v-3a8 6 0 0 1 16 0v3',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14M15 15l6 6'};
export const menuIcon=id=>'<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round">'+(paths[id]||paths.overview).split(/(?=M)/).filter(Boolean).map(p=>'<path d="'+p+'"/>').join('')+'</svg>';
export const normalizeSearch=v=>String(v).toLowerCase().replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/[\u064B-\u065F\u0640]/g,'').trim();
export function menuMatches(text,tags,query,filter){return normalizeSearch(text).includes(normalizeSearch(query))&&(!filter||filter==='all'||tags.split(' ').includes(filter))}
export function invoiceStatus(v,day){return v.settled?'settled':v.amount!==v.expected?'difference':v.type==='sale'&&v.due>day?'future':v.type==='sale'?'due':'review'}
export function installMenuUI({panels,getSim,btn,row,go,note,empty,num,egp,esc}){
 const g=()=>getSim(),s=()=>g().s,original={...panels},prefs=new Map();
 const pref=id=>{if(!prefs.has(id))prefs.set(id,{query:'',filter:'all'});return prefs.get(id)};
 const badge=(text,tone='neutral')=>'<span class="menu-badge '+tone+'">'+esc(text)+'</span>';
 const link=(label,id)=>btn(label,'panelNav','data-panel="'+id+'"',false,'secondary');
 const metrics=items=>'<div class="menu-metrics">'+items.map(([label,value,detail])=>'<div><small>'+label+'</small><strong>'+value+'</strong>'+(detail?'<span>'+detail+'</span>':'')+'</div>').join('')+'</div>';
 const toolbar=(id,options,placeholder)=>{const p=pref(id);return '<section class="menu-toolbar" data-menu-toolbar="'+id+'"><label class="menu-search">'+menuIcon('search')+'<input type="search" id="menu-search-'+id+'" data-menu-search="'+id+'" value="'+esc(p.query)+'" placeholder="'+placeholder+'" aria-label="'+placeholder+'" autocomplete="off"></label><div class="menu-filters" aria-label="تصفية القائمة">'+options.map(([key,title])=>'<button data-action="menuFilter" data-list="'+id+'" data-filter="'+key+'" aria-pressed="'+(p.filter===key)+'">'+title+'</button>').join('')+'</div><small data-menu-count="'+id+'" aria-live="polite"></small></section>'};
 const record=(id,text,tags,html)=>'<article class="menu-record" data-menu-list="'+id+'" data-search="'+esc(text)+'" data-tags="'+tags+'">'+html+'</article>';
 const noResults=id=>'<div class="menu-no-results" data-menu-empty="'+id+'" hidden><strong>مفيش نتائج بالمواصفات دي</strong><p>جرّب اسم تاني أو اعرض كل العناصر.</p>'+btn('مسح البحث والفلاتر','menuClear','data-list="'+id+'"',false,'secondary')+'</div>';
 const storage=cid=>({dry:'جاف',chilled:'مبرد +٤°',frozen:'مجمد −١٨°'})[C[cid].storage];
 const product=(pid,subtitle='')=>'<div class="menu-product">'+productImage(P[pid])+'<div><small>'+C[P[pid].company].short+'</small><h3>'+P[pid].name+'</h3><p>'+subtitle+'</p></div></div>';
 const progress=(value,max,label)=>'<div class="menu-progress" role="progressbar" aria-label="'+esc(label)+'" aria-valuemin="0" aria-valuemax="'+max+'" aria-valuenow="'+Math.min(max,Math.max(0,value))+'"><i style="width:'+Math.min(100,Math.max(0,value/Math.max(1,max)*100))+'%"></i></div>';
 const section=(title,html)=>'<section class="menu-section"><h3 class="menu-section-title">'+title+'</h3>'+html+'</section>';
 panels.desk=()=>{const d=s();if(!d.signed)return original.desk();return ['شراكات وكالة سعيد','التوكيلات والعقود',metrics([['توكيلات نشطة',num(Object.values(d.contracts).filter(Boolean).length),'من ٤ شركات'],['دورات ناجحة',num(d.successfulCycles),'سجل أداء الوكالة'],['السمعة',num(d.rep)+'٪','تفتح شراكات جديدة']])+toolbar('agencies',[['all','كل الشركات'],['active','عقود سارية'],['available','متاحة'],['locked','قيد التقدم']],'ابحث باسم الشركة أو النشاط')+'<div class="menu-grid">'+Object.entries(C).map(([id,c])=>{const active=d.contracts[id],eligible=g().eligibility(id).every(r=>r.met),cycle=d.cycles[id],status=active?'active':eligible?'available':'locked';return record('agencies',c.name+' '+TRUCK_BRANDS[id].line,status,'<div class="menu-card-top">'+brandImage(id)+badge(active?'عقد ساري':eligible?'متاح للتجهيز':'شروط ناقصة',active?'good':eligible?'info':'neutral')+'</div><h3>'+c.name+'</h3><p>'+TRUCK_BRANDS[id].line+' · '+storage(id)+'</p><div class="menu-contract-rate"><b>١٢٪ <small>خصم فوري</small></b><b>٢٪ <small>مؤجل مشروط</small></b></div>'+row('تارجت الدورة',egp(cycle?.target||c.target))+(active?progress(d.purchases[id],cycle.target,'المسحوبات المستلمة')+row('المحقق',egp(d.purchases[id]))+row('نهاية الدورة','يوم '+num(cycle.endDay)):'<p class="menu-requirement">'+(eligible?'ابدأ بتجهيز المخزن والعربية قبل توقيع العقد.':g().eligibility(id).filter(r=>!r.met).map(r=>esc(r.text)).join(' · '))+'</p>')+'<footer>'+btn(active?'إدارة العقد':'عرض الشروط والعقد','contractPreview','data-cid="'+id+'"')+'</footer>')}).join('')+'</div>'+noResults('agencies')+section('إدارة المقر','<div class="actions">'+btn('تجديد المقر · ٦٬٠٠٠ ج','upgrade','data-type="office"',d.officeLevel>=2,'secondary')+btn('سداد ٢٬٠٠٠ ج','repay','',!d.debt,'secondary')+link('التمويل والسوق','strategy')+link('خطة التقدم','journal')+btn('إقفال اليوم','endDayConfirm','','','secondary')+'</div>')]};
 panels.supplier=()=>{const d=s(),products=Object.entries(P).filter(([id])=>g().enabled(id));return ['شراء مباشر من الشركات','كتالوج البضاعة',metrics([['الخزنة',egp(d.money),'قبل سداد المشتريات'],['أصناف متاحة',num(products.length),'حسب التوكيلات الموقعة'],['في الطريق',num(g().pendingStock)+' كرتونة','بانتظار الوصول والاستلام']])+toolbar('catalog',[['all','كل التوكيلات'],...Object.entries(C).filter(([id])=>d.contracts[id]).map(([id,c])=>[id,c.short])],'ابحث عن صنف أو شركة')+'<div class="menu-grid">'+products.map(([id,p])=>record('catalog',p.name+' '+C[p.company].name,p.company,product(id,'صلاحية '+num(p.life)+' أيام · '+storage(p.company))+'<div class="menu-price"><small>شراء الكرتونة</small><strong>'+egp(g().cost(id))+'</strong><span>القائمة '+egp(g().listPrice(id))+' · خصم العقد ١٢٪</span></div>'+row('المتاح على الرف',num(g().qty(id))+' كرتونة')+row('مساحة الشركة المتبقية',num(Math.max(0,d.warehouses[p.company].capacity-g().companyUsage(p.company)))+' كرتونة')+'<div class="menu-buy"><label for="qty-'+id+'">عدد الكراتين</label><input id="qty-'+id+'" data-menu-quantity="'+id+'" data-unit="'+g().cost(id)+'" type="number" min="1" max="500" step="1" value="10"><span>الإجمالي <b data-menu-total="'+id+'">'+egp(g().cost(id)*10)+'</b></span>'+btn('طلب البضاعة','buy','data-pid="'+id+'"')+'</div>')).join('')+'</div>'+(!products.length?empty('وقّع أول توكيل لعرض أصناف الشركة.')+go('desk','التوكيلات'):'')+noResults('catalog')+note('المسحوبات تدخل تارجت الشركة عند الاستلام. الخصم المؤجل ٢٪ مشروط بتحقيق التارجت؛ لا يُخصم من قيمة الطلب الآن.')+link('متابعة الشحنات الواردة','receiving')]};
 panels.receiving=()=>{const d=s();return ['رصيف الوارد','استلام البضاعة',metrics([['شحنات واردة',num(d.incoming.length)],['جاهزة للاستلام',num(d.incoming.filter(b=>b.ready).length)],['كراتين متوقعة',num(g().pendingStock)]])+toolbar('receipts',[['all','الكل'],['ready','وصلت'],['travel','في الطريق']],'ابحث عن صنف أو رقم شحنة')+'<div class="menu-grid">'+d.incoming.map(b=>record('receipts',b.id+' '+P[b.pid].name+' '+C[P[b.pid].company].name,b.ready?'ready':'travel','<div class="menu-card-top"><small>شحنة #'+num(b.id)+'</small>'+badge(b.ready?'جاهزة للاستلام':'في الطريق',b.ready?'good':'info')+'</div>'+product(b.pid,num(b.qty)+' كرتونة')+row('سعر الوحدة',egp(b.unit))+row(b.onCredit?'قيمة الشراء الآجل':'المدفوع عند الطلب',egp(b.total))+'<p>'+(b.ready?'راجع الكمية ثم سجّل استلامها.':'الوصول بعد '+num(Math.max(0,b.eta-d.elapsed))+' ثانية لعب.')+'</p><footer>'+btn('عدّ واستلم الشحنة','receive','data-id="'+b.id+'"',!b.ready||!!d.workerJob)+'</footer>')).join('')+'</div>'+noResults('receipts')+(!d.incoming.length?empty('كل الشحنات اتسلمت. تقدر تطلب بضاعة جديدة.'):'')+link('كتالوج المشتريات','supplier')]};
 panels.phone=()=>{const d=s();if(d.event)return original.phone();return ['مركز المبيعات','طلبات العملاء',metrics([['طلبات جديدة',num(d.orders.filter(o=>!o.accepted).length)],['طلبات مؤكدة',num(d.orders.filter(o=>o.accepted).length)],['على الطريق',num(g().allTrips().reduce((n,t)=>n+t.orders.filter(o=>!t.deliveredOrders.includes(o.id)).length,0))]])+toolbar('orders',[['all','الكل'],['new','جديدة'],['accepted','مؤكدة'],['short','نقص في المخزون']],'ابحث باسم العميل أو الصنف أو رقم الطلب')+'<div class="menu-grid">'+d.orders.map(o=>{const c=d.clients[o.client],t=g().terms(o.client),loaded=[...d.cargo,...g().otherLoads(),...(d.carry?[d.carry]:[]),...(d.pickingJob?[d.pickingJob.batch]:[])].filter(b=>b.order===o.id).reduce((n,b)=>n+b.qty,0),missing=Math.max(0,o.qty-loaded-g().qty(o.pid)),seconds=Math.max(0,(o.accepted?o.deadline:o.expires)-d.elapsed);return record('orders',o.id+' '+c.name+' '+P[o.pid].name+' '+c.area,(o.accepted?'accepted':'new')+(missing?' short':''),'<div class="menu-card-top"><small>طلب #'+num(o.id)+(o.bundle?' · مجمع #'+num(o.bundle):'')+'</small>'+badge(o.accepted?'مؤكد':'طلب جديد',o.accepted?'good':'info')+'</div><h3>'+esc(c.name)+'</h3><p>'+c.area+' · ثقة '+num(c.trust)+'٪</p>'+product(o.pid,num(o.qty)+' كرتونة')+row('القيمة '+(o.accepted?'بعد الخصم':'قبل الخصم'),egp(o.qty*o.price*(1-(o.accepted?o.discount:0)/100)))+row(o.accepted?'المهلة المتبقية':'متاح للرد',num(seconds)+' ث')+'<div class="menu-stock-note '+(missing?'warn':'good')+'">'+(missing?'ناقص '+num(missing)+' كرتونة للتجهيز':'المخزون والحمولة يغطيان الطلب')+'</div>'+(o.accepted?'<div class="actions">'+go('shelf','تجهيز الطلب')+(missing?link('شراء الناقص','supplier'):'')+'</div>':'<div class="menu-form-pair"><label for="discount-'+o.id+'">خصم البيع<select id="discount-'+o.id+'"><option value="0">بدون خصم</option><option value="5">٥٪</option><option value="10">١٠٪</option></select></label><label for="payment-'+o.id+'">السداد<select id="payment-'+o.id+'">'+(t.payment!=='credit'?'<option value="cash">نقدي</option>':'')+(t.payment!=='cash'?'<option value="credit">آجل '+num(t.days)+' أيام</option>':'')+'</select></label></div><footer class="actions">'+btn('تأكيد الطلب','accept','data-id="'+o.id+'"')+btn('اعتذار','reject','data-id="'+o.id+'"',false,'secondary')+'</footer>'))}).join('')+'</div>'+noResults('orders')+(!d.orders.length?empty('مفيش طلبات دلوقتي. طلبات السوق بتوصل كل ١٠ ثوانٍ بعد التعاقد.'):'')+link('ملفات العملاء والتحصيل','customers')]};
 panels.accounts=()=>{const d=s(),labels={settled:'مقفلة',difference:'فرق يحتاج مراجعة',future:'آجلة',due:'مستحقة للتحصيل',review:'بانتظار الاعتماد'};return ['المراجعة والتحصيل','الفواتير والحسابات',metrics([['مستحق لدى العملاء',egp(d.clients.reduce((n,c)=>n+c.outstanding,0))],['صافي الربح',egp(g().profit),'غير رصيد الخزنة'],['فواتير مفتوحة',num(d.invoices.filter(v=>!v.settled).length)]])+toolbar('invoices',[['all','الكل'],['open','مفتوحة'],['due','مستحقة'],['future','آجلة'],['difference','فروق'],['settled','مقفلة']],'ابحث برقم الفاتورة أو العميل أو الصنف')+'<div class="menu-invoices">'+[...d.invoices].sort((a,b)=>b.id-a.id).map(v=>{const status=invoiceStatus(v,d.day),cid=P[v.pid].company;return record('invoices',v.id+' '+(v.type==='sale'?d.clients[v.client].name:C[cid].name)+' '+P[v.pid].name,status+(v.settled?'':' open'),'<div class="menu-invoice-head"><div>'+brandImage(cid)+'<div><small>'+(v.type==='sale'?'فاتورة بيع':'فاتورة شراء')+' · #'+num(v.id)+'</small><h3>'+esc(v.type==='sale'?d.clients[v.client].name:C[cid].name)+'</h3><span>يوم '+num(v.day)+'</span></div></div>'+badge(labels[status],status==='difference'?'danger':status==='settled'?'good':status==='due'?'warn':'info')+'</div><div class="menu-invoice-line"><span>'+P[v.pid].name+'</span><b>'+num(v.qty)+' كرتونة</b><strong>'+egp(v.amount)+'</strong></div><div class="menu-invoice-values">'+row('المرجع الصحيح',egp(v.expected))+row('فرق المستند',egp(v.amount-v.expected))+(v.type==='sale'?row('الاستحقاق','يوم '+num(v.due))+row('المتبقي للتحصيل',egp(v.settled?0:Math.max(0,v.amount-(v.paid||0)))):row('طريقة السداد',v.onCredit?'آجل — دفتر علاقات الشركات':'مدفوع عند الطلب'))+'</div>'+(v.settled?'<p class="menu-settled">✓ تمت المراجعة والإقفال</p>':'<footer class="actions">'+btn(status==='difference'?'صحّح الفرق أولًا':v.type==='purchase'?'اعتماد المراجعة':d.day<v.due?'اعتماد الآجل':'تحصيل المتبقي','approve','data-id="'+v.id+'"',status==='difference'||v.approved&&d.day<v.due)+btn('تصحيح الفرق','correct','data-id="'+v.id+'"',v.amount===v.expected,'secondary')+'</footer>'))}).join('')+'</div>'+noResults('invoices')+(!d.invoices.length?empty('الفواتير هتظهر بعد شراء واستلام البضاعة أو تسليم الطلبات.'):'')+'<details class="menu-details"><summary>نتائج التشغيل وحركة الخزنة</summary>'+row('الإيراد',egp(d.revenue))+row('تكلفة المبيعات',egp(d.cogs))+row('المصاريف والتالف',egp(d.expenses))+d.ledger.slice(0,30).map(v=>row('يوم '+num(v.day)+' · '+esc(v.text),egp(v.amount))).join('')+'</details><details class="menu-details"><summary>دورات التوكيلات والإقفال الأسبوعي</summary>'+d.cycleHistory.slice(0,12).map(c=>'<div class="card"><h3>'+C[c.cid].short+' · يوم '+num(c.endDay)+'</h3>'+row('المسحوبات / التارجت',egp(c.gross)+' / '+egp(c.target))+row('الخصم المؤجل',egp(c.rebate))+'</div>').join('')+(d.lastStatement?row('آخر رواتب',egp(d.lastStatement.salary))+row('سداد التزامات',egp(d.lastStatement.debtPay)):'<p>لم يحدث إقفال أسبوعي بعد.</p>')+'</details>']};
 // Keep physical loading and all established warehouse operations, adding an inventory catalogue.
 panels.shelf=()=>{const d=s();if(!d.inventoried)return original.shelf();const old=original.shelf();return [old[0],'المخزن وتجهيز الطلبات',metrics([['على الرفوف',num(g().stockTotal)+' كرتونة'],['وارد متوقع',num(g().pendingStock)+' كرتونة'],['السعة الإجمالية',num(d.capacity)+' كرتونة']])+toolbar('stock',[['all','كل الأصناف'],['available','متاح'],['low','مخزون قليل'],['expiry','قريب الانتهاء']],'ابحث عن صنف أو توكيل')+'<div class="menu-grid">'+Object.entries(P).filter(([pid,p])=>d.warehouses[p.company].owned).map(([pid,p])=>{const qty=g().qty(pid),batches=d.stock.filter(b=>b.pid===pid),expiry=batches.length?Math.min(...batches.map(b=>b.expires)):null;return record('stock',p.name+' '+C[p.company].name,(qty?'available':'empty')+(qty<20?' low':'')+(expiry!==null&&expiry-d.day<=1?' expiry':''),product(pid,storage(p.company))+row('رصيد الصنف',num(qty)+' كرتونة')+row('أقرب انتهاء',expiry===null?'لا توجد دفعات':'يوم '+num(expiry))+row('الدفعات',num(batches.length))+'<div class="actions">'+link('شراء','supplier')+link('الطلبات','phone')+'</div>')}).join('')+'</div>'+noResults('stock')+'<details class="menu-details" open><summary>تجهيز الطلبات وإدارة مساحات المخازن</summary>'+old[2]+'</details>']};
 return {pref,metrics,badge,link,progress,record,toolbar,noResults,section,
 handle(b){const a=b.dataset.action;if(!['menuFilter','menuClear'].includes(a))return false;const p=pref(b.dataset.list);if(a==='menuClear'){p.query='';p.filter='all'}else p.filter=b.dataset.filter;return true},
 mount(container){for(const toolbar of container.querySelectorAll('[data-menu-toolbar]')){const id=toolbar.dataset.menuToolbar,p=pref(id);let count=0,total=0;for(const el of container.querySelectorAll('[data-menu-list="'+id+'"]')){total++;el.hidden=!menuMatches(el.dataset.search,el.dataset.tags,p.query,p.filter);if(!el.hidden)count++}const counter=container.querySelector('[data-menu-count="'+id+'"]');if(counter)counter.textContent=num(count)+' من '+num(total);const zero=container.querySelector('[data-menu-empty="'+id+'"]');if(zero)zero.hidden=count>0||total===0;const search=container.querySelector('[data-menu-search="'+id+'"]');if(search)search.value=p.query}for(const input of container.querySelectorAll('[data-menu-quantity]'))this.quantity(input,container)},
 quantity(input,container){const total=container.querySelector('[data-menu-total="'+input.dataset.menuQuantity+'"]');if(total){const qty=Number(input.value);total.textContent=Number.isInteger(qty)&&qty>=1&&qty<=500?egp(qty*Number(input.dataset.unit)):'أدخل كمية من ١ إلى ٥٠٠'}},
 input(input,container){if(input.dataset.menuSearch){pref(input.dataset.menuSearch).query=input.value;this.mount(container)}if(input.dataset.menuQuantity)this.quantity(input,container)},
 shell(id,html,started){if(!started)return '<div class="menu-workspace">'+html+'</div>';const group=MENU_GROUPS.find(x=>x[2].some(([key])=>key===id))||MENU_GROUPS[0];return '<div class="menu-shell"><aside class="menu-sidebar"><div class="menu-brand"><b>س</b><div>وكالة سعيد<small>مركز إدارة التشغيل</small></div></div><nav aria-label="أقسام الإدارة">'+MENU_GROUPS.map(([icon,title,items])=>'<button data-action="panelNav" data-panel="'+items[0][0]+'" class="'+(icon===group[0]?'active':'')+'">'+menuIcon(icon)+'<span>'+title+'</span></button>').join('')+'</nav><div class="menu-sidebar-foot">اليوم '+num(s().day)+'<b>'+egp(s().money)+'</b></div></aside><div class="menu-workspace"><nav class="menu-subnav" aria-label="قوائم '+group[1]+'">'+group[2].filter(([key])=>panels[key]&&key!=='company').map(([key,title])=>'<button data-action="panelNav" data-panel="'+key+'" aria-current="'+(key===id?'page':'false')+'">'+title+'</button>').join('')+'</nav>'+html+'</div></div>'}
 };
}
export function vehicleArtwork(vehicle,cid='agency'){const b=TRUCK_BRANDS[cid]||TRUCK_BRANDS.agency;return '<svg class="menu-vehicle" viewBox="0 0 340 140" role="img" aria-label="عربية صندوق '+V[vehicle.kind].name+'"><ellipse cx="174" cy="120" rx="143" ry="8" fill="#173d3e" opacity=".1"/><path d="M25 28h201v75H25Z" fill="'+b.color+'"/><path d="M226 58h49l39 34v18h-88Z" fill="#f2eddf" stroke="#748c88"/><path d="M239 64h30l21 23h-51Z" fill="#568588"/><path d="M23 102h294v10H23Z" fill="#344f50"/><circle cx="73" cy="111" r="17" fill="#23363b"/><circle cx="73" cy="111" r="7" fill="#a0b3ae"/><circle cx="275" cy="111" r="17" fill="#23363b"/><circle cx="275" cy="111" r="7" fill="#a0b3ae"/><text x="126" y="69" text-anchor="middle" font-family="Tahoma,Arial" font-size="20" font-weight="bold" fill="'+b.accent+'">'+b.name+'</text>'+(vehicle.kind!=='normal'?'<rect x="198" y="20" width="26" height="20" rx="3" fill="#bed8d3"/><path d="M203 25h16m-16 5h16m-16 5h16" stroke="#537574"/>':'')+'</svg>'}
