import {VEHICLES as V,COMPANIES as C} from './economy.js';
import {vehicleArtwork,menuIcon,MENU_GROUPS} from './menu-ui.js';
import {tripStatus} from './trip-status.js';
import {brandImage} from './brands.js';
export function installFleetMenus({panels,menu,getSim,btn,row,egp,num,esc,fleetMap}){
 const g=()=>getSim(),s=()=>g().s,{metrics,badge,link,progress,toolbar,record,noResults}=menu;
 const original={...panels};
 const vehicleCard=v=>{const d=s(),trip=g().allTrips().find(t=>t.vehicleId===v.id),service=d.ops.services.find(j=>j.id===v.id),cargo=trip?.cargo||(v.id===d.selectedVehicle?d.cargo:d.vehicleLoads[v.id]||[]),qty=cargo.reduce((n,b)=>n+b.qty,0),clients=[...new Set(cargo.map(b=>d.orders.find(o=>o.id===b.order)?.client).filter(id=>id!==undefined))],plan=d.routePriorities[v.id]||[],event=v.id===d.selectedVehicle?d.tripEvent:trip?.event;return '<div class="menu-card-top"><small>عربية #'+num(v.id)+'</small>'+badge(event?'قرار طريق':trip?'في التوزيع':service?'داخل الصيانة':'جاهزة بالجراج',event?'danger':trip?'info':service?'warn':'good')+'</div>'+vehicleArtwork(v,d.development.branding[v.id]||'agency')+'<h3>'+V[v.kind].name+'</h3>'+row('التوكيل',C[d.development.branding[v.id]]?.short||'وكالة سعيد')+row('الحمولة',num(qty)+' / '+num(v.capacity)+' كرتونة')+progress(qty,v.capacity,'حمولة العربية '+v.id)+row('الحالة العامة',num(v.condition)+'٪')+'<p class="menu-trip-status">'+(trip?tripStatus(d,trip):service?'الصيانة تنتهي بعد '+num(Math.max(0,service.until-d.elapsed))+' ث':'اختر العربية لتجهيز وتحميل طلباتها.')+'</p><footer class="actions">'+btn(v.id===d.selectedVehicle?'فتح العربية':'اختيار العربية','fleetSelect','data-vehicle="'+v.id+'"',!!d.carry||!!d.pickingJob,'secondary')+(trip?btn('الخريطة','fleetFollow','data-vehicle="'+v.id+'"',!!d.carry||!!d.pickingJob,'secondary'):'')+(event?link('اتخاذ قرار الطريق','roadDecisions'):'')+'</footer>'+(v.id===d.selectedVehicle&&!trip&&clients.length?'<details class="menu-details"><summary>أولوية توقفات العملاء</summary><p>'+plan.filter(id=>clients.includes(id)).map(id=>esc(d.clients[id].name)).join(' ← ')+'</p>'+clients.map(id=>btn('ابدأ بـ '+esc(d.clients[id].name),'prioritize','data-client="'+id+'"',false,'secondary')).join('')+'</details>':'')};
 panels.fleet=()=>{const d=s(),trips=g().allTrips();return ['مركز التوزيع','أسطول وكالة سعيد',metrics([['العربيات',num(d.vehicles.length),'حد الأسطول ٥ عربيات'],['رحلات شغالة',num(trips.length)],['السائقون',num(d.staff.driver)]])+toolbar('fleet',[['all','كل العربيات'],['parked','في الجراج'],['trip','على الطريق'],['service','صيانة']],'ابحث برقم العربية أو نوعها أو توكيلها')+'<div class="menu-grid">'+d.vehicles.map(v=>record('fleet',v.id+' '+V[v.kind].name+' '+(C[d.development.branding[v.id]]?.name||'وكالة سعيد'),trips.some(t=>t.vehicleId===v.id)?'trip':d.ops.services.some(j=>j.id===v.id)?'service':'parked',vehicleCard(v))).join('')+'</div>'+noResults('fleet')+'<section class="menu-section"><h3>تتبّع العربيات والمناديب</h3>'+fleetMap()+'</section><div class="actions">'+link('إدارة التحميل وشراء عربية','truck')+link('الصيانة الوقائية','garage')+link('ترتيب خطوط التوزيع','planner')+link('هوية الأسطول','fleetStyle')+link('تعيين سائق','staff')+link('خطوط المناديب','reps')+'</div>']};
 panels.truck=()=>{const view=original.truck(),d=s(),v=g().vehicle;if(!d.repaired)return view;view[1]='العربية '+num(v.id)+' · التحميل والتوزيع';view[2]='<div class="menu-vehicle-focus">'+vehicleArtwork(v,d.development.branding[v.id]||'agency')+'<div><small>العربية المختارة</small><h3>'+V[v.kind].name+'</h3><p>'+tripStatus(d)+'</p>'+link('تغيير العربية','fleet')+'</div></div><div class="menu-truck-operations">'+view[2]+'</div>';return view};
 panels.garage=()=>{const d=s();return ['ورشة وكالة سعيد','الجراج والصيانة',metrics([['عربيات داخل الورشة',num(d.ops.services.length)],['الورشة',d.ops.garageLevel?'مجهزة':'أساسية'],['زمن الخدمة',d.ops.garageLevel?'١٥ ثانية':'٣٠ ثانية']])+(!d.ops.garageLevel?'<div class="menu-callout"><div><h3>جهّز ورشتك</h3><p>تقل مدة الصيانة من ٣٠ إلى ١٥ ثانية.</p></div>'+btn('تجهيز · ٤٬٥٠٠ ج','garageUpgrade')+'</div>':'')+'<div class="menu-grid">'+d.vehicles.map(v=>{const m=g().mechanical(v.id),away=g().allTrips().some(t=>t.vehicleId===v.id),job=d.ops.services.find(j=>j.id===v.id);return '<article class="menu-record">'+vehicleArtwork(v,d.development.branding[v.id]||'agency')+'<div class="menu-card-top"><h3>عربية '+num(v.id)+'</h3>'+badge(away?'في رحلة':job?'صيانة جارية':'راكنة',away?'info':job?'warn':'good')+'</div>'+row('المسافة',m.km.toFixed(1)+' كم')+(job?'<p>متبقي '+num(Math.max(0,job.until-d.elapsed))+' ثانية</p>':'')+Object.entries({tires:['الكاوتش',650],oil:['الزيت',350],brakes:['الفرامل',500],cooling:['التبريد',750]}).filter(([part])=>part!=='cooling'||['chilled','frozen'].includes(v.kind)).map(([part,[name,cost]])=>'<div class="menu-service">'+row(name,num(m[part])+'٪')+progress(m[part],100,name)+btn('صيانة · '+egp(Math.round(cost*(m[part]<10?1.75:1))),'serviceVehicle','data-vehicle="'+v.id+'" data-part="'+part+'"',away||!!job||m[part]>=99,'secondary')+'</div>').join('')+'</article>'}).join('')+'</div><p class="note">تحذير عند ٣٥٪. الكاوتش والزيت والفرامل الأقل من ١٠٪ تمنع الخروج؛ تكلفة صيانتها أعلى ٧٥٪.</p><div class="actions">'+link('التطوير والمعدات','development')+link('ملصقات وغسيل العربيات','fleetStyle')+link('الأسطول','fleet')+'</div>']};
 panels.company=()=>{const view=original.company();view[2]='<div class="menu-contract-document"><div class="menu-document-top"><span>وكالة سعيد للتجارة والتوزيع</span><b>ملف شراكة وتوزيع</b></div>'+view[2]+'</div>';return view};
 panels.tablet=()=>{const d=s(),newOrders=d.orders.filter(o=>!o.accepted).length,pending=d.invoices.filter(v=>!v.settled).length,decisions=g().allTrips().filter(t=>t.vehicleId===d.selectedVehicle?d.tripEvent:t.event).length;return ['وكالة سعيد · مركز التشغيل','تابلت الإدارة','<div class="menu-welcome"><div><small>كل شغلك في مكان واحد</small><h3>أهلًا، '+esc(d.name)+'</h3><p>تابع الطلبات، جهّز البضاعة، وراجع تحصيلك.</p></div>'+brandImage('agency')+'</div>'+metrics([['الخزنة',egp(d.money),'رصيد متاح'],['طلبات جديدة',num(newOrders),'تحتاج ردك'],['رحلات نشطة',num(g().allTrips().length),'التوزيع مستمر'],['فواتير مفتوحة',num(pending),'مراجعة وتحصيل']])+(decisions?'<div class="menu-callout warning"><div><h3>عربية مستنية قرارك</h3><p>'+num(decisions)+' توقف في الطريق يحتاج متابعة.</p></div>'+link('قرارات الطريق','roadDecisions')+'</div>':'')+'<div class="menu-launcher">'+MENU_GROUPS.map(([icon,title,items])=>'<section><h3>'+menuIcon(icon)+title+'</h3><div>'+items.filter(([id])=>id!=='tablet'&&id!=='company'&&panels[id]).map(([id,label])=>'<button data-action="panelNav" data-panel="'+id+'"><span>'+label+'</span><b aria-hidden="true">←</b></button>').join('')+'</div></section>').join('')+'</div>']};
}
