import {ANALYTICS_CONFIG} from './analytics-config.js';
import {MISSIONS} from './economy.js';
const $=s=>document.querySelector(s),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),number=v=>Number(v).toLocaleString('ar-EG');let key='',endpoint='',report=null,busy=false,generation=0;
$('#endpoint').value=ANALYTICS_CONFIG.endpoint||(/^https?:$/.test(location.protocol)?new URL('/api/telemetry',location.href).href:'');
const labels={sign:'استلام الوكالة',inventory:'الجرد',repair:'إصلاح العربية',buy:'شراء بضاعة',receive:'استلام بضاعة',accept:'تأكيد طلب',reject:'رفض طلب',pack:'تجهيز',load:'تحميل',dispatch:'خروج رحلة',approve:'اعتماد أو تحصيل',contract:'توقيع توكيل',upgrade:'ترقية',hire:'توظيف',unlock:'فتح منطقة',buyDevelopment:'تطوير الوكالة',chooseStory:'قرار قصة'};
function bars(items){if(!items.length)return '<p class="hint">لا بيانات في هذه الفترة.</p>';const max=Math.max(1,...items.map(x=>x[1]));return items.map(([label,n])=>'<div class="bar-row"><span>'+esc(label)+'</span><div class="bar-track"><i style="width:'+Math.round(n/max*100)+'%"></i></div><b>'+number(n)+'</b></div>').join('')}
export function drawStats(d){$('#metrics').innerHTML=[[d.visitors,'متصفحات زائرة'],[d.sessions,'جلسات مسجلة'],[d.starts,'جلسات بدأت اللعب'],[d.active,'متصلة خلال ٩٠ ثانية'],[Math.round(d.activeSeconds/60),'دقائق لعب فعلية'],[Math.round(d.averageSeconds/60),'متوسط دقائق الجلسة التي بدأت'],[Object.values(d.errors).reduce((a,b)=>a+b,0),'أخطاء برمجية'],[d.retentionDays,'أيام الاحتفاظ']].map(([n,label])=>'<article class="metric"><strong>'+number(n)+'</strong><small>'+label+'</small></article>').join('');$('#daily').innerHTML=bars(d.daily.map(x=>[x.date+' · جلسات',x.sessions]));$('#devices').innerHTML=bars(Object.entries(d.devices).map(([k,v])=>[k==='mobile'?'موبايل / لمس':'كمبيوتر',v]));$('#progress').innerHTML=bars(d.lastMissions.map((n,i)=>[MISSIONS[i].title,n]).filter(x=>x[1]));$('#actions').innerHTML=bars(Object.entries(d.actions).sort((a,b)=>b[1]-a[1]).slice(0,30).map(([k,v])=>[(labels[k.split(':')[0]]||k)+(k.includes(':')?' · '+k.split(':').slice(1).join(' / '):''),v]));$('#errors').innerHTML=bars(Object.entries(d.errors).sort((a,b)=>b[1]-a[1]).slice(0,20));$('#sessions').innerHTML=d.recent.map(s=>'<tr><td>'+esc(s.id)+'</td><td>'+esc(s.device==='mobile'?'موبايل':'كمبيوتر')+' / '+esc(s.version)+'</td><td>'+esc(MISSIONS[s.mission].title)+'</td><td>'+number(Math.round(s.activeSeconds/60))+' د</td><td>'+esc(new Date(s.lastSeen).toLocaleString('ar-EG'))+'</td></tr>').join('')||'<tr><td colspan="5">لسه مفيش جلسات مسجلة.</td></tr>'}
async function refresh(){if(busy||!key)return;busy=true;const requestGeneration=generation;$('#refresh').disabled=true;$('#status').textContent='جارٍ الاتصال…';try{const url=new URL(endpoint);url.pathname=url.pathname.replace(/\/$/,'')+'/summary';url.search='days='+$('#range').value;const response=await fetch(url,{headers:{Authorization:'Bearer '+key},cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(10000)});let data;try{data=await response.json()}catch{throw Error('العنوان لا يقدم خادم إحصائيات. GitHub Pages وحده لا يشغل الخادم.')}if(!response.ok)throw Error(data.error||'تعذر الاتصال');if(requestGeneration!==generation)return;report=data;drawStats(data);$('#dashboard').hidden=false;$('#login').hidden=true;$('#connection').textContent='متصل';$('#status').textContent='آخر تحديث: '+new Date(data.generatedAt).toLocaleString('ar-EG')+' · تحديث تلقائي كل دقيقة.'}catch(e){if(requestGeneration!==generation)return;$('#connection').textContent='الاتصال متعذر';$('#status').textContent=e.message+' — الأرقام السابقة إن وُجدت ليست تحديثًا جديدًا.'}finally{busy=false;$('#refresh').disabled=false}}
$('#stats-login').addEventListener('submit',e=>{e.preventDefault();try{const u=new URL($('#endpoint').value.trim());if(u.username||u.password||u.search||u.hash||!u.pathname.endsWith('/api/telemetry')||!(u.protocol==='https:'||u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))throw Error();endpoint=u.href;key=$('#admin-key').value;$('#admin-key').value='';void refresh()}catch{$('#status').textContent='اكتب رابط HTTPS ينتهي بـ /api/telemetry، أو localhost للاختبار.'}});
$('#refresh').onclick=refresh;$('#range').onchange=refresh;$('#logout').onclick=()=>{generation++;key='';report=null;$('#dashboard').hidden=true;$('#login').hidden=false;$('#connection').textContent='غير متصل';$('#status').textContent='تم الخروج.'};$('#export').onclick=()=>{if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Saeed-Analytics-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};setInterval(()=>{if(!document.hidden&&key&&!$('#dashboard').hidden)void refresh()},60000);
