import {ANALYTICS_CONFIG} from './analytics-config.js';
export const TRACKED_ACTIONS=['sign','inventory','repair','buy','receive','accept','reject','pack','load','dispatch','approve','contract','upgrade','hire','unlock','buyDevelopment','chooseStory'];
const errorKinds=new Set(['Error','TypeError','ReferenceError','RangeError','SyntaxError','URIError','EvalError']);
export function safeError(error,filename='',line=0){return {kind:errorKinds.has(error?.name)?error.name:'Error',file:/^[a-zA-Z0-9_-]+\.js$/.test(filename.split('/').at(-1)?.split('?')[0]||'')?filename.split('/').at(-1).split('?')[0]:'runtime',line:Math.min(100000,Math.max(0,Math.floor(Number(line)||0)))}};
export function randomVisitorId(){return globalThis.crypto?.randomUUID?.()||'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.floor(Math.random()*16);return (c==='x'?r:(r&3)|8).toString(16)})}
export class Telemetry{
 constructor({storage,endpoint=ANALYTICS_CONFIG.endpoint,transport=globalThis.fetch,uuid=randomVisitorId,device='desktop',privateMode=false}={}){Object.assign(this,{storage,transport,device});this.endpoint='';try{const u=new URL(endpoint);if(!u.username&&!u.password&&!u.search&&!u.hash&&(u.protocol==='https:'||u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))this.endpoint=u.href}catch{}this.privateMode=privateMode;this.uuid=uuid;this.queue=[];this.seq=0;this.activeSeconds=0;this.clock=0;this.flushClock=0;this.errors=0;this.state=null;this.bound=new WeakSet();this.enabled=this.read('saeed_metrics_optout')!=='1';this.session=uuid();this.visitor=this.read('saeed_metrics_visitor')||uuid();this.status=this.endpoint?'جاهز للاتصال':'لم يتم ربط خادم الإحصائيات';this.started=false;this.sentVisit=false;this.busy=false;this.cooldown=0;this.sendInitial();}
 read(key){try{return this.storage?.getItem(key)}catch{return null}}
 get allowed(){return !!this.endpoint&&this.enabled&&!this.privateMode&&!this.state?.testMode}
 setEnabled(value){this.enabled=!!value;try{this.storage?.setItem('saeed_metrics_optout',value?'0':'1')}catch{}this.queue=[];if(!value){this.session=this.uuid();this.visitor=this.uuid();this.sentVisit=false;this.started=false;this.seq=0;this.activeSeconds=0;try{this.storage?.removeItem('saeed_metrics_visitor')}catch{}}else this.sendInitial();}
 snapshot(){const s=this.state;return {mission:s?.mission||0,stage:s?.development?.stage||0,delivered:Math.min(1000000,s?.delivered||0),day:Math.min(1000000,s?.day||1),activeSeconds:Math.floor(this.activeSeconds)}}
 sendInitial(){if(!this.allowed||this.sentVisit)return;this.sentVisit=true;try{this.storage?.setItem('saeed_metrics_visitor',this.visitor)}catch{}this.emit('visit')}
 emit(kind,key='',error){if(!this.allowed)return;this.queue.push({seq:++this.seq,kind,key,snapshot:this.snapshot(),...(error?{error}:{})});if(this.queue.length>100)this.queue.splice(0,this.queue.length-100)}
 bind(sim){this.state=sim.s;if(this.bound.has(sim))return;this.bound.add(sim);for(const name of TRACKED_ACTIONS){const old=sim[name];if(typeof old!=='function')continue;sim[name]=(...args)=>{const ok=old.apply(sim,args);this.state=sim.s;if(ok===true){let key=name;if(name==='contract')key+=':'+args[0];if(name==='chooseStory')key+=':'+args[0]+':'+args[1];this.emit('action',key)}return ok}}}
 frame(dt,sim,started,active){this.state=sim.s;if(!this.allowed)return;this.sendInitial();if(started&&!this.started){this.started=true;this.emit('start')}if(active)this.activeSeconds+=Math.max(0,Math.min(dt,1));this.clock+=dt;this.flushClock+=dt;this.cooldown=Math.max(0,this.cooldown-dt);if(this.clock>=30){this.clock=0;this.emit('heartbeat')}if(this.flushClock>=8&&this.queue.length&&!this.cooldown){this.flushClock=0;void this.flush()}}
 error(error,filename,line){if(this.errors++>=12)return;this.emit('error','',safeError(error,filename,line));}
 async flush(){if(!this.allowed||this.busy||!this.queue.length)return false;this.busy=true;const events=this.queue.slice(0,20),body=JSON.stringify({visitor:this.visitor,session:this.session,version:ANALYTICS_CONFIG.version,device:this.device,events}),session=this.session;try{const response=await this.transport(this.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'omit',keepalive:true,body,signal:globalThis.AbortSignal?.timeout?.(8000)});if(!response.ok)throw Error('unavailable');if(session===this.session)this.queue=this.queue.filter(e=>e.seq>events.at(-1).seq);this.status='متصل — آخر إرسال ناجح';return true}catch{this.status='الاتصال متعذر؛ اللعب مستمر';this.cooldown=30;return false}finally{this.busy=false}}
}
export function TelemetryUI({panels,getTelemetry,btn}){const old=panels.settings;panels.settings=()=>{const p=old(),t=getTelemetry();p[2]+='<article class="card"><h3>إحصائيات تحسين اللعبة</h3><p>معرّف عشوائي للمتصفح والجلسة، نوع الجهاز، مدة اللعب والتقدم ومكان الخطأ البرمجي. بدون اسمك أو ملف حفظك أو عنوان IP محفوظ في الإحصائيات. يمكنك إيقاف المشاركة.</p><p>'+t.status+'</p>'+btn(t.enabled?'إيقاف مشاركة الإحصائيات':'تفعيل مشاركة الإحصائيات','telemetryToggle','','','secondary')+'</article>';return p};return {handle(b){if(b.dataset.action!=='telemetryToggle')return false;const t=getTelemetry();t.setEnabled(!t.enabled);return true}}}
