import {CAST,CHAPTERS,SCENES,RECURRING,sceneById,storyLines} from './story-data.js';
export const portraitURL=id=>globalThis.SAEED_PORTRAITS?.[id]||'./assets/portraits/'+id+'.png';
export function StoryUI({panels,getSim,getWorld,btn,esc,open,close,save,canPresent,isStarted}){
 let active=null,line=0,result=null,replay=false,previousFocus=null,lastState=null,seenBark=0,uiTime=0,lastClose=-20,lastBadge='',barkUntil=0;
 const root=document.createElement('section');root.id='story-overlay';root.hidden=true;root.dir='rtl';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-labelledby','story-title');document.body.appendChild(root);
 const badge=document.createElement('button');badge.id='story-badge';badge.hidden=true;badge.onclick=()=>open('story');document.body.appendChild(badge);
 const bark=document.createElement('aside');bark.id='story-bark';bark.hidden=true;bark.setAttribute('aria-live','polite');document.body.appendChild(bark);
 const picture=(id,cls='')=>'<img class="'+cls+'" src="'+portraitURL(id)+'" alt="'+esc(CAST[id].name)+'" width="160" height="160">';
 const lines=()=>storyLines(active,getSim().s);
 function draw(){if(!active)return;const all=lines(),entry=result?{who:'player',text:result}:all[line],person=CAST[entry.who],decision=line===all.length-1&&!result;
  getWorld()?.setStoryShot(entry.who,entry.shot||'face');
  root.innerHTML='<header class="story-top"><div><small>'+esc(active.chapter===undefined?'حكايات بين النقلات':CHAPTERS[active.chapter])+' · الوقت متوقف</small><h2 id="story-title">'+esc(active.title)+'</h2></div><button data-story="defer" aria-label="تأجيل المحادثة">'+(replay?'إغلاق':'نكمل بعدين')+' ×</button></header><div class="story-dialogue"><div class="story-portrait" style="--cast:'+person.color+'">'+picture(entry.who)+'<b>'+esc(entry.who==='player'?getSim().s.name:person.name)+'</b><small>'+esc(person.role)+'</small></div><div class="story-copy"><div class="story-steps">'+all.map((_,i)=>'<i class="'+(i<=line?'read':'')+'"></i>').join('')+'</div><p class="story-line">'+esc(entry.text)+'</p>'+(result?'<button data-story="finish" class="primary">رجوع للشغل ←</button>':decision?'<div class="story-choices">'+active.choices.map(c=>'<button data-story-choice="'+c.id+'" '+(!replay&&(c.effect.cost||0)>getSim().s.money?'disabled':'')+'><b>'+esc(c.label)+'</b><small>'+esc(c.consequence)+(replay?' · عرض فقط':'')+'</small></button>').join('')+'</div>':'<button data-story="next" class="primary">كمّل الحوار ←</button>')+(line>0&&!result?'<button data-story="back" class="secondary">الجملة السابقة</button>':'')+'<small class="story-footnote">'+(replay?'إعادة مشاهدة فقط؛ لا تتكرر النتائج.':'الاختيار محفوظ؛ التأجيل لا يختار بالنيابة عنك.')+'</small></div></div>';
  root.querySelector('[data-story="next"], [data-story="finish"], [data-story-choice]:not(:disabled), button')?.focus({preventScroll:true});
 }
 function present(id,review=false){const scene=sceneById(id);if(!scene)return;previousFocus=document.activeElement;active=scene;line=0;result=null;replay=review;close();root.hidden=false;bark.hidden=true;document.body.classList.add('story-playing');getWorld()?.beginStory(scene,(scene.lines?.[0]?.who)||scene.who,'wide');draw();}
 function finish(defer=false){if(!active)return;if(defer&&!replay)getSim().deferStory();active=null;result=null;root.hidden=true;document.body.classList.remove('story-playing');getWorld()?.endStory();lastClose=uiTime;save();previousFocus?.focus?.({preventScroll:true});}
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;e.stopPropagation();if(b.dataset.storyChoice){if(replay){result='اخترت وقتها: '+(active.choices.find(c=>c.id===getSim().s.story.decisions[active.id])?.label||'—');draw();return}const c=active.choices.find(c=>c.id===b.dataset.storyChoice);if(getSim().chooseStory(active.id,c.id)){result=c.reply||'اتسجل الاختيار في دفتر الحكاية. '+c.consequence;save();draw();}return;}const a=b.dataset.story;if(a==='next'){line=Math.min(lines().length-1,line+1);draw()}if(a==='back'){line=Math.max(0,line-1);draw()}if(a==='defer')finish(!result);if(a==='finish')finish();});
 document.addEventListener('keydown',e=>{if(!active)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();finish(!result)}if(e.key==='Tab'){const all=[...root.querySelectorAll('button:not(:disabled)')],first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}},true);
 panels.story=()=>{const s=getSim().s,n=s.story,pending=sceneById(n.queue[0]),next=SCENES.find(x=>!n.done.includes(x.id)),last=[...SCENES].reverse().find(x=>n.done.includes(x.id));return ['دفتر عم سعيد • الاسم لسه عايش','حكاية وكالة سعيد','<article class="card"><h3>'+CHAPTERS[n.chapter]+'</h3><p>قصة داخل عالم الوكالة، مع صور الشخصيات وقرارات تؤثر في الثقة والمصاريف والفريق. يتوقف الوقت أثناء المشهد فقط. ربيع مستشار وصديق سعيد؛ لا يستبدل السائق الموظف.</p>'+btn(n.enabled?'إيقاف ظهور القصة':'ابدأ / استأنف القصة','storyToggle')+btn(n.frequency==='rich'?'حوارات أهدى':'حوارات أكثر','storyFrequency','','', 'secondary')+'<p>'+(!n.offered?'حفظك القديم محفوظ بالكامل. تفعيل القصة لا يعيد تقدمك؛ بعض المشاهد تسترجع ما أنجزته.':'تقدر تؤجل أي مشهد وترجع له هنا.')+'</p></article>'+(n.enabled&&pending?'<article class="card"><h3>المشهد المتاح: '+esc(pending.title)+'</h3>'+btn('افتح المحادثة','storyPresent')+'</article>':'')+'<article class="card"><h3>خطوتك في الحكاية</h3><p>'+esc(last?.goal||next?.goal||'واصل التوزيع؛ المواقف الدورية مستمرة.')+'</p><p>مشاهد رئيسية مكتملة: '+n.done.filter(id=>SCENES.some(x=>x.id===id)).length+' / '+SCENES.length+' · تجهيزات عامل أسرع متبقية: '+n.prep+'</p></article><div class="story-cast-list">'+Object.entries(CAST).filter(([id])=>id!=='player').map(([id,c])=>'<article class="card">'+picture(id)+'<div><h3>'+c.name+'</h3><small>'+c.role+'</small><p>العلاقة: '+n.bonds[id]+' / ١٠٠</p></div></article>').join('')+'</div><h3>صفحات وقرارات محفوظة</h3>'+(n.history.length?n.history.map(h=>{const scene=sceneById(h.scene),c=scene.choices.find(c=>c.id===h.choice);return '<article class="card"><small>اليوم '+h.day+'</small><h3>'+esc(scene.title)+'</h3><p>'+esc(c.label)+' — '+esc(c.consequence)+'</p>'+btn('شاهد الحوار','storyReplay','data-scene="'+h.scene+'"',false,'secondary')+'</article>'}).join(''):'<p>أول اختيار هيظهر هنا.</p>')]};
 for(const id of ['tablet','settings','diary'])if(panels[id]){const old=panels[id];panels[id]=()=>{const p=old();p[2]+=btn('دفتر الحكاية والشخصيات','storyOpen','','','secondary');return p}}
 return {get active(){return !!active},handle(b){switch(b.dataset.action){case'storyOpen':open('story');return true;case'storyToggle':getSim().enableStory(!getSim().s.story.enabled);return true;case'storyFrequency':getSim().storyFrequency(getSim().s.story.frequency==='rich'?'normal':'rich');return true;case'storyPresent':if(getSim().s.story.enabled)present(getSim().s.story.queue[0]);return true;case'storyReplay':if(getSim().s.story.done.includes(b.dataset.scene))present(b.dataset.scene,true);return true;default:return false}},update(dt){uiTime+=dt;const s=getSim().s,n=s.story;if(lastState!==s){if(active)finish();lastState=s;seenBark=0;lastBadge='';}
 badge.hidden=!isStarted()||!!active||!canPresent();const label=!n.offered?'حكاية الوكالة · جديد':!n.enabled?'دفتر الحكاية':n.queue.length?'حوار جديد · '+sceneById(n.queue[0]).title:'دفتر الحكاية · '+CHAPTERS[n.chapter];if(label!==lastBadge){badge.textContent=label;lastBadge=label}
 if(!active&&isStarted()&&canPresent()&&n.enabled&&n.queue.length&&s.elapsed>=n.snooze&&uiTime-lastClose>=12){present(n.queue[0]);return;}
 if(!active&&isStarted()&&canPresent()&&n.enabled&&n.bark&&n.bark.id!==seenBark){seenBark=n.bark.id;if(s.elapsed-n.bark.at<12){bark.innerHTML=picture(n.bark.who)+'<div><b>'+esc(CAST[n.bark.who].name)+'</b><p>'+esc(n.bark.text)+'</p></div>';barkUntil=uiTime+6;}}
 bark.hidden=!!active||!isStarted()||!canPresent()||uiTime>barkUntil||!n.enabled;
 }};
}
