export const VOICE_LINES={welcome:'أهلًا بيك في وكالة سعيد. ابدأ من المكتب واستلم الوكالة.',order:'ألو يا أستاذ سعيد، محتاجين طلبية جديدة. راجع التليفون وشوف المطلوب.',driver:'العربية جاهزة. راجع الحمولة وخط السير قبل ما نطلع.',diary:'المخزن المليان مش دايمًا رزق. الرزق في بضاعة تلف وتتحصل قبل ما تبوظ.'};
function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('saeed-voices',1);r.onupgradeneeded=()=>r.result.createObjectStore('clips');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function clip(key,value){const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('clips',value?'readwrite':'readonly'),store=tx.objectStore('clips');const r=value?store.put(value,key):store.get(key);r.onerror=()=>reject(r.error);tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
export function VoiceUI({panels,btn,esc,open,toast}){
 let recorder=null,stream=null,timer=null,activeAudio=null;
 const prev=panels.settings;panels.settings=()=>{const p=prev();p[2]+=btn('استوديو الحوارات المسجلة','voiceOpen');return p};
 panels.voice=()=>['صوت بشري من تسجيلك','استوديو حوارات الوكالة','<p>سجل الجمل بصوتك أو ارفع تسجيلًا لديك حق استخدامه. التسجيل محلي على الجهاز، ويعمل عند الحدث المرتبط به. لا توجد أصوات ممثلين مرفقة أو ادعاء أن الصوت الآلي تسجيل بشري.</p>'+Object.entries(VOICE_LINES).map(([key,line])=>'<div class="card"><p>'+esc(line)+'</p>'+btn('تسجيل حتى ٣٠ ثانية','voiceRecord','data-key="'+key+'"')+btn('تشغيل','voicePlay','data-key="'+key+'"')+btn('تنزيل التسجيل','voiceExport','data-key="'+key+'"')+'<label>استيراد ملف صوت (حتى ٥ ميجابايت)<input type="file" accept="audio/*" data-voice-import="'+key+'"></label></div>').join('')+btn('إيقاف وحفظ التسجيل','voiceStop')+'<p id="voice-status">'+(recorder?'جارٍ التسجيل…':'الميكروفون لا يعمل إلا عند ضغط تسجيل.')+'</p>'];
 async function play(key){try{const blob=await clip(key);if(!blob)return false;if(activeAudio){activeAudio.pause();URL.revokeObjectURL(activeAudio.src)}const url=URL.createObjectURL(blob);activeAudio=new Audio(url);activeAudio.onended=()=>URL.revokeObjectURL(url);await activeAudio.play();return true}catch{return false}}
 const stop=()=>{clearTimeout(timer);if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());stream=null};
 async function record(key){if(recorder)throw Error('أوقف التسجيل الحالي أولًا.');if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('التسجيل يحتاج HTTPS أو localhost ومتصفحًا يدعم الميكروفون.');stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{const blob=new Blob(chunks,{type:recorder.mimeType});recorder=null;try{if(blob.size>5e6)throw Error('التسجيل أكبر من المسموح');await clip(key,blob);toast('اتحفظ التسجيل محليًا.')}catch(e){toast(e.message,'bad')}};recorder.start();timer=setTimeout(stop,30000);open('voice')}
 document.addEventListener('change',async e=>{const key=e.target.dataset?.voiceImport;if(!key)return;const file=e.target.files?.[0];if(!file)return;try{if(!file.type.startsWith('audio/')||file.size>5e6)throw Error('اختار ملف صوت أقل من ٥ ميجابايت.');await clip(key,file);toast('تم استيراد التسجيل.')}catch(e){toast(e.message,'bad')}});
 return {play,stop,handle(b){const a=b.dataset.action,key=b.dataset.key;if(!a.startsWith('voice'))return false;if(a==='voiceOpen')open('voice');if(a==='voiceStop')stop();if(a==='voiceRecord')record(key).catch(e=>{stop();recorder=null;toast(e.message,'bad')});if(a==='voicePlay')play(key).then(ok=>{if(!ok)toast('سجّل الجملة أو ارفع ملفها أولًا.')});if(a==='voiceExport')clip(key).then(blob=>{if(!blob)return toast('لا يوجد تسجيل.');const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=key+(blob.type.includes('webm')?'.webm':blob.type.includes('ogg')?'.ogg':'.audio');link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}).catch(e=>toast(e.message,'bad'));return true}};
}
