import {narrativeWorld} from './world/story.js';
import {detail} from './world/detail.js';
import {environment} from './world/environment.js';
import {BAY_X,BAY_Z,yardPosition} from './world/fleet-path.js';
import {models} from './world/models.js';
import {city} from './world/city.js';
import * as T from './vendor/three.module.js';
import * as Agency from './economy.js';
import {effects} from './world/effects.js';
import {materials} from './world/materials.js';
import {scene} from './world/scene.js';
import {warehouse} from './world/warehouse.js';
import {actors} from './world/actors.js';
import {picking} from './world/picking.js';
import {pathfinding} from './world/pathfinding.js';
export class AgencyWorld {
constructor(callbacks){this.cb=callbacks;this.touchDevice=globalThis.matchMedia?.('(pointer:coarse)').matches||false;this.canvas=document.getElementById('world');const canvas=this.canvas;this.scene=new T.Scene();this.scene.background=new T.Color('#89a5a4');this.scene.fog=new T.Fog('#89a5a4',65,150);this.renderer=callbacks.rendererFactory?callbacks.rendererFactory(canvas):new T.WebGLRenderer({canvas,antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.touchDevice?1.25:1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.VSMShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.22;this.camera=new T.PerspectiveCamera(40,innerWidth/innerHeight,.1,250);this.target=new T.Vector3(0,0,1);this.focusTarget=this.target.clone();this.angle=.55;this.radius=42;this.elevation=.77;this.zoomTarget=42;this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.obstacles=[];this.interactables=[];this.path=[];this.keys={};this.active=false;this.pending=null;this.near=null;this.elapsed=0;this.state=null;this.lastVisual='';this.room='';this.mats={};this.buildMaterials();this.buildWorld();this.buildPlayer();this.buildCity();this.buildEnvironment();this.initDetail();this.initEffects();if(!callbacks.rendererFactory)this.initModels();this.setupInput();this.resize();window.addEventListener('resize',()=>this.resize());}

clearGroup(g){while(g.children.length){const m=g.children.pop();m.parent=null;m.traverse?.(n=>{if(n.geometry)n.geometry.dispose();if(n.material&&!Object.values(this.mats).includes(n.material)){if(!n.userData.sharedTexture)n.material.map?.dispose();n.material.dispose()}});}}

sync(s){this.state=s;const sig=JSON.stringify([s.stock,s.incoming.map(b=>[b.id,b.ready]),s.cargo,s.trip?[s.trip.cargo,s.trip.legIndex]:false,s.vehicles,s.vehicleLoads,s.selectedVehicle,s.carry,s.cooling,s.freezer,s.warehouses,s.warehousePlan,s.fleetTrips.map(t=>t.vehicleId),s.repRoutes.map(r=>r.index),s.pickingJob?.batch.order,s.workerJob?.id,s.officeLevel,s.truckCount,s.staff,s.capacity,s.development.owned.uniforms]);if(sig===this.lastVisual)return;this.lastVisual=sig;if(this.player&&this.blockedAt(this.player.position.x,this.player.position.z)){let found=false;for(let r=.5;r<6&&!found;r+=.5)for(const [dx,dz]of [[r,0],[-r,0],[0,r],[0,-r]]){const x=this.player.position.x+dx,z=this.player.position.z+dz;if(!this.blockedAt(x,z)){this.player.position.set(x,0,z);s.position={x,z};found=true;break}}}this.coolGroup.visible=s.cooling||s.freezer;this.carryMesh.visible=!!s.carry;if(!this.coldSigns){this.coldSigns=new T.Group();this.coolGroup.add(this.coldSigns)}this.clearGroup(this.coldSigns);this.clearGroup(this.extraRacks);this.rackGroup.visible=!s.warehousePlan.customRacks;this.rackGroup.userData.action="shelf";this.extraRacks.userData.action="shelf";if(s.warehousePlan.customRacks)for(const p of s.warehousePlan.customRacks)this.rack(p.x,p.z,this.extraRacks);if(!s.warehousePlan.customRacks&&(s.capacity>160||Object.keys(s.warehouses).some(cid=>s.warehouses[cid].owned&&s.warehousePlan.slots[cid]===3)))this.rack(1,-1.1,this.extraRacks);if(s.capacity>320&&!s.warehousePlan.customRacks)this.rack(5,-1.1,this.extraRacks);const stockRacks=s.warehousePlan.customRacks||this.racks.concat((s.capacity>160||Object.keys(s.warehouses).some(cid=>s.warehouses[cid].owned&&s.warehousePlan.slots[cid]===3))?[{x:1,z:-1.1}]:[],s.capacity>320?[{x:5,z:-1.1}]:[]);this.clearGroup(this.dynamicStock);const companies=Object.keys(Agency.COMPANIES);for(let ci=0;ci<companies.length;ci++){const cid=companies[ci],batches=s.stock.filter(b=>Agency.PRODUCTS[b.pid].company===cid),total=batches.reduce((a,b)=>a+b.qty,0);if(!s.warehouses[cid].owned)continue;const rack=stockRacks[s.warehousePlan.slots[cid]%stockRacks.length];this.label(Agency.COMPANIES[cid].short+' · '+total+' ك',2.6,.28,rack.x,3.14,rack.z+.93,'#f2dca8','#274a48',this.dynamicStock);const n=Math.min(18,Math.ceil(total/5));for(let i=0;i<n;i++){const layer=Math.floor(i/6),j=i%6,b=batches[Math.min(batches.length-1,Math.floor(i/Math.max(1,n/batches.length)))];if(!b)continue;let m=this.mats['product_'+b.pid];if(!m)m=this.mat('product_'+b.pid,Agency.PRODUCTS[b.pid].color,.93);this.carton(rack.x-1+(j%3)*.87,.3+layer,rack.z-.4+Math.floor(j/3)*.78,.95,this.dynamicStock,m).userData.action='batch:'+b.pid}}

 this.clearGroup(this.dynamicIncoming);s.incoming.filter(b=>b.ready).forEach((b,i)=>{for(let j=0;j<Math.min(6,Math.ceil(b.qty/5));j++)this.carton(8.2+(j%3)*.8,.29+Math.floor(j/3)*.59+i*.6,2.6,.98,this.dynamicIncoming)});
 this.clearGroup(this.dynamicCargo);let qty=(s.trip?s.trip.cargo:s.cargo).reduce((a,b)=>a+b.qty,0);this.dynamicCargo.visible=qty>0;for(let j=0;j<Math.min(12,Math.ceil(qty/5));j++)this.carton(-1.95+(j%4)*.77,1.03+Math.floor(j/8)*.58,-.42+Math.floor(j%8/4)*.85,.93,this.dynamicCargo);
 this.decorateTruck(this.truck,s.vehicles.find(v=>v.id===s.selectedVehicle)?.kind);this.clearGroup(this.extraTrucks);for(let i=1;i<s.truckCount;i++){let truck=this.makeTruck();this.decorateTruck(truck,s.vehicles.filter(v=>v.id!==s.selectedVehicle)[i-1]?.kind);const parked=s.vehicles.filter(v=>v.id!==s.selectedVehicle)[i-1];truck.position.set(BAY_X[s.vehicles.findIndex(v=>v.id===parked?.id)],0,BAY_Z);truck.rotation.y=Math.PI/2;truck.userData.vehicle=s.vehicles.filter(v=>v.id!==s.selectedVehicle)[i-1]?.id;truck.userData.action='vehicle:'+truck.userData.vehicle;truck.visible=!s.fleetTrips.some(t=>t.vehicleId===truck.userData.vehicle);const batches=s.vehicleLoads[parked?.id]||[];for(let j=0;j<Math.min(12,Math.ceil(batches.reduce((n,b)=>n+b.qty,0)/5));j++){const b=batches[Math.min(batches.length-1,Math.floor(j/12*batches.length))],m=this.mats['product_'+b.pid]||this.mat('product_'+b.pid,Agency.PRODUCTS[b.pid].color,.93);this.carton(-1.95+(j%4)*.77,1.03+Math.floor(j/8)*.58,-.42+Math.floor(j%8/4)*.85,.93,truck,m)}this.extraTrucks.add(truck)}
 this.clearGroup(this.npcs);this.workerActor=null;this.workerPathKey=null;this.workerBox=null;for(const [role,loc]of Object.entries({driver:[4.8,5.6],worker:[7.4,-3.3],rep:[-6.1,-6.6],accountant:[-13.3,.1]})){if(s.staff[role]){let npc=this.human(role==='worker'?'teal':'shirt',({driver:1,worker:4,rep:5,accountant:8})[role]);npc.position.set(loc[0],0,loc[1]);npc.rotation.y=role==='accountant'?1.5:0;npc.userData.action=role==='driver'?'dialogue':role==='accountant'?'accounts':'staff';const idleDrivers=s.staff.driver-[s.trip,...s.fleetTrips].filter(Boolean).length;npc.visible=role!=='driver'||idleDrivers>0;if(role==='rep')npc.visible=!s.repRoutes.some(r=>r.index===0);if(role==='driver')for(let i=1;i<idleDrivers;i++){const extra=this.human('shirt',1+i);extra.position.set(loc[0]+i*.75,0,loc[1]+.7);extra.userData.action='dialogue';this.npcs.add(extra)}this.npcs.add(npc);if(role==='rep')for(let i=1;i<s.staff.rep;i++){const extra=this.human('teal',5+i);extra.position.set(loc[0]+i*.9,0,loc[1]+.8);extra.userData.action='staff';extra.visible=!s.repRoutes.some(r=>r.index===i);this.npcs.add(extra)}if(role==='worker')this.workerActor=npc;}}
 if(s.officeLevel&&!this.officeUpgrade){this.officeUpgrade=new T.Group();this.scene.add(this.officeUpgrade);this.box(2.2,.7,.8,-8,.4,1.3,'teal',this.officeUpgrade);this.label('وكالة سعيد • موزع معتمد',4.4,.7,-8.8,3.75,-7.96,'#f1d69e','#285758',this.officeUpgrade);}if(this.officeUpgrade)this.officeUpgrade.visible=s.officeLevel>0;this.mats.wood.color.set(s.officeLevel===2?0xcad7cd:0xffffff);

 }

resize(){this.renderer.setSize(innerWidth,innerHeight);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.composer?.setSize(innerWidth,innerHeight)}

quality(level){this.renderer.setPixelRatio(level==='low'?1:Math.min(devicePixelRatio,this.touchDevice?1.25:1.7));this.renderer.shadowMap.enabled=level!=='low';this.resize()}

update(dt,s){this.elapsed+=dt;this.sync(s);const blocked=this.cb.blocked();let moving=false;
 if(this.active&&!blocked){let x=(this.keys.KeyD||this.keys.ArrowRight?1:0)-(this.keys.KeyA||this.keys.ArrowLeft?1:0),z=(this.keys.KeyS||this.keys.ArrowDown?1:0)-(this.keys.KeyW||this.keys.ArrowUp?1:0);let dir=new T.Vector3();if(x||z){this.path=[];this.pending=null;dir.set(x*Math.cos(this.angle)+z*Math.sin(this.angle),0,-x*Math.sin(this.angle)+z*Math.cos(this.angle)).normalize();}else if(this.path.length){let p=this.path[0];dir.set(p.x-this.player.position.x,0,p.z-this.player.position.z);if(dir.length()<.12){this.path.shift();if(!this.path.length){this.destinationRing.visible=false;if(this.pending){const id=this.pending;this.pending=null;this.cb.interact(id);}}}dir.normalize();}
 this.speed=(this.speed||0)+((dir.lengthSq()>0?(s.carry?3.2:4.7):0)-(this.speed||0))*Math.min(1,dt*9);const speed=this.speed;if(dir.lengthSq()>0){const nx=this.player.position.x+dir.x*dt*speed,nz=this.player.position.z+dir.z*dt*speed;if(!this.blockedAt(nx,this.player.position.z))this.player.position.x=nx;if(!this.blockedAt(this.player.position.x,nz))this.player.position.z=nz;const target=Math.atan2(dir.x,dir.z),turn=Math.atan2(Math.sin(target-this.player.rotation.y),Math.cos(target-this.player.rotation.y));this.player.rotation.y+=turn*Math.min(1,dt*9);this.player.rotation.z=-turn*.035;moving=true;}
 s.position={x:this.player.position.x,z:this.player.position.z};}
 const walk=moving?Math.sin(this.elapsed*11)*.55:0;this.player.userData.legs[0].rotation.x=walk;this.player.userData.legs[1].rotation.x=-walk;this.player.userData.arms[0].rotation.x=s.carry?-1:-walk;this.player.userData.arms[1].rotation.x=s.carry?-1:walk;
 if(moving){const phase=Math.floor(this.elapsed*11/Math.PI);if(this.stepPhase!==phase){this.stepPhase=phase;this.cb.footstep?.()}}else this.player.rotation.z*=Math.max(0,1-dt*8);
 if(!blocked)this.fan.rotation.y+=dt*1.4;
 if(this.workerActor&&!blocked&&s.auto){this.workerActor.position.x=7.4+Math.sin(this.elapsed*.6)*1.2;this.workerActor.userData.legs[0].rotation.x=Math.sin(this.elapsed*8)*.4;this.workerActor.userData.legs[1].rotation.x=-Math.sin(this.elapsed*8)*.4;}
 const home=BAY_X[s.vehicles.findIndex(v=>v.id===s.selectedVehicle)];if(s.trip){this.truck.visible=false;}else{this.truck.position.set(home,s.ops.services.some(j=>j.id===s.selectedVehicle)?.2:0,BAY_Z);this.truck.rotation.y=Math.PI/2;this.truck.visible=true;}this.gateBar.rotation.x=[s.trip,...s.fleetTrips].filter(Boolean).some(t=>t.legs[t.legIndex]?.yard)?Math.PI/2:0;const truckSpot=this.interactables.find(o=>o.id==='truck');if(truckSpot){truckSpot.pos.set(home,3.25,BAY_Z);truckSpot.approach={x:home,z:15.9};}

 this.target.lerp(this.focusTarget,Math.min(1,dt*4));this.radius+=(this.zoomTarget-this.radius)*Math.min(1,dt*5);const mobile=innerWidth<700?1.25:1;this.camera.position.set(this.target.x+Math.sin(this.angle)*this.radius*mobile,this.radius*Math.sin(this.elevation)*mobile,this.target.z+Math.cos(this.angle)*this.radius*mobile);this.camera.lookAt(this.target);
 this.near=null;let best=2.25;for(const o of this.interactables){const d=Math.hypot(o.approach.x-this.player.position.x,o.approach.z-this.player.position.z);if(d<best){best=d;this.near=o;}const p=o.pos.clone().project(this.camera);const visible=this.active&&!blocked&&(d<5||['desk','shelf','truck','phone'].includes(o.id)&&innerWidth>=700||o.id===Agency.MISSIONS[s.mission]?.target)&&p.z<1&&p.x>-1.05&&p.x<1.05&&p.y>-1&&p.y<1;o.el.hidden=!visible;o.el.style.left=(p.x*.5+.5)*innerWidth+'px';o.el.style.top=(-p.y*.5+.5)*innerHeight+'px';o.el.classList.toggle('target',o.id===Agency.MISSIONS[s.mission]?.target);o.el.classList.toggle('near',this.near===o);if(o.id==='truck')o.el.hidden=!visible||!!s.trip;if(o.id==='dialogue'){o.el.hidden=!visible||s.staff.driver<=[s.trip,...s.fleetTrips].filter(Boolean).length;if(this.near===o&&(s.staff.driver<=[s.trip,...s.fleetTrips].filter(Boolean).length))this.near=null;}}
 const prompt=document.getElementById('interaction');prompt.hidden=!this.active||blocked||!this.near;if(this.near)prompt.querySelector('span').textContent=s.carry&&this.near.id==='truck'?'تحميل الكراتين في العربية':this.near.label;
 const room=this.player.position.z>2?'ساحة التحميل':this.player.position.x<-3?'مكتب وكالة سعيد':'المخزن';if(room!==this.room){this.room=room;document.querySelector('#location b').textContent=room;document.querySelector('#location span').textContent='وكالة سعيد / دمياط'}
 this.updateEffects(dt,s);this.updateCity(dt,s);this.updateWarehouseWork(dt,s);this.updateModels(dt,s);this.updateEnvironment(dt,s);this.updateDetail(dt,s);this.updateStoryShot(dt,s);this.renderScene();
 }
}
Object.assign(AgencyWorld.prototype,materials,scene,warehouse,actors,picking,pathfinding,effects,city,models,environment,detail,narrativeWorld);
