import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation,MAP,PRODUCTS} from '../economy.js';
import {SUPPLY_CONTRACTS} from '../simulation/business.js';
import {warehouseFootprint,COMPANY_PLOTS} from '../site-layout.js';
const ready=()=>{const g=new Simulation();g.sign('محمد');g.inventory();g.repair();g.hire('driver');g.contract('bakery');g.s.money=500000;g.s.delivered=25;g.s.firstReward=true;g.s.story.enabled=false;g.change();g.rng=()=>.99;return g};
function load(g,o){g.s.stock.push({pid:o.pid,qty:o.qty,unit:g.cost(o.pid),expires:g.s.day+7});while(g.s.cargo.filter(b=>b.order===o.id).reduce((n,b)=>n+b.qty,0)<o.qty){assert(g.pack(o.id));assert(g.load())}}
function finish(g){let n=0;while(g.allTrips().length&&n++<4000){if(g.s.tripEvent)g.resolveTrip('repair');g.moveTrip(1)}assert.equal(g.allTrips().length,0)}
test('legacy six-client save extends city without changing money, stock or existing clients',()=>{const g=ready(),old=structuredClone(g.s);delete old.business;old.clients=old.clients.slice(0,6);old.customerCare=old.customerCare.slice(0,6);const n=new Simulation(old);assert.equal(n.s.clients.length,12);assert.equal(n.s.money,old.money);assert.deepEqual(n.s.stock,old.stock);assert.deepEqual(n.s.clients.slice(0,6),old.clients);assert.equal(MAP.width,1500);assert.equal(n.customerUnlocked(11),false);n.s.delivered=0;for(let i=0;i<30;i++)n.generateOrder();assert(n.s.orders.every(o=>o.client<6))});
test('periodic supply credits a real delivery once, persists, renews and cancel only stops future cycles',()=>{let g=ready();assert(g.signSupply('sham'));let r=g.s.business.contracts.sham,o=g.s.orders.find(o=>o.supply==='sham');assert.equal(o.qty,20);assert(!g.accept(o.id,5,'cash'));assert(g.accept(o.id,0,'cash'));load(g,o);assert(g.dispatch());finish(g);assert.equal(r.fulfilled,20);const v=g.s.invoices.find(v=>v.orderId===o.id);assert(v);assert.equal(g.orderJourney(o).step,6);assert(g.approve(v.id));assert.equal(g.orderJourney(o).step,7);g=new Simulation(Simulation.validate(g.s));g.rng=()=>.99;while(g.s.day<=g.s.business.contracts.sham.dueDay&&g.s.business.contracts.sham.successes===0)g.nextDay();r=g.s.business.contracts.sham;assert.equal(r.successes,1);assert.equal(r.cycle,2);assert.equal(r.fulfilled,0);assert(g.renewSupply('sham'));assert(r.active);const due=r.dueDay;while(g.s.day<=due)g.nextDay();assert(!r.active);assert.equal(r.misses,1);g.nextDay();assert.equal(r.misses,1);assert.doesNotThrow(()=>Simulation.validate(g.s))});
test('failed supply penalizes declared reputation and trust and reload cannot reset the cycle',()=>{const g=ready();assert(g.signSupply('sham'));g.s.event=null;g.s.nextEvent=9999;g.s.rep=60;g.s.clients[6].trust=60;g.nextDay();const rep=g.s.rep,trust=g.s.clients[6].trust;g.nextDay();assert.equal(g.s.business.contracts.sham.misses,1);assert.equal(g.s.rep,rep-3);assert.equal(g.s.clients[6].trust,trust-8);assert.equal(new Simulation(g.s).s.business.contracts.sham.cycle,2);assert(!g.signSupply('sham'));const malformed=structuredClone(g.s);malformed.business.contracts.sham.fulfilled=999;assert.throws(()=>Simulation.validate(malformed))});
test('five-vehicle fleet supports dry jumbo 120, five drivers, extra cost and correct reload capacity',()=>{const g=ready();for(let i=0;i<3;i++)assert(g.buyVehicle('normal'));assert(g.buyVehicle('jumbo'));assert.equal(g.s.vehicles.length,5);assert(!g.buyVehicle('normal'));for(let i=1;i<5;i++)assert(g.hire('driver'));assert(!g.hire('driver'));assert(g.chooseVehicle(5));assert.equal(g.vehicle.capacity,120);assert(!g.canCarry('milk'));assert(!g.convertVehicle('chilled'));const ids=[];for(let i=0;i<3;i++){const o={id:g.s.seq++,pid:'bread',client:0,qty:40,price:132,discount:0,payment:'cash',accepted:true,expires:99999,deadline:99999};g.s.orders.push(o);ids.push(o.id);assert(g.toggleLoadPlan(o.id));load(g,o)}assert.equal(g.s.cargo.reduce((n,b)=>n+b.qty,0),120);const money=g.s.money,f=g.loadForecast();assert.equal(f.qty,120);assert(g.dispatch());assert(Math.abs(money-g.s.money-f.cost)<.01);assert.equal(g.s.trip.yardHome,-30);assert.doesNotThrow(()=>Simulation.validate(g.s));finish(g);assert.equal(g.s.cargo.length,0);assert.equal(g.s.invoices.filter(v=>ids.includes(v.orderId)).length,3)});
test('load plans check capacity and cold needs; forecasts do not spend and priorities link real bottlenecks',()=>{const g=ready();const o={id:g.s.seq++,pid:'bread',client:0,qty:40,price:132,discount:0,payment:'cash',accepted:true,expires:99999,deadline:99999},b={...o,id:g.s.seq++,qty:30};g.s.orders.push(o,b);assert(g.toggleLoadPlan(o.id));assert(!g.toggleLoadPlan(b.id));const before=structuredClone(g.s);const f=g.loadForecast();assert.equal(f.shortages.bread,40);assert.equal(f.valid,true);assert.deepEqual(g.s,before);assert.equal(g.orderJourney(o).panel,'supplier');g.s.stock.push({pid:'bread',qty:40,unit:90,expires:7});assert.equal(g.orderJourney(o).panel,'shelf');assert(g.dayPriorities().some(x=>x.panel==='shelf'));assert(g.packPlanned());assert.equal(g.s.carry.order,o.id);assert.equal(g.orderJourney(o).step,3)});
test('customer choices are costed and cooldown protected; cash does not forgive invoices, trade deal once a day',()=>{const g=ready(),cash=g.s.money,trust=g.s.clients[0].trust;assert(g.visitBusiness(0,'service'));assert.equal(g.s.money,cash-350);assert.equal(g.s.clients[0].trust,trust+4);assert(!g.visitBusiness(0,'service'));g.s.day+=3;g.s.clients[0].outstanding=900;assert(g.visitBusiness(0,'cash'));assert.equal(g.s.clients[0].outstanding,900);assert.equal(g.s.clients[0].credit,0);assert(g.takeTradeDeal('cash'));assert(!g.takeTradeDeal('cash'));assert(!g.takeTradeDeal('volume'));assert.doesNotThrow(()=>Simulation.validate(g.s))});
test('warehouse expansions grow physical footprint on separate land without exceeding capacity cap',()=>{const g=ready();for(const cid of Object.keys(COMPANY_PLOTS)){const a=warehouseFootprint(cid,160),b=warehouseFootprint(cid,640);assert(b.w>a.w&&b.d>a.d);for(const other of Object.keys(COMPANY_PLOTS).filter(id=>id!==cid)){const c=warehouseFootprint(other,640);assert(Math.abs(b.x-c.x)>(b.w+c.w)/2+4||Math.abs(b.z-c.z)>(b.d+c.d)/2+4)}}g.s.warehouses.bakery.capacity=560;g.s.capacity=560;assert(g.upgrade('warehouse','bakery'));assert.equal(g.s.capacity,640);assert(!g.upgrade('warehouse','bakery'))});
test('five independent trips visit new city clients, survive reload and return with no cargo',()=>{let g=ready();g.s.delivered=100;g.s.regions.push('الدقهلية');g.s.ops.territories.bakery=['دمياط','الدقهلية'];for(let i=1;i<5;i++){assert(g.buyVehicle(i===4?'jumbo':'normal'));assert(g.hire('driver'))}for(let i=0;i<5;i++){assert(g.chooseVehicle(i+1));const o={id:g.s.seq++,pid:'bread',client:i+6,qty:20,price:132,discount:0,payment:i>=3?'credit':'cash',accepted:true,business:true,expires:99999,deadline:99999};g.s.orders.push(o);load(g,o);assert(g.dispatch());}assert.equal(g.allTrips().length,5);g=new Simulation(Simulation.validate(g.s));g.rng=()=>.99;finish(g);assert.equal(g.s.invoices.filter(v=>v.type==='sale').length,5);assert.equal(g.s.fleetTrips.length,0);assert.doesNotThrow(()=>Simulation.validate(g.s))});
