import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation,PRODUCTS} from '../economy.js';
import {neighborhoodLayout,overlaps} from '../world/neighborhood-layout.js';
function ready(){const sim=new Simulation();sim.sign('محمد');sim.inventory();sim.repair();sim.hire('driver');sim.contract('bakery');sim.s.money=100000;return sim}
function order(sim,qty=10,client=0){return {id:sim.s.seq++,client,pid:'bread',qty,price:132,discount:0,payment:'cash',accepted:true,expires:99999,deadline:99999}}
function deliver(sim,qty=10,client=0){const o=order(sim,qty,client),t={orders:[o],cargo:[{order:o.id,pid:'bread',qty,cost:qty*90,expires:8}],deliveredOrders:[]};sim.deliverOrder(o,t);return {o,t}}
test('v7 saves retain money, inventory and fleet and migrate optional progression',()=>{const a=ready();a.s.stock=[{pid:'bread',qty:12,unit:90,expires:5}];const old=structuredClone(a.s);delete old.development;const b=new Simulation(old);assert.equal(b.s.money,a.s.money);assert.deepEqual(b.s.stock,a.s.stock);assert.deepEqual(b.s.vehicles,a.s.vehicles);assert.equal(b.s.development.stage,0);assert.equal(b.s.development.equipment,'manual');for(const path of ['owned','branding','washedAt','districts']){const bad=structuredClone(b.s);bad.development[path]=[];assert.throws(()=>Simulation.validate(bad))}});
test('progression gates meaningful equipment; purchases are one-shot and stages never regress',()=>{const a=ready(),money=a.s.money;assert.equal(a.buyDevelopment('jack'),false);assert.equal(a.s.money,money);a.s.delivered=5;a.s.rep=55;a.change();assert.equal(a.s.development.stage,1);assert.equal(a.buyDevelopment('jack'),false);a.hire('worker');assert(a.buyDevelopment('jack'));const paid=a.s.money;assert.equal(a.buyDevelopment('jack'),false);assert.equal(a.s.money,paid);a.s.rep=20;a.change();assert.equal(a.s.development.stage,1);assert.equal(a.buyDevelopment('forklift'),false);a.s.delivered=35;a.s.rep=75;a.change();assert(a.buyDevelopment('forklift'));assert.equal(a.s.development.equipment,'forklift');assert.doesNotThrow(()=>Simulation.validate(a.s))});
test('equipment speeds the real worker job without creating stock, and cannot switch mid-job',()=>{const a=ready();a.s.delivered=35;a.s.rep=75;a.change();a.hire('worker');a.buyDevelopment('jack');a.buyDevelopment('forklift');a.s.stock=[{pid:'bread',qty:30,unit:90,expires:5}];const o=order(a);a.s.orders.push(o);const manual=new Simulation(a.s);manual.selectEquipment('manual');assert(manual.pack(o.id));assert(a.pack(o.id));assert(a.s.pickingJob.duration<manual.s.pickingJob.duration);assert.equal(a.s.pickingJob.batch.qty,manual.s.pickingJob.batch.qty);assert.equal(a.selectEquipment('manual'),false);assert.equal(a.s.stock.reduce((n,b)=>n+b.qty,0),20);assert.doesNotThrow(()=>Simulation.validate(a.s))});
test('district order saves correctly, success rewards only actual delivery and exactly once',()=>{const a=ready();a.s.orders=[];a.s.delivered=5;a.s.rep=60;a.change();assert(a.startDistrict(0));assert(a.requestDistrictOrder(0));assert.doesNotThrow(()=>Simulation.validate(a.s));assert.equal(a.requestDistrictOrder(0),false);deliver(a,20);assert.equal(a.s.development.districts[0].done,20);const before=a.s.money,{o,t}=deliver(a,20);assert.equal(a.s.money,before+650);assert(a.s.development.districts[0].rewarded);a.deliverOrder(o,t);assert.equal(a.s.money,before+650);const failed=ready();failed.s.delivered=5;failed.change();failed.startDistrict(0);const empty=order(failed,20);failed.deliverOrder(empty,{orders:[empty],cargo:[],deliveredOrders:[]});assert.equal(failed.s.development.districts[0].done,0)});
test('branding respects signed contracts, washing costs once per distance and preserves mechanics',()=>{const a=ready();assert.equal(a.brandVehicle(1,'dairy'),false);assert(a.brandVehicle(1,'bakery'));a.s.delivered=15;a.s.rep=60;a.change();assert(a.buyDevelopment('wash'));a.mechanical(1).km=12;a.mechanical(1).tires=74;const cash=a.s.money;assert(a.washVehicle(1));assert.equal(a.s.money,cash-80);assert.equal(a.mechanical(1).tires,74);assert.equal(a.washVehicle(1),false);assert.doesNotThrow(()=>Simulation.validate(a.s))});
test('dispatch upgrade shortens handling but preserves receiving-window waiting and boarding',()=>{const a=ready(),o=order(a),cargo=[{order:o.id,pid:'bread',qty:10,cost:900,expires:4}];const before=a.buildTrip([o],cargo);a.s.development.owned.dispatch=true;const after=a.buildTrip([o],cargo);assert(after.total<before.total);assert.equal(after.legs[0].boarding,3);assert(after.legs[0].hold>=3);assert.equal(after.total,after.legs.reduce((n,l)=>n+l.duration,0));});
test('all customer plots and homes are clear of permanent streets and each other',()=>{const layout=neighborhoodLayout();assert.equal(layout.shops.length,12);assert(layout.plots.length>=15);for(const b of layout.plots){for(const r of layout.streets)assert(!overlaps(b,r,.74),'building overlaps road');for(const other of layout.plots)if(b!==other)assert(!overlaps(b,other,.99),'buildings overlap')}for(const p of layout.clients)assert(layout.streets.some(r=>Math.abs(p.x-r.x)<=r.w/2&&Math.abs(p.z-r.z)<=r.d/2),'client not reached by street');for(const r of layout.streets)assert(layout.streets.some(other=>r!==other&&overlaps(r,other)), 'disconnected road')});
test('new agencies automatically brand available suitable trucks while preserving manual choices',()=>{const a=ready();assert.equal(a.s.development.branding[1],'bakery');a.s.vehicles.push({id:2,kind:'chilled',condition:100,capacity:60});a.s.truckCount=2;a.s.contracts.dairy=true;a.s.cycles.dairy={startDay:1,endDay:8,target:22000,successes:0,misses:0};a.change();assert.equal(a.s.development.branding[2],'dairy');assert.equal(a.s.development.branding[1],'bakery');assert(a.brandVehicle(2,'agency'));a.change();assert.equal(a.s.development.branding[2],'agency');const b=new Simulation(a.s);assert.equal(b.s.development.branding[2],'agency');assert.equal(b.s.vehicles[0].kind,'normal');});
test('automatic branding waits for a truck to return and never assigns dairy to a dry truck',()=>{const a=ready();a.s.vehicles.push({id:2,kind:'normal',condition:100,capacity:60});a.s.truckCount=2;a.s.contracts.dairy=true;a.change();assert.equal(a.s.development.branding[2],undefined);a.s.vehicles[1].kind='chilled';const o=order(a);const t=a.buildTrip([o],[{pid:'bread',qty:10,order:o.id,cost:900,expires:4}]);t.vehicleId=2;a.s.fleetTrips=[t];a.change();assert.equal(a.s.development.branding[2],undefined);a.s.fleetTrips=[];a.change();assert.equal(a.s.development.branding[2],'dairy')});
