import assert from 'node:assert/strict';
import test from 'node:test';
import {Simulation,routePosition,MAP} from '../economy.js';
import {SaveSlots} from '../save-slots.js';
const tick=(g,n)=>{for(let i=0;i<n;i++)g.tick(1)};
function setup(){let g=new Simulation();g.rng=()=>.5;assert(g.sign('محمد'));assert(g.inventory());assert(g.repair());assert(g.hire('driver'));assert(g.contract('bakery'));return g}
function load(g){const o=g.s.orders[0];assert(g.accept(o.id));assert(g.buy(o.pid,o.qty));tick(g,9);g.receive(g.s.incoming[0].id);while(g.s.cargo.reduce((a,b)=>a+b.qty,0)<o.qty){assert(g.pack(o.id));assert(g.load())}return o}
test('orders every 10 seconds while carrying and driving; unloading clears cargo before return',()=>{const g=setup(),o=load(g);const n=g.s.orders.length;tick(g,20);assert(g.s.orders.length>=n+2);assert(g.dispatch());const t=g.s.trip;assert.deepEqual(routePosition(t),{x:MAP.depot.x,y:MAP.depot.y});tick(g,10);assert(g.s.orders.length>=2);let guard=0;while(g.s.trip&&!g.s.trip.returning&&guard++<500)g.tick(1);assert(g.s.trip?.returning);assert.equal(g.s.trip.cargo.length,0);assert(g.s.invoices.some(v=>v.type==='sale'));const cash=g.s.money;const v=g.s.invoices.find(v=>v.type==='sale');assert(g.approve(v.id));assert(g.s.money>cash);const paid=g.s.money;assert.equal(g.approve(v.id),false);assert.equal(g.s.money,paid);tick(g,80);assert.equal(g.s.trip,null);assert.equal(g.s.delivered,1);assert.equal(g.dispatch(),false);assert.equal(o.qty,10)});
test('12 percent immediate; 2 percent conditional rebate once per period',()=>{const g=setup();assert.equal(g.cost('bread'),116.16);g.s.money=100000;assert(g.buy('bread',100));assert.equal(g.s.incoming[0].gross,13200);tick(g,9);g.receive(g.s.incoming[0].id);assert.equal(g.s.purchases.bakery,13200);assert.equal(g.s.netPurchases.bakery,11616);g.s.day=g.s.cycles.bakery.endDay;const before=g.s.money;g.settleCycles();assert.equal(g.s.money,before+264);g.settleCycles();assert.equal(g.s.money,before+264);assert.equal(g.s.successfulCycles,1);});
test('agency gates, warehouse and actual chilled vehicle required',()=>{const g=setup();g.s.money=100000;assert.equal(g.contract('dairy'),false);g.s.delivered=8;g.s.rep=60;g.s.successfulCycles=1;assert(g.setupWarehouse('dairy'));assert(g.upgrade('cooling'));assert.equal(g.contract('dairy'),false);assert(g.convertVehicle('chilled'));assert(g.contract('dairy'));assert(g.canCarry('milk'));assert.equal(g.contract('frozen'),false)});
test('trip decision pauses truck only, repair costs exactly once',()=>{const g=setup();load(g);g.dispatch();g.s.tripEvent={kind:'breakdown'};const before=g.s.trip.remaining,n=g.s.orders.length;tick(g,20);assert.equal(g.s.trip.remaining,before);assert(g.s.orders.length>=n+2);const cash=g.s.money;assert(g.resolveTrip('repair'));assert.equal(g.s.money,cash-500);assert.equal(g.resolveTrip('repair'),false);tick(g,3);assert.equal(g.s.trip.remaining,before);g.tick(1);assert(g.s.trip.remaining<before)});
test('weather, interest, bankruptcy, save validation and slot isolation',()=>{const g=setup();g.s.money=30000;assert(g.borrow());g.s.day=6;g.nextDay();assert(g.s.ledger.some(l=>l.text.includes('فائدة')&&l.amount===-100));g.s.money=-50000;g.nextDay();g.nextDay();g.nextDay();assert(g.s.bankrupt);const elapsed=g.s.elapsed;g.tick(10);assert.equal(g.s.elapsed,elapsed);const round=Simulation.validate(JSON.parse(JSON.stringify(g.s)));assert.deepEqual(round,g.s);assert.throws(()=>Simulation.validate({...g.s,market:Infinity}));assert.throws(()=>Simulation.validate({...g.s,truckCount:100000}));const store=new Map(),storage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};const slots=new SaveSlots(storage);slots.save(g.s);slots.select('2');assert.equal(slots.load(),null);slots.save({day:1});slots.select('1');assert.equal(slots.load().day,g.s.day)});
test('rain trip takes 20 percent longer drive legs; returned cash cannot duplicate quest reward',()=>{const g=setup(),o=load(g);const dry=g.buildTrip([o],g.s.cargo);g.s.weather='rain';const wet=g.buildTrip([o],g.s.cargo);assert.equal(wet.legs[0].duration,dry.legs[0].duration*1.2);g.talk();g.s.delivered+=5;g.s.firstReward=true;const cash=g.s.money;g.talk();assert.equal(g.s.money,cash+750);g.talk();assert.equal(g.s.money,cash+750)});
test('rejected delivery returns real stock; alternate customer uses new route with no duplicate invoices',()=>{
 for(const choice of ['return','discount']){const g=setup();load(g);g.dispatch();while(g.s.trip.legs[g.s.trip.legIndex].kind!=='unload')g.tick(1);const original=g.s.trip.orders[0].client;g.s.tripEvent={kind:'rejection'};assert(g.resolveTrip(choice));if(choice==='discount')assert.notEqual(g.s.trip.orders[0].client,original);tick(g,200);assert.equal(g.s.trip,null);if(choice==='return'){assert.equal(g.qty('bread'),10);assert.equal(g.s.invoices.filter(v=>v.type==='sale').length,0)}else{assert.equal(g.qty('bread'),0);assert.equal(g.s.invoices.filter(v=>v.type==='sale').length,1);assert.equal(g.s.invoices.find(v=>v.type==='sale').expected,660)}assert.doesNotThrow(()=>Simulation.validate(g.s))}
});
test('challenge ends after 7 days; endless does not stop on story completion',()=>{const g=new Simulation();assert(g.setMode('challenge'));g.sign('تحدي');for(let i=0;i<7;i++)g.nextDay();assert.equal(typeof g.s.challenge.result,'number');const elapsed=g.s.elapsed;g.tick(10);assert.equal(g.s.elapsed,elapsed);g.setMode('endless');g.tick(10);assert.equal(g.s.elapsed,elapsed+10)});
test('v4 without optional feature fields migrates; malformed route cannot pass validation',()=>{const g=setup();const old=structuredClone(g.s);for(const k of ['weather','market','team','mode','bankPrincipal','negativeDays','bankrupt','season','networkReceived','networkOutbox','tripEvent','tripDelay','rivalShare','advert','enterprise','quest','questDone','auction','challenge'])delete old[k];assert.equal(Simulation.validate(old).weather,'clear');load(g);g.dispatch();const bad=structuredClone(g.s);bad.trip.legs[0].points[0].x=Infinity;assert.throws(()=>Simulation.validate(bad))});
test('original v3 in-flight save migrates without lost cargo or cash',async()=>{const {readFile}=await import('node:fs/promises');const old=JSON.parse(await readFile(new URL('./fixtures/v3-trip.json',import.meta.url),'utf8'));const g=new Simulation(old);g.rng=()=>.5;assert.equal(g.s.money,old.money);assert.equal(g.s.trip.cargo.reduce((n,b)=>n+b.qty,0),10);assert.equal(g.s.version,4);assert(g.s.contracts.bakery);tick(g,200);assert.equal(g.s.trip,null);assert.equal(g.s.invoices.filter(v=>v.type==='sale').length,1);assert.doesNotThrow(()=>Simulation.validate(g.s))});
