import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation,DAY_SECONDS} from '../economy.js';
function setup(){const g=new Simulation();g.rng=()=>.5;g.sign('محمد');g.inventory();g.repair();g.hire('driver');g.contract('bakery');return g}
const tick=(g,n)=>{for(let i=0;i<n;i++)g.tick(1)};
function load(g,client=0){g.generateOrder(true);const o=g.s.orders.find(o=>!o.accepted);o.client=client;assert(g.accept(o.id));g.s.stock.push({id:g.s.seq++,pid:o.pid,qty:o.qty,unit:100,expires:g.s.day+4});assert(g.pack(o.id));assert(g.load());return o}
test('two simultaneous trucks keep independent cargo, events and invoices across save/reload',()=>{
 let g=setup();g.s.money=100000;load(g);assert(g.dispatch());assert(g.buyVehicle('normal'));assert(g.hire('driver'));assert(g.chooseVehicle(2));assert.equal(g.s.trip,null);load(g,1);assert(g.dispatch());assert.equal(g.allTrips().length,2);const selected=g.s.selectedVehicle;g.s.tripEvent={kind:'breakdown'};const blocked=g.s.trip.remaining,other=g.s.fleetTrips[0].remaining;tick(g,5);assert.equal(g.s.selectedVehicle,selected);assert.equal(g.s.trip.remaining,blocked);assert(g.s.fleetTrips[0].remaining<other);
 g=new Simulation(JSON.parse(JSON.stringify(g.s)));g.rng=()=>.5;assert.equal(g.allTrips().length,2);assert(g.resolveTrip('wait'));tick(g,160);assert.equal(g.allTrips().length,0);assert.equal(g.s.invoices.filter(v=>v.type==='sale').length,2);assert.equal(g.reservedStorage,0);assert.doesNotThrow(()=>Simulation.validate(g.s));
});
test('held loads survive switching and prevent duplicate reservation of an order',()=>{const g=setup();g.s.money=100000;const o=load(g);g.buyVehicle('normal');g.chooseVehicle(2);g.s.stock.push({pid:'bread',qty:20,unit:100,expires:4});assert.equal(g.pack(o.id),false);assert.equal(g.reservedStorage,10);g.chooseVehicle(1);assert.equal(g.s.cargo[0].order,o.id);assert.equal(g.reservedStorage,10)});
test('partial receipts sum to the invoice exactly; credit in transit counts toward limit',()=>{const g=setup();load(g);g.dispatch();tick(g,100);const v=g.s.invoices.find(v=>v.type==='sale'),cash=g.s.money;assert(g.collect(v.id,300));assert.equal(g.s.delivered,0);assert.equal(g.s.clients[v.client].outstanding,v.amount-300);assert(g.collect(v.id,v.amount-300));assert.equal(g.s.money,cash+v.amount+3000);assert.equal(g.s.delivered,1);assert.equal(g.collect(v.id,1),false);assert.equal(g.s.clients[v.client].outstanding,0);assert.equal(g.s.collectionReceipts.reduce((n,r)=>n+r.amount,0),v.amount)});
test('worker receipt and picking jobs reserve real stock and finish before dispatch',()=>{
 const g=setup();g.s.delivered=1;g.s.firstReward=true;assert(g.hire('worker'));const o=g.s.orders[0];g.accept(o.id);g.buy('bread',10);tick(g,9);assert(g.receive(g.s.incoming[0].id));assert.equal(g.qty('bread'),0);assert(g.s.workerJob);tick(g,8);assert.equal(g.qty('bread'),10);assert(g.pack(o.id));assert(g.s.pickingJob);assert.equal(g.s.carry,null);assert.equal(g.reservedStorage,10);assert.equal(g.dispatch(),false);const restored=new Simulation(JSON.parse(JSON.stringify(g.s)));restored.rng=()=>.5;tick(restored,30);assert.equal(restored.s.carry.qty,10);assert(restored.load());assert(restored.dispatch());
});
test('representatives finish a real itinerary and report customer visits',()=>{const g=setup();g.s.delivered=3;g.s.firstReward=true;g.hire('rep');assert(g.assignRep(0,'دمياط','sales'));const first={...g.s.repRoutes[0]};tick(g,10);assert(g.s.repRoutes[0].elapsed>first.elapsed);assert.doesNotThrow(()=>Simulation.validate(g.s));tick(g,160);assert.equal(g.s.repRoutes.length,0);assert(g.s.repReports.length>=3);assert(g.s.orders.some(o=>o.repAssigned===1))});
test('supplier terms postpone cash once; inspector warnings preserve inventory and allow correction',()=>{const g=setup();g.s.cycles.bakery.successes=1;g.relation('bakery').score=75;assert(g.negotiate('bakery','credit'));g.requestTerms('bakery',true);const cash=g.s.money;assert(g.buy('bread',10));assert.equal(g.s.money,cash);assert.equal(g.s.supplierBills[0].amount,1161.6);assert(g.paySupplier(g.s.supplierBills[0].id));assert.equal(g.s.money,cash-1161.6);assert.equal(g.paySupplier(g.s.supplierBills[0].id),false);g.relation('bakery').suspended=true;assert.equal(g.buy('bread',1),false);assert(g.enabled('bread'));assert.doesNotThrow(()=>Simulation.validate(g.s))});
test('day is three times longer, configurable without slowing orders; old saves retain time of day',()=>{assert.equal(DAY_SECONDS,900);const g=setup();tick(g,300);assert.equal(g.s.day,1);assert.equal(g.s.time,300);g.s.dayLength=1800;tick(g,100);assert.equal(g.s.time,350);assert(g.s.orders.length>0);const old=JSON.parse(JSON.stringify(g.s));delete old.expansion;delete old.dayLength;old.time=150;const restored=new Simulation(old);assert.equal(restored.s.time,450);assert.equal(restored.s.dayLength,900)});
test('warehouse return quarantine reserves capacity, inspection releases a batch exactly once',()=>{const g=setup();g.s.money=100000;g.buyFacility('returnsZone');load(g);g.dispatch();while(g.s.trip.legs[g.s.trip.legIndex].kind!=='unload')g.tick(1);g.s.tripEvent={kind:'rejection'};g.resolveTrip('return');tick(g,100);assert.equal(g.qty('bread'),0);assert.equal(g.s.returnQuarantine[0].qty,10);assert.equal(g.reservedStorage,10);const id=g.s.returnQuarantine[0].id;assert(g.inspectReturn(id));assert.equal(g.qty('bread'),10);assert.equal(g.inspectReturn(id),false)});
test('malformed fleet, layouts and picking jobs fail validation',()=>{const g=setup();for(const change of [s=>s.warehousePlan.slots.bakery=99,s=>s.fleetTrips=[{vehicleId:999}],s=>s.pickingJob={elapsed:0,duration:Infinity},s=>s.dayLength=0,s=>s.customerCare[0].creditLimit=-1]){const bad=structuredClone(g.s);change(bad);assert.throws(()=>Simulation.validate(bad))}});
