import test from 'node:test';import assert from 'node:assert/strict';import {Simulation} from '../economy.js';
const tick=(g,n)=>{for(let i=0;i<n;i++)g.tick(1)};
function setup(){const g=new Simulation();g.rng=()=>.8;g.sign('محمد');g.inventory();g.repair();g.hire('driver');g.contract('bakery');g.s.money=200000;g.s.firstReward=true;return g}
function stock(g,pid,qty){g.s.stock.push({pid,qty,unit:100,expires:g.s.day+5})}
function order(g,extra={}){const o={id:g.s.seq++,client:0,pid:'bread',qty:20,price:132,accepted:false,payment:'cash',discount:0,expires:g.s.elapsed+900,first:false,business:true,...extra};g.s.orders.push(o);return o}
test('composite orders accept atomically, require all lines or explicit partial consent',()=>{const g=setup();g.s.orders=[];const a=order(g),b=order(g,{pid:'pastry',qty:10,price:207});a.bundle=b.bundle=a.id;assert(g.accept(a.id));assert(b.accepted);stock(g,'bread',20);g.pack(a.id);g.load();g.pack(a.id);g.load();assert.equal(g.dispatch(),false);assert(g.partialConsent(a.id));assert(g.dispatch());assert(g.s.orders.some(o=>o.id===b.id));tick(g,120);assert.equal(g.s.invoices.filter(v=>v.type==='sale')[0].qty,20);assert.doesNotThrow(()=>Simulation.validate(g.s))});
test('partial line creates only its unpaid remainder and invoices delivered quantity',()=>{const g=setup();g.s.orders=[];const a=order(g);g.accept(a.id);stock(g,'bread',10);g.pack(a.id);g.load();g.partialConsent(a.id);assert(g.dispatch());assert.equal(g.s.orders[0].qty,10);assert.notEqual(g.s.orders[0].id,a.id);tick(g,120);assert.equal(g.s.invoices.find(v=>v.type==='sale').amount,1320)});
test('customer payment requirements and extra deadline are explicit and one-shot',()=>{const g=setup();g.s.orders=[];const a=order(g);assert.equal(g.accept(a.id,0,'credit'),false);assert(g.accept(a.id));const deadline=a.deadline;assert(g.extendOrder(a.id));assert.equal(a.deadline,deadline+180);assert.equal(g.extendOrder(a.id),false);g.s.regions.push('الدقهلية');g.s.ops.territories.bakery=['دمياط','الدقهلية'];g.s.clients[3].trust=60;const chain=order(g,{client:3,qty:10});assert.equal(g.accept(chain.id),false);assert(g.accept(chain.id,0,'credit'));assert.equal(g.partialConsent(chain.id),false)});
test('company territorial permit requires performance, reputation and a representative',()=>{const g=setup();g.s.regions.push('الدقهلية');assert.equal(g.authorizeArea('bakery'),false);g.s.delivered=3;g.hire('rep');g.s.rep=60;g.s.cycles.bakery.successes=1;assert(g.authorizeArea('bakery'));const money=g.s.money;assert.equal(g.authorizeArea('bakery'),false);assert.equal(g.s.money,money);assert(g.territories('bakery').includes('الدقهلية'))});
test('representative inventory and collected cash remain in custody until one settlement',()=>{let g=setup();g.s.delivered=3;g.hire('rep');stock(g,'bread',10);const money=g.s.money;assert(g.giveCustody(0,'bread',10));assert.equal(g.qty('bread'),0);assert.equal(g.reservedStorage,10);g.assignRep(0,'دمياط','sales');tick(g,30);assert(g.custody(0).cash>0);assert.equal(g.s.money,money);assert.equal(g.settleCustody(0),false);g=new Simulation(JSON.parse(JSON.stringify(g.s)));g.rng=()=>.8;tick(g,150);const held=g.custody(0).cash;assert(g.settleCustody(0));assert.equal(g.s.money,money+held);assert.equal(g.settleCustody(0),false);assert.doesNotThrow(()=>Simulation.validate(g.s))});
test('maintenance follows travelled kilometres and service locks a vehicle until completion',()=>{const g=setup();const o=g.s.orders[0];g.accept(o.id);stock(g,'bread',10);g.pack(o.id);g.load();g.dispatch();tick(g,10);assert.equal(g.serviceVehicle(1,'oil'),false);tick(g,120);assert(g.mechanical(1).km>0);assert(g.mechanical(1).oil<100);assert(g.serviceVehicle(1,'oil'));assert.equal(g.dispatch(),false);g.s.ops.services[0].until=g.s.elapsed+2;tick(g,3);assert.equal(g.mechanical(1).oil,100);assert.equal(g.s.ops.services.length,0)});
test('cold exposure warns before waste, respects backup power and never invoices spoiled cargo',()=>{const g=setup();g.s.cooling=true;stock(g,'milk',10);g.s.ops.cold.dairy=30;g.s.ops.powerUntil=1000;g.tickCold(50);assert.equal(g.qty('milk'),10);assert(g.s.ops.warnings.dairyheat);g.tickCold(140);assert.equal(g.qty('milk'),9);const before=g.s.expenses;g.s.ops.generator=true;g.s.ops.cold.dairy=4;g.tickCold(180);assert.equal(g.qty('milk'),9);assert.equal(g.s.expenses,before);const o=order(g,{pid:'milk',qty:1,accepted:true,deadline:999}),t={orders:[o],cargo:[],deliveredOrders:[]};g.deliverOrder(o,t);assert(!g.s.invoices.some(v=>v.type==='sale'&&v.pid==='milk'))});
test('route forecast uses actual load and includes customer receiving windows',()=>{const g=setup();g.s.orders=[];g.s.customerCare[0].type='super';g.s.time=600;const o=order(g,{qty:10});g.accept(o.id);stock(g,'bread',10);g.pack(o.id);g.load();assert(g.planRoute('windows'));const forecast=g.routeForecast();assert.equal(forecast.qty,10);assert.equal(forecast.stops.length,1);const t=g.buildTrip([o],g.s.cargo);assert(t.legs.some(l=>l.windowWait>0));assert.equal(t.legs[0].yard,'out');assert.equal(t.legs.at(-1).yard,'in')});
test('limited offer rewards once and failure applies its declared penalty once',()=>{const g=setup();g.s.delivered=5;g.nextDay();const f=g.s.ops.offers[0];assert(f);assert(g.acceptOffer(f.id));for(const o of g.s.orders.filter(o=>o.special===f.id)){const t={orders:[o],cargo:[{pid:o.pid,order:o.id,qty:o.qty,cost:100,expires:9}],deliveredOrders:[]};g.deliverOrder(o,t);g.deliverOrder(o,t)}assert.equal(f.status,'won');assert.equal(f.done,f.qty);g.nextDay();const failed=g.s.ops.offers.find(o=>o.status==='open');g.acceptOffer(failed.id);while(g.s.day<=failed.dueDay)g.nextDay();assert.equal(failed.status,'failed');const penalties=g.s.ops.history.filter(h=>h.text.includes('غرامة'));g.nextDay();assert.equal(g.s.ops.history.filter(h=>h.text.includes('غرامة')).length,penalties.length)});
test('remembered assistance produces referral and daily report reconciles accounting deltas',()=>{const g=setup();const initial={money:g.s.money,revenue:g.s.revenue,cogs:g.s.cogs,expenses:g.s.expenses};g.s.ops.dayStart=initial;assert(g.helpClient(0));assert.equal(g.helpClient(0),false);g.nextDay();const d=g.s.ops.daily[0];assert.equal(d.profit,d.revenue-d.cogs-d.expenses);assert.equal(d.cash,g.s.money-initial.money);g.nextDay();assert.equal(g.s.ops.referrals.length,1);g.nextDay();assert.equal(g.s.ops.referrals.length,1)});
test('v6 save migration preserves fleet and money; malformed new operating state is rejected',()=>{const g=setup();const old=structuredClone(g.s);delete old.ops;const upgraded=Simulation.validate(old);assert.equal(upgraded.money,g.s.money);assert.deepEqual(upgraded.vehicles,g.s.vehicles);for(const mutate of [s=>s.ops.cold.dairy=Infinity,s=>s.ops.maintenance[1]={km:-1},s=>s.ops.custody[9]={},s=>s.ops.territories.bakery=['غير موجود']]){const bad=structuredClone(g.s);mutate(bad);assert.throws(()=>Simulation.validate(bad))}});
test('rerouting from a customer never teleports the truck through the garage departure',()=>{const g=setup();const o=order(g,{client:2});const current={x:235,y:100},t=g.buildTrip([o],[], 'safe',current);assert.notEqual(t.legs[0].yard,'out');assert.deepEqual(t.legs[0].points[0],current);assert.equal(t.legs.at(-1).yard,'in')});
