import test from 'node:test';import assert from 'node:assert/strict';
import {PanelHistory} from '../panel-history.js';import {installMenuUI,menuMatches,invoiceStatus,MENU_GROUPS} from '../menu-ui.js';import {Simulation} from '../economy.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fixture(){const g=new Simulation();g.rng=()=>.5;const panels=Object.fromEntries(['desk','company','supplier','receiving','phone','accounts','shelf'].map(id=>[id,()=>['قسم','عنوان','المحتوى القديم']]));const btn=(text,action,extra='',disabled=false)=>'<button data-action="'+action+'" '+extra+(disabled?' disabled':'')+'>'+text+'</button>';const menu=installMenuUI({panels,getSim:()=>g,btn,row:(a,b)=>'<div>'+a+' '+b+'</div>',go:()=>'',note:x=>x,empty:x=>x,num:x=>String(Math.round(x)),egp:x=>x+' ج',esc});return {g,menu,panels}}
test('navigation returns through prior screens without closing, preserves payloads and bounds history',()=>{const h=new PanelHistory();h.visit(null,'accounts',true);assert.equal(h.back().id,'tablet');assert.equal(h.back(),null);const old={id:'supplier',scroll:740,values:[{id:'qty-bread',value:'30'}],details:[true]};h.visit(old,'receiving',true);assert.deepEqual(h.back(),old);h.visit(old,'supplier',true);assert.equal(h.canBack,false);for(let i=0;i<50;i++)h.visit({id:'p'+i},'next',true);assert.equal(h.entries.length,30);h.clear();assert.equal(h.canBack,false);h.visit(null,'settings',false);assert.equal(h.canBack,false)});
test('Arabic search ignores diacritics and alef forms; filters combine with search',()=>{assert(menuMatches('مَزارع نُور الألبان','dairy','الالبان','dairy'));assert(!menuMatches('مزارع نور الألبان','dairy','الالبان','bakery'));assert(menuMatches('عميل علي','accepted short','على','short'));assert(!menuMatches('طلب خبز','new','لبن','all'))});
test('invoice filters prioritize differences, distinguish future credit and closed records',()=>{const v={type:'sale',amount:100,expected:100,due:4,settled:false};assert.equal(invoiceStatus(v,3),'future');assert.equal(invoiceStatus(v,4),'due');assert.equal(invoiceStatus({...v,amount:110},3),'difference');assert.equal(invoiceStatus({...v,type:'purchase'},4),'review');assert.equal(invoiceStatus({...v,settled:true},4),'settled')});
test('catalogue uses real stock and cost; all products get artwork and order fields retain original actions',()=>{const {g,panels}=fixture();g.sign('تاجر');g.inventory();g.repair();g.hire('driver');g.contract('bakery');const catalog=panels.supplier()[2];assert(catalog.includes('data-menu-total="bread"'));assert(catalog.includes('qty-bread'));assert(catalog.includes('data-action="buy"'));assert(catalog.includes('data:image/svg+xml'));const orders=panels.phone()[2],o=g.s.orders[0];assert(orders.includes('discount-'+o.id));assert(orders.includes('payment-'+o.id));assert(orders.includes('data-action="accept"'));assert(orders.includes('data-action="reject"'));assert(!orders.includes('undefined'));const before=JSON.stringify(g.s);panels.supplier();panels.phone();panels.accounts();assert.equal(JSON.stringify(g.s),before)});
test('filters show empty state and clearing restores records; subtotal follows quantity validation',()=>{const {menu}=fixture();const records=[{dataset:{search:'خبز',tags:'bakery'}},{dataset:{search:'لبن',tags:'dairy'}}],counter={},zero={},search={},total={};const container={querySelectorAll:selector=>selector==='[data-menu-toolbar]'?[{dataset:{menuToolbar:'catalog'}}]:selector==='[data-menu-list="catalog"]'?records:[],querySelector:selector=>selector.includes('count')?counter:selector.includes('empty')?zero:selector.includes('search')?search:total};menu.input({dataset:{menuSearch:'catalog'},value:'لبن'},container);assert(records[0].hidden);assert(!records[1].hidden);assert.equal(counter.textContent,'1 من 2');menu.handle({dataset:{action:'menuFilter',list:'catalog',filter:'bakery'}});menu.mount(container);assert.equal(zero.hidden,false);menu.handle({dataset:{action:'menuClear',list:'catalog'}});menu.mount(container);assert(records.every(r=>!r.hidden));assert.equal(search.value,'');menu.quantity({dataset:{menuQuantity:'bread',unit:'88'},value:'30'},container);assert.equal(total.textContent,'2640 ج');menu.quantity({dataset:{menuQuantity:'bread',unit:'88'},value:'-5'},container);assert(total.textContent.includes('أدخل كمية'))});
test('all core requested sections are reachable from the tablet navigation',()=>{const ids=MENU_GROUPS.flatMap(x=>x[2].map(y=>y[0]));for(const id of ['desk','company','supplier','phone','accounts','shelf','truck','fleet','garage','staff','receiving'])assert(ids.includes(id))});
test('invoice cards use remaining amounts and disable approval of mismatches',()=>{const {g,panels}=fixture();g.s.invoices=[{id:101,type:'sale',client:0,pid:'bread',qty:10,day:1,due:1,expected:1000,amount:1000,paid:250,settled:false},{id:102,type:'sale',client:1,pid:'bread',qty:10,day:1,due:3,expected:1000,amount:1100,settled:false}];const html=panels.accounts()[2];assert(html.includes('750 ج'));assert(html.includes('data-id="102" disabled'));assert(html.includes('data-tags="difference open"'));assert(html.includes('data-tags="due open"'));assert(!html.includes('undefined'));assert(!html.includes('NaN'))});
