import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto,createHash} from 'node:crypto';
import {registerPWA} from '../pwa.js';
const settle=()=>new Promise(resolve=>setImmediate(resolve));
function browser(){const handlers={},timers=[],order=[],reg={async update(){order.push('check')}};const env={window:{addEventListener:(name,fn)=>handlers[name]=fn},document:{hidden:false,addEventListener:(name,fn)=>handlers[name]=fn},navigator:{onLine:true,serviceWorker:{addEventListener:(name,fn)=>handlers[name]=fn,async register(url,opts){assert.equal(opts.updateViaCache,'none');return reg}}},location:{protocol:'https:',reload(){order.push('reload')}},setInterval(fn,ms){timers.push(fn);assert.equal(ms,60000)},clearInterval(){},setTimeout(fn){timers.push(fn);return timers.length},clearTimeout(){}};return{env,handlers,timers,order}}
test('update saves before a single reload, checks periodically and bypasses HTTP worker cache',async()=>{const b=browser();await registerPWA({beforeReload:()=>{b.order.push('save');return true}},b.env);b.handlers.controllerchange();b.handlers.controllerchange();await settle();assert.deepEqual(b.order,['check','save','reload']);b.handlers.pageshow();await settle();assert.equal(b.order.filter(x=>x==='reload').length,1);assert(b.timers.length)});
test('updates defer during editing, offline checks and failed saves, then retry safely',async()=>{const b=browser();let busy=true,saved=false;await registerPWA({canReload:()=>!busy,beforeReload:()=>saved},b.env);b.handlers.controllerchange();await settle();assert(!b.order.includes('reload'));busy=false;await b.timers.at(-1)();assert(!b.order.includes('reload'));saved=true;await b.timers.at(-1)();assert(b.order.includes('reload'));b.env.navigator.onLine=false;const checks=b.order.filter(x=>x==='check').length;await b.handlers.online();assert.equal(b.order.filter(x=>x==='check').length,checks)});
test('hidden tabs defer reload until foreground and local-file play does not register a worker',async()=>{const b=browser();await registerPWA({},b.env);b.env.document.hidden=true;b.handlers.controllerchange();await settle();assert(!b.order.includes('reload'));b.env.document.hidden=false;b.handlers.visibilitychange();await settle();assert(b.order.includes('reload'));const f=browser();f.env.location.protocol='file:';await registerPWA({},f.env);assert.equal(f.order.length,0)});
function worker(corrupt=false){const handlers={},stores=new Map(),fetched=[],deleted=[];let skipped=0,claimed=0;const assets=['./','./index.html','./game.js'],contents={'./':'INDEX','./index.html':'INDEX','./game.js':'CODE'},hashes=Object.fromEntries(assets.map(p=>[p,createHash('sha256').update(contents[p]).digest('hex')])),scope='https://example.github.io/agency/';const cache={async put(url,r){stores.set(url,r)},async match(url){return stores.get(typeof url==='string'?url:url.url)?.clone()}};const context={URL,Response,Uint8Array,Map,Array,crypto:webcrypto,console,self:{registration:{scope},clients:{async claim(){claimed++}},async skipWaiting(){skipped++},addEventListener:(name,fn)=>handlers[name]=fn},caches:{async open(){return cache},async keys(){return ['saeed@'+scope+':old','saeed@https://example.github.io/other/:old','foreign-cache']},async delete(key){deleted.push(key)}},async fetch(url,opts){fetched.push([url,opts]);const u=new URL(typeof url==='string'?url:url.url),path=u.pathname.endsWith('game.js')?'./game.js':u.pathname.endsWith('index.html')?'./index.html':'./';return new Response(corrupt&&path==='./game.js'?'BROKEN':contents[path])}};vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('../scripts/service-worker-template.js',import.meta.url),'utf8').replace('__VERSION__','"test"').replace('__ASSETS__',JSON.stringify(assets)).replace('__HASHES__',JSON.stringify(hashes)),context);const event=async name=>{let promise;handlers[name]({waitUntil:p=>promise=p});await promise};return {context,handlers,stores,fetched,deleted,event,get skipped(){return skipped},get claimed(){return claimed}}}
test('worker activates only after verified full download; cleanup is scoped to this game',async()=>{const w=worker();await w.event('install');assert.equal(w.skipped,1);assert.equal(w.stores.size,3);assert(w.fetched.every(([,opts])=>opts.cache==='no-store'));await w.event('activate');assert.equal(w.claimed,1);assert.deepEqual(w.deleted,['saeed@https://example.github.io/agency/:old']);const broken=worker(true);await assert.rejects(broken.event('install'),/hash mismatch/);assert.equal(broken.skipped,0)});
test('worker serves the installed module offline, ignores query cache busters and never intercepts API calls',async()=>{const w=worker();await w.event('install');w.context.fetch=async()=>{throw Error('offline')};let response;w.handlers.fetch({request:{url:'https://example.github.io/agency/game.js?v=old',method:'GET',mode:'cors'},respondWith:p=>response=p});assert.equal(await(await response).text(),'CODE');let intercepted=false;w.handlers.fetch({request:{url:'https://example.github.io/agency/api/auth',method:'GET'},respondWith(){intercepted=true}});assert.equal(intercepted,false)});
