import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../economy.js';
import {SCENES,RECURRING,CAST,storyLines} from '../story-data.js';
import fs from 'node:fs';
const choose=(a,id,c)=>{a.storyEvaluate();assert.equal(a.s.story.queue[0],id);assert(a.chooseStory(id,c));assert.doesNotThrow(()=>Simulation.validate(a.s))};
function ready(){const a=new Simulation();a.sign('محمد');a.inventory();a.repair();a.hire('driver');a.contract('bakery');return a}
function completed(a){for(const x of SCENES){a.s.story.done.push(x.id);a.s.story.decisions[x.id]=x.choices[0].id;}a.s.story.queue=[];}
test('v8.2 migration preserves business and offers opt-in, fresh game begins story',()=>{const a=ready(),old=structuredClone(a.s);delete old.story;const b=new Simulation(old);assert.equal(b.s.story.enabled,false);assert.equal(b.s.story.offered,false);for(const key of ['stock','money','vehicles','contracts','orders','team'])assert.deepEqual(b.s[key],old[key]);b.enableStory();assert.equal(b.s.story.queue[0],'key');assert(new Simulation().s.story.enabled);});
test('story choices are atomic, costed, persistent and never award twice',()=>{const a=ready();choose(a,'key','people');choose(a,'inventory','continue');a.s.money=0;const n=structuredClone(a.s.story);assert.equal(a.chooseStory('engine','ready'),false);assert.deepEqual(a.s.story,n);a.s.money=500;const expense=a.s.expenses;choose(a,'engine','ready');assert.equal(a.s.money,380);assert.equal(a.s.expenses,expense+120);assert.equal(a.s.story.prep,2);assert.equal(a.chooseStory('engine','ready'),false);assert.equal(a.s.money,380);const saved=new Simulation(a.s);assert.equal(saved.s.story.decisions.engine,'ready');assert.equal(saved.s.story.queue[0],'bread');});
test('six chapters reach opening through gameplay gates; end does not reset business',()=>{const a=ready();a.s.money=100000;choose(a,'key','system');choose(a,'inventory','continue');choose(a,'engine','steady');choose(a,'bread','continue');a.s.stock=[{pid:'bread',qty:10,unit:90,expires:5}];choose(a,'pallet','continue');a.s.tripHistory=[{day:1,clients:[0],route:'local',orders:1}];choose(a,'road','continue');a.s.delivered=1;choose(a,'first','reserve');assert.equal(a.s.story.queue.length,0);a.s.delivered=5;choose(a,'name','continue');for(const cid of ['dairy','pantry','frozen']){a.s.contracts[cid]=true;a.s.cycles[cid]={startDay:1,endDay:8,target:22000,successes:0,misses:0}}choose(a,'cold','cash');assert(a.hire('worker'));choose(a,'team','listen');a.s.delivered=15;choose(a,'roots','help');choose(a,'pantry','margin');a.s.regions.push('الدقهلية');choose(a,'delta','continue');choose(a,'frozen','continue');a.s.delivered=70;a.s.rep=80;a.change();choose(a,'offer','roots');assert(a.buyDevelopment('frontage'));assert(a.buyDevelopment('landmark'));const money=a.s.money;choose(a,'opening','continue');assert(a.s.story.flags.finished);assert.equal(a.s.story.chapter,5);assert.equal(a.s.money,money);assert.equal(a.s.story.done.filter(id=>SCENES.some(x=>x.id===id)).length,16);assert.equal(a.s.delivered,70);});
test('recurring decisions require real activity, respect cooldown and unlock relationship followups',()=>{const a=ready();completed(a);a.s.delivered=8;a.s.elapsed=120;a.s.story.lastScene=0;a.s.story.actions=1;a.storyRecurring('pack');assert.equal(a.s.story.queue.length,0);a.s.story.actions=4;a.storyRecurring('pack');assert.equal(a.s.story.queue[0],'packing');assert(a.chooseStory('packing','keep'));a.s.elapsed=250;a.s.story.actions+=4;a.storyRecurring('pack');assert.equal(a.s.story.queue.length,0);a.s.elapsed=500;a.storyRecurring('pack');assert.equal(a.s.story.queue[0],'packing');a.chooseStory('packing','keep');a.s.elapsed=650;a.s.story.actions+=4;a.s.story.bonds.rabie=54;a.s.story.cooldowns.competition=650;a.s.story.cooldowns.teamtalk=650;a.storyRecurring('timer');assert.equal(a.s.story.queue[0],'rabie_trust');a.chooseStory('rabie_trust','learn');assert.equal(a.s.story.prep,2);a.s.elapsed=1200;a.s.story.actions+=4;a.s.story.cooldowns.competition=1200;a.s.story.cooldowns.teamtalk=1200;a.storyRecurring('timer');assert(!a.s.story.queue.includes('rabie_trust'));assert.doesNotThrow(()=>Simulation.validate(a.s));});
test('training modifies real worker picking job only; failed pack cannot consume training',()=>{const a=ready();a.s.delivered=1;a.hire('worker');a.s.story.prep=2;const before=a.s.story.prep;assert.equal(a.pack(-1),false);assert.equal(a.s.story.prep,before);a.s.orders=[];const o={id:a.s.seq++,client:0,pid:'bread',qty:10,price:132,accepted:true,discount:0,payment:'cash',expires:300,deadline:300};a.s.orders.push(o);a.s.stock=[{pid:'bread',qty:20,unit:90,expires:5}];const control=new Simulation(a.s);control.s.story.prep=0;assert(control.pack(o.id));assert(a.pack(o.id));assert.equal(a.s.story.prep,1);assert.equal(a.s.pickingJob.duration,Math.max(2,control.s.pickingJob.duration*.9));assert.deepEqual(a.s.stock,control.s.stock);});
test('deferred pending story survives reload; disabling does not discard decisions',()=>{const a=ready();choose(a,'key','people');a.deferStory();const b=new Simulation(a.s);assert.equal(b.s.story.snooze,b.s.elapsed+90);assert.equal(b.s.story.queue[0],'inventory');b.enableStory(false);const counts=structuredClone(b.s.story.counts);b.storySignal('pack');assert.deepEqual(b.s.story.counts,counts);b.enableStory();assert.equal(b.s.story.decisions.key,'people');assert.equal(b.s.story.queue[0],'inventory');});
test('invalid story imports rejected, every portrait and dialogue speaker resolves',()=>{const a=ready();for(const mutate of [s=>s.story.prep=99,s=>s.story.queue=['missing'],s=>s.story.bonds.rabie=Infinity,s=>s.story.history=[{scene:'key',choice:'cheat',day:1,at:0}],s=>s.story.decisions.key='people',s=>s.story.flags.cheat=true,s=>s.story.cooldowns.fake=0]){const bad=structuredClone(a.s);mutate(bad);assert.throws(()=>Simulation.validate(bad));}for(const x of [...SCENES,...RECURRING]){assert(x.choices.some(c=>!c.effect.cost),'Each scene must allow a free option');for(const l of storyLines(x,a.s))assert(CAST[l.who]);}for(const id of Object.keys(CAST)){const bytes=fs.readFileSync(new URL('../assets/portraits/'+id+'.png',import.meta.url));assert.equal(bytes.subarray(1,4).toString(),'PNG');}});
test('initial path and ending choices change later dialogue',()=>{const a=ready(),first=SCENES.find(x=>x.id==='first'),end=SCENES.find(x=>x.id==='opening');a.s.story.path='people';const people=storyLines(first,a.s);a.s.story.path='system';assert.notDeepEqual(storyLines(first,a.s),people);a.s.story.ending='network';const network=storyLines(end,a.s);a.s.story.ending='roots';assert.notDeepEqual(storyLines(end,a.s),network);});
