import {truckBanner} from './truck-branding.js';
import * as T from '../vendor/three.module.js';
import {COMPANIES,PRODUCTS} from '../economy.js';
import {DISTRICT_TASKS,STAGES} from '../simulation/development.js';
import {BAY_X} from './fleet-path.js';
const colors={agency:0x275a5b,bakery:0xaa713b,dairy:0x4c9690,pantry:0x9d593b,frozen:0x567ba3};
export const detail={
 initDetail(){
 this.detailGroup=new T.Group();this.scene.add(this.detailGroup);this.equipmentGroup=new T.Group();this.scene.add(this.equipmentGroup);this.loadingGroup=new T.Group();this.scene.add(this.loadingGroup);this.occluders=[];this.scene.traverse(o=>{if(o.isMesh&&o.geometry?.type==='BoxGeometry'&&o.position.y>1.3&&(o.geometry.parameters.height>2.5||o.position.y>3&&o.geometry.parameters.width>6&&o.geometry.parameters.depth>3)&&!o.userData.action){o.material=o.material.clone();o.userData.occlusionOpacity=o.material.opacity;this.occluders.push(o)}});
 this.mat('epoxy',0x687e79,.62,.05);this.mat('safety',0xd9ac4e,.8);this.mat('chrome',0xa9b3b2,.24,.85);this.mat('paintWhite',0xdbdfd7,.36,.18);this.mat('soil',0x745b45,1);
 for(const name of ['wall','concrete','wood','box']){const m=this.mats[name];m.bumpMap=m.map;m.bumpScale=name==='concrete'?.025:.013;}
 this.truckMeshes=new Set([this.truck]);this.detailKey='';this.customerTransfers=new Map();
 // Task-linked warning lamps, not decorative notifications.
 this.coldBeacon=this.sphere(.1,12.15,3.55,-5.03,'red');this.coldBeacon.material=this.mats.red.clone();this.coldBeacon.material.emissive.set(0xff3c12);
 this.loadingBeacon=this.sphere(.10,7.4,3.6,8.6,'brass');this.loadingBeacon.material=this.mats.brass.clone();this.loadingBeacon.material.emissive.set(0xffbd35);
 this.box(.8,.04,.48,-9.7,1.4,-4.1,'dark').userData.action='development';this.label('التطوير',.66,.32,-9.7,1.425,-4.1,'#b8e8d2','#163c47').rotation.x=-Math.PI/2;
 this.interact('development','تطوير الوكالة',-9.7,2.2,-4.1,-9,-2.3);
 },
 makeEquipment(kind){const g=new T.Group();g.userData.kind=kind;
 if(kind==='jack'){for(const x of [-.28,.28]){this.box(.15,.12,1.15,x,.14,.35,'safety',g);const w=this.cyl(.1,.1,.09,x,.12,.78,'rubber',g);w.rotation.z=Math.PI/2}this.box(.75,.24,.22,0,.22,-.25,'safety',g);const handle=this.box(.06,.8,.05,0,.64,-.4,'metal',g);handle.rotation.x=-.18;this.box(.43,.06,.06,0,1.05,-.48,'rubber',g);
 }else{this.rounded(.82,.68,1.05,0,.52,-.25,'safety',g);this.box(.5,.13,.42,0,.94,-.32,'rubber',g);this.box(.5,.48,.12,0,1.12,-.57,'rubber',g);for(const x of [-.46,.46])for(const z of [-.65,.4]){const wheel=this.cyl(.22,.22,.16,x,.23,z,'rubber',g);wheel.rotation.z=Math.PI/2}for(const x of [-.35,.35]){this.box(.07,1.8,.08,x,1.1,.52,'metal',g);this.box(.13,.06,.9,x,.15,1,'metal',g);this.box(.06,1.8,.06,x,1.2,-.65,'metal',g)}this.box(.95,.07,1.25,0,2.05,-.05,'metal',g);this.box(.13,.05,.13,.3,2.14,-.3,'brass',g);this.box(.76,.08,.15,0,.4,.65,'chrome',g);}
 g.userData.crate=this.carton(0,.25,.38,.7,g);g.userData.crate.visible=false;return g;
 },
 enhanceTruck(g,id,s){
 if(!g.userData.finish){const f=new T.Group();g.add(f);g.userData.finish=f;
 for(const z of [-1,1]){this.box(1.3,.07,.25,1.6,.73,z,'chrome',f);this.box(.04,.72,.05,.94,1.55,z*1.05,'dark',f);this.box(.22,.05,.06,1.23,1.33,z*1.05,'chrome',f);for(const x of [-1.5,1.67]){const arch=new T.Mesh(new T.TorusGeometry(.55,.05,5,16,Math.PI),this.mats.metal);arch.position.set(x,.49,z*1.09);f.add(arch)}this.box(.12,.32,.19,2.1,1.79,z*1.17,'chrome',f);this.box(.13,.09,.27,-2.5,.75,z*.78,'red',f);this.box(.9,.09,.08,-1.6,1,z*1.07,'chrome',f)}
 this.box(.85,.12,.04,2.68,.9,0,'paper',f).rotation.y=Math.PI/2;this.box(.6,.32,1.45,1.52,1.12,0,'dark',f);const steering=new T.Mesh(new T.TorusGeometry(.17,.025,8,20),this.mats.rubber);steering.position.set(2,1.55,.43);steering.rotation.y=Math.PI/2;f.add(steering);
 const driver=this.human('shirt',1+(id-1)%3);driver.position.set(1.42,.1,.43);driver.rotation.y=Math.PI/2;for(const leg of driver.userData.legs){leg.rotation.x=-Math.PI/2;leg.userData.knee.rotation.x=Math.PI/2}for(const arm of driver.userData.arms)arm.rotation.x=-1;driver.userData.seated=true;f.add(driver);g.userData.driver=driver;const entering=this.human('shirt',1+(id-1)%3);entering.rotation.y=Math.PI;f.add(entering);g.userData.entering=entering;
 const dirt=new T.Group();f.add(dirt);g.userData.dirt=dirt;for(const z of [-1.063,1.063])for(let i=0;i<12;i++){const m=this.box(.16+(i%3)*.08,.035+(i%4)*.026,.012,-2.1+i*.4,.8+(i%3)*.06,z,'soil',dirt);m.rotation.z=(i%3-1)*.15}const scratches=new T.Group();f.add(scratches);g.userData.scratches=scratches;for(const z of [-1.08,1.08])for(let i=0;i<4;i++){const line=this.box(.28,.009,.009,-1+i*.32,1.15+i*.06,z,'metal',scratches);line.rotation.z=.08;}g.userData.brandGroup=new T.Group();f.add(g.userData.brandGroup);
 }
 const trip=[s.trip,...s.fleetTrips].find(t=>t?.vehicleId===id),leg=trip?.legs[trip.legIndex],boarding=leg?.boarding&&trip.legElapsed<(leg.hold||0),phase=boarding?Math.max(0,Math.min(1,(trip.legElapsed-((leg.hold||0)-leg.boarding))/leg.boarding)):1;g.userData.driver.visible=!!trip&&!boarding;g.userData.entering.visible=!!boarding;g.userData.entering.position.set(1.4,phase>.8?(phase-.8)*2:0,2.1-phase*.95);g.userData.entering.userData.legs[0].rotation.x=Math.sin(phase*18)*.28;g.userData.entering.userData.legs[1].rotation.x=-Math.sin(phase*18)*.28;for(let i=0;i<g.userData.cabDoors.length;i++)g.userData.cabDoors[i].rotation.y=i===1&&boarding?-Math.sin(phase*Math.PI)*1.1:0;g.userData.scratches.visible=(s.vehicles.find(v=>v.id===id)?.condition||100)<80;const km=(s.ops.maintenance[id]?.km||0)-(s.development.washedAt[id]||0);g.userData.dirt.visible=km>2;g.userData.dirt.scale.y=Math.min(1.4,.3+km/35);
 const open=trip?!!g.userData.open:!!s.carry&&id===s.selectedVehicle||!!s.pickingJob&&id===s.selectedVehicle||(s.ops.doors['v'+id]||0)>s.elapsed;for(let i=0;i<(g.userData.rearDoors?.length||0);i++)g.userData.rearDoors[i].rotation.y=open?(i===0?-1.65:1.65):0;
 const cid=s.development.branding[id]||'agency',brandKey=cid+':'+g.userData.kind;if(g.userData.brandKey!==brandKey){g.userData.brandKey=brandKey;this.clearGroup(g.userData.brandGroup);const material=truckBanner(this,cid);for(const z of [-1.086,1.086]){const sign=new T.Mesh(new T.PlaneGeometry(3.2,1.6),material);sign.position.set(-.75,1.89,z);sign.userData.sharedTexture=true;if(z<0)sign.rotation.y=Math.PI;g.userData.brandGroup.add(sign);}for(const [index,door]of g.userData.rearDoors.entries()){const old=door.userData.banner;if(old){door.remove(old);old.geometry.dispose()}const label=new T.Mesh(new T.PlaneGeometry(.86,.48),material);label.position.set(-.057,1.35,index===0?.52:-.52);label.rotation.y=-Math.PI/2;label.userData.sharedTexture=true;door.add(label);door.userData.banner=label;} }

 },
 updateDetail(dt,s){
 const d=s.development,owned=d.owned,signature=JSON.stringify([owned,d.stage,s.officeLevel]);if(signature!==this.detailKey){this.detailKey=signature;this.clearGroup(this.detailGroup);const g=this.detailGroup;
 if(owned.paving){this.box(29,.025,4.7,0,.005,5.5,'epoxy',g);for(let x=-13;x<13;x+=1.5)this.box(.8,.012,.05,x,.024,3.4,'safety',g);for(let x=-13;x<13;x+=1.5)this.box(.8,.012,.05,x,.024,7.5,'safety',g)}
 if(owned.frontage){this.box(29,.45,.18,0,4.4,-7.83,'teal',g);const sign=this.label('وكالة سعيد • '+STAGES[d.stage].name,8,.9,-8.7,4.2,-7.65,'#f2d8a4','#21434a',g);sign.material.emissive.set(0xb1a080);sign.material.emissiveIntensity=.18;for(let x=-13;x<13;x+=4)this.box(.6,.055,.4,x,4.65,-7.6,'light',g)}
 if(owned.dispatch){this.box(2.1,.75,.75,-8,.4,1.3,'teal',g);this.box(1.35,.77,.08,-8,1.18,1.4,'dark',g);this.label('تشغيل الخطوط',1.15,.4,-8,1.2,1.46,'#a9e4d5','#17343d',g);this.box(1.7,.05,.35,-8,.86,1,'paper',g)}
 if(owned.wash){this.box(2,.1,1,10,.08,12.8,'metal',g);this.cyl(.25,.25,.8,10,.53,13,'teal',g);const hose=new T.Mesh(new T.TorusGeometry(.32,.035,6,18),this.mats.rubber);hose.position.set(10.55,.7,13);g.add(hose);this.label('غسيل الأسطول',2.4,.4,10,1.8,13.1,'#e1ded1','#214a55',g);g.userData.action='garage'}
 if(owned.landmark){this.box(29,.45,.6,0,5.4,-8.1,'paintWhite',g);for(const x of [-14,14])this.box(.3,5.5,.35,x,2.6,-8.1,'chrome',g);this.label('وكالة سعيد • مركز توزيع إقليمي',15,.9,0,5.65,-7.9,'#f1d594','#1d4950',g);this.box(5,.1,1.4,-9,3.3,1.9,'teal',g)}
 }
 const equipmentKey=JSON.stringify([owned.jack,owned.forklift]);if(this.equipmentKey!==equipmentKey){this.equipmentKey=equipmentKey;this.clearGroup(this.equipmentGroup);this.equipment={};for(const kind of ['jack','forklift'])if(owned[kind]){const g=this.makeEquipment(kind);g.userData.action='development';this.equipmentGroup.add(g);this.equipment[kind]=g;}}
 const job=s.pickingJob||s.workerJob;for(const [kind,g]of Object.entries(this.equipment||{})){g.position.set(kind==='jack'?6.2:12.8,0,4.4);g.rotation.y=Math.PI;g.userData.crate.visible=false;if(job&&job.equipment===kind&&this.workerActor){g.position.copy(this.workerActor.position);g.rotation.y=this.workerActor.rotation.y;g.userData.crate.visible=!!this.workerBox?.visible;if(this.workerBox)this.workerBox.visible=false;if(kind==='forklift'){this.workerActor.position.y=.38;this.workerActor.userData.seated=true;for(const leg of this.workerActor.userData.legs)leg.rotation.x=-1.3;}else for(const arm of this.workerActor.userData.arms)arm.rotation.x=-.9;}}
 if(this.workerActor&&job?.equipment!=='forklift'){this.workerActor.position.y=0;this.workerActor.userData.seated=false}
 const trucks=[[s.selectedVehicle,this.truck],...this.extraTrucks.children.map(g=>[g.userData.vehicle,g]),...this.cityTrucks.entries()];for(const [id,g]of trucks)if(id)this.enhanceTruck(g,id,s);
 const coldDanger=Object.values(s.ops.exposure).some(n=>n>=40);this.coldBeacon.material.emissiveIntensity=coldDanger?1+Math.sin(this.elapsed*8)*.8:0;this.loadingBeacon.material.emissiveIntensity=job||s.carry?.9:0;
 for(const person of this.adults||[]){if(person.userData.managerShirt){person.userData.managerShirt.color.copy(person.userData.managerShirtBase);if(owned.uniforms)person.userData.managerShirt.color.multiply(new T.Color(0x8fbbbd));continue;}const material=this.mats['person_'+person.userData.identity+'_shirt'];if(material)material.color.set(owned.uniforms?(person.userData.identity===4?0xc09a51:0x638184):person.userData.baseShirt);}
 this.updateLoadingMotion(s);this.updateCustomers(dt,s);this.updateOcclusion(dt);
 },
 updateLoadingMotion(s){const motion=s.development.loadMotion,visible=motion&&s.elapsed-motion.start<1.3&&!s.trip&&motion.vehicle===s.selectedVehicle;this.loadingGroup.visible=!!visible;if(!visible){this.dynamicCargo.visible=this.dynamicCargo.children.length>0;for(const box of this.dynamicCargo.children)box.visible=true;return}const f=Math.min(1,(s.elapsed-motion.start)/1.3),home=BAY_X[s.vehicles.findIndex(v=>v.id===motion.vehicle)];if(this.loadKey!==motion.start+':'+motion.pid){this.loadKey=motion.start+':'+motion.pid;this.clearGroup(this.loadingGroup);this.carton(0,0,0,.8,this.loadingGroup,this.mats['product_'+motion.pid]||this.mats.box)}const t=f*f*(3-2*f);this.loadingGroup.position.set(motion.x+(home-motion.x)*t,.85+.2*t+Math.sin(Math.PI*f)*.25,motion.z+(13.7-motion.z)*t);this.dynamicCargo.visible=true;const before=Math.ceil(Math.max(0,s.cargo.reduce((n,b)=>n+b.qty,0)-motion.qty)/5);this.dynamicCargo.children.forEach((box,i)=>box.visible=i<before||f>.88);for(const arm of this.player.userData.arms)arm.rotation.x=-1.1*(1-f);},
 updateCustomers(dt,s){const trips=[s.trip,...s.fleetTrips].filter(Boolean);for(let i=0;i<(this.shops?.length||0);i++){const shop=this.shops[i],trip=trips.find(t=>{const leg=t.legs[t.legIndex];return leg.kind==='unload'&&leg.client===i&&t.legElapsed>=(leg.windowWait||0)}),door=shop.userData.door,npc=shop.userData.customer;door.rotation.y+=((trip?-1.25:0)-door.rotation.y)*Math.min(1,dt*5);if(trip){const leg=trip.legs[trip.legIndex],f=(trip.legElapsed-(leg.windowWait||0))/Math.max(.1,leg.duration-(leg.windowWait||0)),p=this.neighborhood.clients[i],truck=this.cityTrucks.get(trip.vehicleId);truck?.updateWorldMatrix(true,false);shop.updateWorldMatrix(true,false);const stop=truck?truck.localToWorld(new T.Vector3(-3.25,0,0)):new T.Vector3(p.x,-.15,p.z),local=shop.worldToLocal(stop);const walk=Math.sin(Math.PI*Math.min(1,f)),dx=local.x+1.3,dz=local.z+2.8,total=Math.abs(dx)+Math.abs(dz),distance=walk*total,along=Math.min(Math.abs(dx),distance),vertical=Math.max(0,distance-Math.abs(dx));npc.position.set(-1.3+Math.sign(dx)*along,0,-2.8+Math.sign(dz)*vertical);npc.rotation.y=(distance<Math.abs(dx)?Math.sign(dx)*Math.PI/2:dz>=0?0:Math.PI)+(f>.5?Math.PI:0);for(let k=0;k<2;k++)npc.userData.legs[k].rotation.x=Math.sin(this.elapsed*10+k*Math.PI)*.35;if(!npc.userData.deliveryBox)npc.userData.deliveryBox=this.carton(0,.8,.48,.65,npc);npc.userData.deliveryBox.visible=f>.5;for(const arm of npc.userData.arms)arm.rotation.x=f>.5?-1:-.1;}else{npc.position.set(-1.3,0,-2.8);if(npc.userData.deliveryBox)npc.userData.deliveryBox.visible=false;for(const leg of npc.userData.legs)leg.rotation.x=0;for(const arm of npc.userData.arms)arm.rotation.x=-.08;}
 const complete=DISTRICT_TASKS.some((task,k)=>task.client===i&&s.development.districts[k]?.rewarded);if(shop.userData.renewed!==complete){shop.userData.renewed=complete;this.clearGroup(shop.userData.renewal);if(complete){this.box(6.1,.2,.22,0,3.8,-2.05,'brass',shop.userData.renewal);this.label('شريك وكالة سعيد',3,.38,0,3.7,-2.2,'#f7e3a8','#255458',shop.userData.renewal).rotation.y=Math.PI;for(const x of [-2.65,2.65])this.box(.1,2.6,.12,x,1.4,-2.1,'teal',shop.userData.renewal);}}
 }},
 updateOcclusion(dt){this.occlusionClock=(this.occlusionClock||0)+dt;if(this.occlusionClock<.12)return;this.occlusionClock=0;this.scene.updateMatrixWorld(true);const target=this.player.position.clone().add(new T.Vector3(0,1,0)),direction=target.clone().sub(this.camera.position);const ray=new T.Raycaster(this.camera.position,direction.clone().normalize(),0,direction.length()-.25),hits=new Set(ray.intersectObjects(this.occluders,false).map(h=>h.object));for(const mesh of this.occluders){const fade=this.view!=='city'&&hits.has(mesh);mesh.material.transparent=true;mesh.material.opacity=fade?.16:mesh.userData.occlusionOpacity;mesh.material.depthWrite=!fade;}}
};
