import {DAY_SECONDS} from '../economy.js';
import * as T from '../vendor/three.module.js';
import {EffectComposer} from '../vendor/addons/postprocessing/EffectComposer.js';
import {RenderPass} from '../vendor/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from '../vendor/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from '../vendor/addons/postprocessing/OutputPass.js';
export const effects={
 initEffects(){
 this.dust=[];this.seasonDecor=new T.Group();this.scene.add(this.seasonDecor);for(let x=-12;x<12;x+=3){this.cyl(.12,.23,.45,x,4,2,'brass',this.seasonDecor);this.sphere(.13,x,3.8,2,'light',this.seasonDecor)}this.lamps=[];this.scene.traverse(o=>{if(o.isPointLight)this.lamps.push(o)});this.lightSites=this.lamps.map(l=>({position:l.position.clone(),power:l.userData.nightPower||10,color:l.color.clone(),distance:l.distance,decay:l.decay}));for(const l of this.lamps)l.removeFromParent();this.lamps=Array.from({length:4},()=>{const l=new T.PointLight(0xffe2b6,0,24,1.7);this.scene.add(l);return l});this.lightClock=1;
 this.sky=new T.Mesh(new T.SphereGeometry(350,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color('#85b9cc')},bottom:{value:new T.Color('#d7c3a3')}},vertexShader:'varying vec3 v;void main(){v=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 v;uniform vec3 top;uniform vec3 bottom;void main(){float h=clamp(normalize(v).y*.8+.25,0.,1.);gl_FragColor=vec4(mix(bottom,top,h),1.);}'}));this.scene.add(this.sky);
 const pts=new Float32Array(900);for(let i=0;i<pts.length;i+=3){pts[i]=(Math.random()-.5)*34;pts[i+1]=Math.random()*18;pts[i+2]=Math.random()*17+3}this.rain=new T.Points(new T.BufferGeometry().setAttribute('position',new T.BufferAttribute(pts,3)),new T.PointsMaterial({color:0xc8e3ed,size:.055,transparent:true,opacity:.55}));this.scene.add(this.rain);
 if(!this.cb.rendererFactory){for(const [name,file]of [['wood','wood'],['concrete','concrete']])new T.TextureLoader().load('./assets/'+file+'.png',tex=>{tex.colorSpace=T.SRGBColorSpace;tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.repeat.set(3,3);tex.anisotropy=Math.min(4,this.renderer.capabilities.getMaxAnisotropy());this.mats[name].map?.dispose();this.mats[name].map=tex;this.mats[name].bumpMap=tex;this.mats[name].needsUpdate=true});
 const studio=new T.Scene();studio.background=new T.Color('#879da1');for(const pos of [[0,10,0],[-8,2,0],[4,3,8]]){const light=new T.Mesh(new T.BoxGeometry(5,.2,5),new T.MeshBasicMaterial({color:0xffffff}));light.position.set(...pos);studio.add(light)}const pmrem=new T.PMREMGenerator(this.renderer);this.environment=pmrem.fromScene(studio);this.scene.environment=this.environment.texture;studio.traverse(o=>{o.geometry?.dispose();o.material?.dispose()});pmrem.dispose();
 if(!this.touchDevice){this.composer=new EffectComposer(this.renderer);this.composer.setPixelRatio(1);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.16,.3,1.1);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());}}
 },
 spawnDust(x,y,z){const points=new Float32Array(60);for(let i=0;i<60;i++)points[i]=(Math.random()-.5)*.65;const m=new T.Points(new T.BufferGeometry().setAttribute('position',new T.BufferAttribute(points,3)),new T.PointsMaterial({color:0xd5c4a0,size:.12,transparent:true}));m.position.set(x,y,z);this.scene.add(m);this.dust.push({m,life:.8})},
 updateEffects(dt,s){this.seasonDecor.visible=s.season==='ramadan'||s.season==='eid';const angle=((s.time/DAY_SECONDS+8/24)%1)*Math.PI*2-Math.PI/2,day=Math.max(0,Math.sin(angle)),storm=s.weather==='rain'?.58:1;
 this.renderer.toneMappingExposure=({balanced:1.08,bright:1.24,soft:.95}[s.settings.lighting]||1.08)+(1-day)*.1;for(const m of Object.values(this.mats))m.envMapIntensity=.26+day*.24;this.sun.position.set(Math.cos(angle)*30,Math.max(2,Math.sin(angle)*30),15);this.sun.color.setHSL(.10,.13+(1-day)*.16,.88);this.sun.intensity=(.12+day*3.4)*storm;this.hemi.intensity=(1.25+day*.9)*(s.settings.brightNight?1.3:1);this.fill.intensity=.65+day*.45;this.hemi.color.setHSL(.56,.22,.58+day*.2);
 this.sky.material.uniforms.top.value.setHSL(.59,.3,.055+day*.48*storm);this.sky.material.uniforms.bottom.value.setHSL(.09,.22,.16+day*.54*storm);this.scene.fog.color.copy(this.sky.material.uniforms.bottom.value);
 this.lightClock+=dt;if(this.lightClock>=.5){this.lightClock=0;const sites=[...this.lightSites].sort((a,b)=>a.position.distanceToSquared(this.target)-b.position.distanceToSquared(this.target));this.lamps.forEach((l,i)=>{const site=sites[i];if(site){l.position.copy(site.position);l.color.copy(site.color);l.distance=site.distance;l.decay=site.decay;l.userData.nightPower=site.power;}})}for(const l of this.lamps)l.intensity=(l.userData.nightPower?l.userData.nightPower*(.2+(1-day)*.8):2+(1-day)*8)*(s.settings.brightNight?1.35:1);
 if(this.mats.windowLit)this.mats.windowLit.emissiveIntensity=.1+(1-day)*.85;this.rain.visible=s.weather==='rain';if(this.rain.visible){const p=this.rain.geometry.attributes.position;for(let i=0;i<p.count;i++){let y=p.getY(i)-dt*12;p.setY(i,y<0?18:y)}p.needsUpdate=true}
 for(const d of this.dust){d.life-=dt;d.m.position.y+=dt*.7;d.m.material.opacity=Math.max(0,d.life/.8)}this.dust=this.dust.filter(d=>{if(d.life>0)return true;this.scene.remove(d.m);d.m.geometry.dispose();d.m.material.dispose();return false});
 this.minimapClock=(this.minimapClock||0)+dt;const canvas=document.getElementById('minimap');if(canvas&&this.active&&this.minimapClock>=.1){this.minimapClock=0;canvas.hidden=false;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#193b40';c.fillRect(0,0,w,h);const point=(x,z)=>[(x+62)/78*w,(z+46)/66*h];c.fillStyle='#8a998c';for(const o of this.obstacles){const a=point(o.x-o.w/2,o.z-o.d/2),b=point(o.x+o.w/2,o.z+o.d/2);c.fillRect(a[0],a[1],b[0]-a[0],b[1]-a[1])}for(const o of this.interactables){const p=point(o.approach.x,o.approach.z);c.fillStyle=o.id===this.cb.target?.()?'#ffcc70':'#8da89d';c.fillRect(p[0]-2,p[1]-2,4,4)}const p=point(this.player.position.x,this.player.position.z);c.fillStyle='#fff2bd';c.beginPath();c.arc(...p,4,0,Math.PI*2);c.fill();if(this.truck.visible){const p=point(this.truck.position.x,this.truck.position.z);c.fillStyle='#58d3c1';c.fillRect(p[0]-5,p[1]-3,10,6)}}
 },
 renderScene(){if(this.composer&&!this.touchDevice&&this.state?.settings.quality!=='low')this.composer.render();else this.renderer.render(this.scene,this.camera)}
};
