// One pointer: orbit or pan. Two pointers: anchored zoom plus translation.
export function bindWorldGestures(canvas,{enabled,getAngle,setAngle,getZoom,setZoom,tap,pan,zoomAt,getMode=()=> 'orbit',getElevation=()=>.77,setElevation=()=>{}}){
 const pointers=new Map();let anchor=null,pinch=null,suppressTap=false,dragged=false;
 const geometry=()=>{const [a,b]=[...pointers.values()];return {distance:Math.max(1,Math.hypot(a.x-b.x,a.y-b.y)),x:(a.x+b.x)/2,y:(a.y+b.y)/2}};
 const rebase=()=>{pinch=pointers.size>=2?{...geometry(),zoom:getZoom()}:null;};
 const reset=()=>{const ids=[...pointers.keys()];pointers.clear();anchor=pinch=null;suppressTap=dragged=false;for(const id of ids)try{if(canvas.hasPointerCapture?.(id))canvas.releasePointerCapture(id)}catch{}};
 canvas.addEventListener('pointerdown',e=>{if(!enabled()||e.button!==undefined&&![0,1,2].includes(e.button))return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});try{canvas.setPointerCapture?.(e.pointerId)}catch{}if(pointers.size===1){anchor={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,angle:getAngle(),elevation:getElevation(),pan:e.button===1||e.button===2||e.shiftKey||getMode()==='pan'};suppressTap=e.button===1||e.button===2;dragged=false;}else{suppressTap=true;rebase();}});
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;if(!enabled()){reset();return}e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2){if(!pinch)rebase();const g=geometry(),zoom=Math.max(8,Math.min(180,pinch.zoom*pinch.distance/g.distance));pan?.(pinch.x,pinch.y,g.x,g.y);if(zoomAt)zoomAt(g.x,g.y,zoom);else setZoom(zoom);pinch={...g,zoom:getZoom()};suppressTap=true;}else if(anchor){const dx=e.clientX-anchor.x,dy=e.clientY-anchor.y;if(Math.hypot(dx,dy)>7)dragged=true;if(dragged){if(anchor.pan)pan?.(anchor.lastX,anchor.lastY,e.clientX,e.clientY);else if(!suppressTap){setAngle(anchor.angle-dx*.006);setElevation(Math.max(.3,Math.min(1.15,anchor.elevation+dy*.003)))}}anchor.lastX=e.clientX;anchor.lastY=e.clientY;}});
 const end=(e,cancelled)=>{if(!pointers.has(e.pointerId))return;e.preventDefault();const click=!cancelled&&pointers.size===1&&!suppressTap&&!dragged&&anchor&&Math.hypot(e.clientX-anchor.x,e.clientY-anchor.y)<=7;pointers.delete(e.pointerId);if(pointers.size){suppressTap=true;anchor=null;rebase();}else{anchor=pinch=null;suppressTap=dragged=false;}try{if(canvas.hasPointerCapture?.(e.pointerId))canvas.releasePointerCapture(e.pointerId)}catch{}if(click&&enabled())tap(e);};
 canvas.addEventListener('pointerup',e=>end(e,false));canvas.addEventListener('pointercancel',e=>end(e,true));canvas.addEventListener('lostpointercapture',e=>end(e,true));canvas.addEventListener('contextmenu',e=>e.preventDefault());return {reset,get active(){return pointers.size>0}};
}
