import * as T from '../vendor/three.module.js';
import {MANAGER_DATA as DATA} from '../assets/manager/manager-data.js';
export function createManager(world,identity=0){
 const g=new T.Group();g.name='Warehouse manager';const bones=DATA.bones.map(b=>{const o=new T.Bone();o.name=b.name;return o});
 DATA.bones.forEach((b,i)=>{bones[i].position.fromArray(b.position);if(b.parent>=0){bones[i].position.sub(new T.Vector3().fromArray(DATA.bones[b.parent].position));bones[b.parent].add(bones[i])}else g.add(bones[i])});
 const skeleton=new T.Skeleton(bones);g.updateMatrixWorld(true);skeleton.calculateInverses();const cache=world.managerTextures||(world.managerTextures=new Map());
 function texture(name,color=true){if(!name||typeof document==='undefined'||world.cb?.rendererFactory)return null;if(!cache.has(name)){const path=globalThis.SAEED_MANAGER_TEXTURES?.[name]||'./assets/manager/'+name;const t=new T.TextureLoader().load(path,undefined,undefined,()=>{g.userData.textureError=name;console.error('Manager texture unavailable',name)});t.colorSpace=color?T.SRGBColorSpace:T.NoColorSpace;t.anisotropy=4;cache.set(name,t)}return cache.get(name)}
 const materials=DATA.materials.map(m=>{const mat=new T.MeshStandardMaterial({name:m.name,color:new T.Color().setRGB(...m.color),roughness:m.roughness,metalness:0,map:texture(m.map),normalMap:texture(m.normal,false),alphaTest:m.alphaTest||0,side:m.doubleSide?T.DoubleSide:T.FrontSide});if(m.normal)mat.normalScale.set(.45,.45);return mat});
 for(const m of DATA.meshes){const geo=new T.BufferGeometry();for(const [key,size]of [['position',3],['normal',3],['uv',2],['skinWeight',4]])geo.setAttribute(key,new T.Float32BufferAttribute(m[key],size));geo.setAttribute('skinIndex',new T.Uint16BufferAttribute(m.skinIndex,4));geo.setIndex(m.index);const mesh=new T.SkinnedMesh(geo,materials[m.material]);mesh.name=m.name;mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.managerTextureCache=true;g.add(mesh);mesh.bind(skeleton,new T.Matrix4());mesh.frustumCulled=false}
 const byName=Object.fromEntries(bones.map(b=>[b.name,b])),legs=[byName['thigh.R'],byName['thigh.L']],arms=[byName['upperarm.R'],byName['upperarm.L']];legs.forEach((b,i)=>b.userData.knee=byName[i?'shin.L':'shin.R']);arms.forEach((b,i)=>b.userData.elbow=byName[i?'forearm.L':'forearm.R']);
 g.userData={identity,profile:identity===13?'صاحب الوكالة — الحكاية':'صاحب الوكالة',adult:true,characterStyle:'complete-skinned-manager-v2',legs,arms,head:byName.head,bones:byName,skeleton,headHeight:.24,totalHeight:DATA.height,baseShirt:0xf2ead8,managerShirt:materials[1],managerShirtBase:materials[1].color.clone()};(world.adults??=new Set()).add(g);return g;
}
export function updateManagerPose(g,time,carrying=false){const b=g.userData.bones;if(!b)return;for(const [name,bone]of Object.entries(b))if(name.startsWith('finger')&&!name.startsWith('finger1-'))bone.rotation.z=(name.endsWith('L')?-1:1)*(carrying?.42:.08);b.spine.rotation.z=carrying?0:g.userData.legs[0].rotation.x*.025;b.chest.rotation.x=Math.sin(time*1.65)*.004;g.userData.arms.forEach((arm,i)=>{arm.rotation.z=carrying?(i===0?-.14:.14):0;if(carrying){arm.rotation.x=-.65;arm.userData.elbow.rotation.x=-.9}})}
