import * as T from '../vendor/three.module.js';
import * as Agency from '../economy.js';

export const pathfinding = {
blockedAt(x,z){if(x<-14.1||x>14||z<-7.5||z>12.3)return true;if((this.state?.capacity>160||this.state&&Object.keys(this.state.warehouses).some(cid=>this.state.warehouses[cid].owned&&this.state.warehousePlan.slots[cid]===3))&&Math.abs(x-1)<1.8&&Math.abs(z+1.1)<1.1)return true;if(this.state?.capacity>320&&Math.abs(x-5)<1.8&&Math.abs(z+1.1)<1.1)return true;if(this.state?.officeLevel&&Math.abs(x+8)<1.4&&Math.abs(z-1.3)<.68)return true;if(this.state)for(let i=1;i<this.state.truckCount;i++){if(Math.abs(x-(-6.7-(i-1)*5.5))<2.85&&Math.abs(z-8.8)<1.5)return true;}return this.obstacles.some(o=>Math.abs(x-o.x)<o.w/2&&Math.abs(z-o.z)<o.d/2)},

findPath(tx,tz){const step=.5;let start={x:Math.round(this.player.position.x/step),z:Math.round(this.player.position.z/step)},goal={x:Math.round(tx/step),z:Math.round(tz/step)};let key=p=>p.x+','+p.z;const isFree=p=>!this.blockedAt(p.x*step,p.z*step);if(!isFree(goal)){let found=null;for(let r=1;r<5&&!found;r++)for(let dx=-r;dx<=r&&!found;dx++)for(let dz=-r;dz<=r;dz++){let p={x:goal.x+dx,z:goal.z+dz};if(isFree(p)){found=p;break;}}if(!found)return [];goal=found;}
 const open=[start],came=new Map(),gScore=new Map([[key(start),0]]),closed=new Set();let rounds=0;while(open.length&&rounds++<6000){open.sort((a,b)=>gScore.get(key(a))+Math.hypot(a.x-goal.x,a.z-goal.z)-gScore.get(key(b))-Math.hypot(b.x-goal.x,b.z-goal.z));let cur=open.shift(),ck=key(cur);if(cur.x===goal.x&&cur.z===goal.z){let route=[{x:cur.x*step,z:cur.z*step}];while(came.has(ck)){cur=came.get(ck);ck=key(cur);route.push({x:cur.x*step,z:cur.z*step})}return route.reverse().slice(1)}closed.add(ck);for(let [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,-1],[1,-1],[-1,1]]){let p={x:cur.x+dx,z:cur.z+dz},pk=key(p);if(closed.has(pk)||!isFree(p))continue;if(dx&&dz&&(!isFree({x:cur.x+dx,z:cur.z})||!isFree({x:cur.x,z:cur.z+dz})))continue;let ng=gScore.get(ck)+Math.hypot(dx,dz);if(ng<(gScore.get(pk)??Infinity)){came.set(pk,cur);gScore.set(pk,ng);if(!open.some(p=>key(p)===pk))open.push(p);}}}return [];}
};
