import {warehouseFootprint} from '../site-layout.js';
import {BAY_X} from './fleet-path.js';
import * as T from '../vendor/three.module.js';
import * as Agency from '../economy.js';

export const pathfinding = {
blockedAt(x,z){if(this.state)for(const [cid,w]of Object.entries(this.state.warehouses)){if(!w.owned)continue;const b=warehouseFootprint(cid,w.capacity);if(Math.abs(x-b.x)<b.w/2+.35&&Math.abs(z-b.z)<b.d/2+.35)return true;}if((this.state?.warehousePlan.customRacks||this.racks||[]).some(p=>Math.abs(x-p.x)<1.78&&Math.abs(z-p.z)<1.13))return true;if(x<-60||x>14||z<-45||z>18)return true;if(!this.state?.warehousePlan.customRacks&&(this.state?.capacity>160||this.state&&Object.keys(this.state.warehouses).some(cid=>this.state.warehouses[cid].owned&&this.state.warehousePlan.slots[cid]===3))&&Math.abs(x-1)<1.8&&Math.abs(z+1.1)<1.1)return true;if(!this.state?.warehousePlan.customRacks&&this.state?.capacity>320&&Math.abs(x-5)<1.8&&Math.abs(z+1.1)<1.1)return true;if((this.state?.officeLevel||this.state?.development?.owned.dispatch)&&Math.abs(x+8)<1.4&&Math.abs(z-1.3)<.68)return true;if(this.state)for(let i=0;i<this.state.vehicles.length;i++){const v=this.state.vehicles[i];if([this.state.trip,...this.state.fleetTrips].some(t=>t?.vehicleId===v.id))continue;if(Math.abs(x-BAY_X[i])<1.55&&Math.abs(z-12)<(v.kind==='jumbo'?3.35:2.9))return true;}return this.obstacles.some(o=>Math.abs(x-o.x)<o.w/2&&Math.abs(z-o.z)<o.d/2)},

findPath(tx,tz){const step=.5;let start={x:Math.round(this.player.position.x/step),z:Math.round(this.player.position.z/step)},goal={x:Math.round(tx/step),z:Math.round(tz/step)};let key=p=>p.x+','+p.z;const free=new Map();const isFree=p=>{const k=key(p);if(!free.has(k))free.set(k,!this.blockedAt(p.x*step,p.z*step));return free.get(k)};if(!isFree(goal)){let found=null;for(let r=1;r<5&&!found;r++)for(let dx=-r;dx<=r&&!found;dx++)for(let dz=-r;dz<=r;dz++){let p={x:goal.x+dx,z:goal.z+dz};if(isFree(p)){found=p;break;}}if(!found)return [];goal=found;}
 const open=[],came=new Map(),gScore=new Map([[key(start),0]]),closed=new Set();
 const push=(p,g)=>{const node={p,g,f:g+Math.hypot(p.x-goal.x,p.z-goal.z)};open.push(node);let i=open.length-1;while(i>0){const parent=(i-1)>>1;if(open[parent].f<=node.f)break;open[i]=open[parent];i=parent;}open[i]=node;};
 const pop=()=>{const top=open[0],last=open.pop();if(open.length){let i=0;while(i*2+1<open.length){let child=i*2+1;if(child+1<open.length&&open[child+1].f<open[child].f)child++;if(last.f<=open[child].f)break;open[i]=open[child];i=child;}open[i]=last;}return top;};
 push(start,0);let rounds=0;while(open.length&&rounds++<20000){const node=pop();let cur=node.p,ck=key(cur);if(closed.has(ck)||node.g!==gScore.get(ck))continue;if(cur.x===goal.x&&cur.z===goal.z){let route=[{x:cur.x*step,z:cur.z*step}];while(came.has(ck)){cur=came.get(ck);ck=key(cur);route.push({x:cur.x*step,z:cur.z*step})}return route.reverse().slice(1)}closed.add(ck);for(let [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,-1],[1,-1],[-1,1]]){let p={x:cur.x+dx,z:cur.z+dz},pk=key(p);if(closed.has(pk)||!isFree(p))continue;if(dx&&dz&&(!isFree({x:cur.x+dx,z:cur.z})||!isFree({x:cur.x,z:cur.z+dz})))continue;let ng=node.g+Math.hypot(dx,dz);if(ng<(gScore.get(pk)??Infinity)){came.set(pk,cur);gScore.set(pk,ng);push(p,ng);}}}return [];}
};
