import * as T from '../vendor/three.module.js';
import * as Agency from '../economy.js';

export const picking = {
interact(id,label,x,y,z,ax,az){
 const areas={desk:[-10,-4,3.7,1.8],phone:[-8.85,-3.9,.9,.6],accounts:[-12,.1,3,1.6],staff:[-5.1,-5.8,2.5,1.4],map:[-4.4,-7.95,2,.3],shelf:[5,-6.6,12,2],supplier:[11,-2,2.6,1.5],receiving:[9,2.6,3.1,2.3],cooling:[12.15,-6.45,2.9,2.6]};
 if(areas[id]){const [cx,cz,w,d]=areas[id];this.scene.updateMatrixWorld(true);this.scene.traverse(m=>{if(!m.isMesh)return;const p=m.getWorldPosition(new T.Vector3());if(p.y>.08&&Math.abs(p.x-cx)<w/2&&Math.abs(p.z-cz)<d/2)m.userData.action=id;});}
 const el=document.createElement('button');el.className='hotspot';el.textContent=label;el.dataset.object=id;el.setAttribute('aria-label','اذهب إلى '+label);el.addEventListener('click',()=>{if(this.active&&!this.cb.blocked())this.goTo(id)});document.getElementById('world-labels').appendChild(el);this.interactables.push({id,label,pos:new T.Vector3(x,y,z),approach:{x:ax,z:az},el});},

goTo(id){const obj=this.interactables.find(o=>o.id===id);if(!obj)return;this.pending=id;this.path=this.findPath(obj.approach.x,obj.approach.z);if(!this.path.length&&this.player.position.distanceTo(new T.Vector3(obj.approach.x,0,obj.approach.z))<2){this.pending=null;this.cb.interact(id);return;}this.destinationRing.position.set(obj.approach.x,.05,obj.approach.z);this.destinationRing.visible=true;},

interactNear(){if(this.near&&!this.cb.blocked()){this.path=[];this.pending=null;this.cb.interact(this.near.id)}},

setView(view){this.view=view;const views={city:[45,14,95],all:[0,1,42],office:[-8.2,-2.3,23],warehouse:[5,-2.5,27],yard:[2,7,29]};const v=views[view]||views.all;this.focusTarget.set(v[0],0,v[1]);this.zoomTarget=v[2];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));},

setupInput(){let down=null,dragged=false;this.canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,angle:this.angle};dragged=false;this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{if(!down)return;const dx=e.clientX-down.x;if(Math.abs(dx)>7){dragged=true;this.angle=down.angle-dx*.006}});this.canvas.addEventListener('pointerup',e=>{if(down&&!dragged&&this.active&&!this.cb.blocked()){const rect=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);
 const hits=this.ray.intersectObjects(this.scene.children,true);let chosen=null;for(const hit of hits){let n=hit.object;let visible=true;for(let q=n;q;q=q.parent)if(!q.visible)visible=false;if(!visible)continue;for(;n;n=n.parent){if(n.userData.action){chosen=n.userData.action;break;}}break;}if(chosen){if(chosen.startsWith('customer:')||chosen.startsWith('batch:')||chosen.startsWith('vehicle:')){this.cb.interact(chosen);down=null;return;}this.goTo(chosen);down=null;return;}
 const p=new T.Vector3();this.ray.ray.intersectPlane(new T.Plane(new T.Vector3(0,1,0),0),p);if(p){this.pending=null;this.path=this.findPath(p.x,p.z);this.destinationRing.position.set(p.x,.05,p.z);this.destinationRing.visible=this.path.length>0;}}down=null;});this.canvas.addEventListener('pointercancel',()=>{down=null});this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoomTarget=T.MathUtils.clamp(this.zoomTarget+e.deltaY*.025,15,58)},{passive:false});document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();this.keys[e.code]=true;if(e.code==='KeyE'&&!e.repeat)this.interactNear();if(e.code==='KeyQ')this.angle-=.2;if(e.code==='KeyR')this.angle+=.2});document.addEventListener('keyup',e=>this.keys[e.code]=false);window.addEventListener('blur',()=>this.keys={});for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();this.keys[b.dataset.key]=true;b.setPointerCapture(e.pointerId)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>this.keys[b.dataset.key]=false);}document.getElementById('touch-interact').onclick=()=>this.interactNear();}
};
