import {CITY_CLIENTS} from '../city-catalog.js';
export const SUPPLY_CONTRACTS={
 sham:{client:6,pid:'bread',qty:20,every:2,payment:'cash',discount:0},
 marina:{client:7,pid:'milk',qty:20,every:2,payment:'cash',discount:0},
 family:{client:8,pid:'rice',qty:30,every:2,payment:'cash',discount:0},
 tawfeer:{client:9,pid:'oil',qty:50,every:3,payment:'credit',discount:5},
 university:{client:10,pid:'pastry',qty:50,every:2,payment:'credit',discount:5},
 elite:{client:11,pid:'chicken',qty:40,every:3,payment:'credit',discount:5}
};
export const businessDefaults=()=>({business:{version:1,contracts:{},plans:{},visits:{},dealDay:0,history:[]}});
const sum=(a,k='qty')=>a.reduce((n,b)=>n+b[k],0),clamp=n=>Math.max(0,Math.min(100,n));
export function installBusiness(Simulation,{PRODUCTS:P,COMPANIES:C,MAP,DAY_SECONDS,MONEY}){
 const p=Simulation.prototype,wrap=(name,fn)=>{const old=p[name];p[name]=function(...a){return fn.call(this,old,...a)}};
 wrap('tick',function(old,dt){const s=this.s;for(const o of [...s.orders,...this.allTrips().flatMap(t=>t.orders)]){const r=s.business.contracts[o.supply];if(r?.active&&o.supplyCycle===r.cycle&&s.day<=r.dueDay){o.expires=s.elapsed+Math.max(1,(r.dueDay-s.day+1)*s.dayLength-s.time/DAY_SECONDS*s.dayLength);if(o.accepted)o.deadline=o.expires}}return old.call(this,dt)});
 p.customerUnlocked=function(id){const c=CITY_CLIENTS[id];return !!c&&this.s.delivered>=c.unlock&&this.s.regions.includes(c.area)};
 p.businessLog=function(text){this.s.business.history.unshift({day:this.s.day,text});this.s.business.history.length=Math.min(60,this.s.business.history.length);this.notice(text)};
 p.supplyEligible=function(id){const q=SUPPLY_CONTRACTS[id];return !!q&&this.customerUnlocked(q.client)&&this.enabled(q.pid)&&this.territories(P[q.pid].company).includes(this.s.clients[q.client].area)&&this.s.staff.driver>0&&this.s.vehicles.some(v=>C[P[q.pid].company].vehicle==='normal'?v.kind!=='frozen':v.kind===C[P[q.pid].company].vehicle)};
 p.issueSupply=function(id){const s=this.s,r=s.business.contracts[id],q=SUPPLY_CONTRACTS[id];if(!r||!r.active)return;const duration=Math.max(1,(r.dueDay-s.day+1)*s.dayLength-s.time/DAY_SECONDS*s.dayLength);s.orders.push({id:s.seq++,client:q.client,pid:q.pid,qty:q.qty,price:MONEY(this.listPrice(q.pid)*(1-q.discount/100)),accepted:false,discount:0,payment:q.payment,expires:s.elapsed+duration,first:false,special:true,business:true,partialOK:false,supply:id,supplyCycle:r.cycle});this.businessLog('طلب توريد دوري جديد: '+s.clients[q.client].name+' — آخر موعد يوم '+r.dueDay)};
 p.signSupply=function(id){const s=this.s;if(s.business.contracts[id]?.active)return false;if(!this.supplyEligible(id))return this.fail('افتح العميل والتوكيل والمنطقة، وجهّز عربية مناسبة وسائقًا أولًا.');if(Object.values(s.business.contracts).filter(r=>r.active).length>=3)return this.fail('ثبّت خدمتك على ٣ عقود دورية كحد أقصى.');const old=s.business.contracts[id],q=SUPPLY_CONTRACTS[id];s.business.contracts[id]={active:true,renew:true,cycle:(old?.cycle||0)+1,dueDay:s.day+q.every-1,fulfilled:0,successes:old?.successes||0,misses:old?.misses||0};this.issueSupply(id);this.change();return true};
 p.renewSupply=function(id){const r=this.s.business.contracts[id];if(!r?.active)return false;r.renew=!r.renew;this.notice(r.renew?'التجديد التلقائي رجع.':'التجديد اتوقف؛ التزام الدورة الحالية مستمر لآخر موعد.');this.change();return true};
 wrap('accept',function(old,id,discount=0,payment='cash'){const o=this.s.orders.find(v=>v.id===id);if(o?.supply){const r=this.s.business.contracts[o.supply],q=SUPPLY_CONTRACTS[o.supply];if(!r?.active||r.cycle!==o.supplyCycle||this.s.day>r.dueDay)return this.fail('دورة التوريد انتهت.');if(discount!==0||payment!==q.payment)return this.fail('عقد التوريد له سعر وطريقة سداد ثابتة: '+(q.payment==='credit'?'آجل':'نقدي')+'.');}const ok=old.call(this,id,discount,payment);if(ok&&o?.supply)o.deadline=o.expires;return ok});
 wrap('extendOrder',function(old,id){if(this.s.orders.find(o=>o.id===id)?.supply)return this.fail('ميعاد التوريد ثابت في العقد.');return old.call(this,id)});
 wrap('deliverOrder',function(old,o,t){const s=this.s,before=s.invoices.length,already=t.deliveredOrders.includes(o.id);old.call(this,o,t);const invoice=s.invoices.slice(before).find(v=>v.type==='sale');if(!already&&invoice){invoice.orderId=o.id;const q=SUPPLY_CONTRACTS[o.supply],r=s.business.contracts[o.supply];if(q&&r?.active&&r.cycle===o.supplyCycle&&s.day<=r.dueDay&&o.client===q.client&&o.pid===q.pid&&invoice.qty===o.qty&&!t.refusedOrders?.includes(o.id))r.fulfilled=Math.min(q.qty,r.fulfilled+invoice.qty);this.change()}});
 wrap('nextDay',function(old){old.call(this);const s=this.s;for(const [id,r]of Object.entries(s.business.contracts)){if(!r.active||s.day<=r.dueDay)continue;const q=SUPPLY_CONTRACTS[id],won=r.fulfilled>=q.qty,c=s.clients[q.client],care=s.customerCare[q.client];r[won?'successes':'misses']++;s.rep=clamp(s.rep+(won?2:-3));c.trust=clamp(c.trust+(won?4:-8));care.loyalty=clamp(care.loyalty+(won?4:-8));this.businessLog((won?'التزمت بتوريد ':'نقص توريد ')+c.name+(won?': سمعة +٢ وثقة +٤.':': سمعة −٣ وثقة −٨.'));s.orders=s.orders.filter(o=>o.accepted||o.supply!==id||o.supplyCycle!==r.cycle);if(!r.renew){r.active=false;continue}r.cycle++;r.dueDay=s.day+q.every-1;r.fulfilled=0;this.issueSupply(id)}this.change()});
 p.orderJourney=function(o){const s=this.s,trip=this.allTrips().find(t=>t.orders.some(v=>v.id===o.id)),invoice=s.invoices.find(v=>v.type==='sale'&&v.orderId===o.id);if(invoice)return {step:invoice.settled?7:6,label:invoice.settled?'تم التسليم والتحصيل':'الفاتورة مستنية مراجعة أو تحصيل',panel:'accounts'};if(trip)return {step:5,label:'العربية في التوزيع؛ تابع التوقفات وقرارات الطريق',panel:'fleet'};if(!o.accepted)return {step:0,label:'الطلب محتاج تأكيد وشروط دفع',panel:'phone'};const loads=[...s.cargo,...this.otherLoads()],loaded=sum(loads.filter(b=>b.order===o.id));if(loaded>=o.qty)return {step:4,label:'محمّل وجاهز للإرسال',panel:'truck'};if(s.pickingJob?.batch.order===o.id||s.carry?.order===o.id)return {step:3,label:'جاري التجهيز أو انتظار التحميل',panel:'truck'};if(this.qty(o.pid)<o.qty-loaded){const incoming=s.incoming.some(b=>b.pid===o.pid);return {step:incoming?2:1,label:incoming?'البضاعة في الطريق أو محتاجة استلام':'المخزون ناقص؛ اشترِ المطلوب',panel:incoming?'receiving':'supplier'}}return {step:3,label:'البضاعة متاحة؛ ابدأ التجهيز',panel:'shelf'}};
 p.dayPriorities=function(){const s=this.s,list=[];if(this.allTrips().some(t=>t.vehicleId===s.selectedVehicle?s.tripEvent:t.event))list.push({label:'عالج توقف العربية على الطريق',panel:'roadDecisions'});for(const [id,r]of Object.entries(s.business.contracts))if(r.active&&r.fulfilled<SUPPLY_CONTRACTS[id].qty)list.push({label:'توريد '+s.clients[SUPPLY_CONTRACTS[id].client].name+' قبل نهاية يوم '+r.dueDay,panel:'supply',rank:r.dueDay});if(s.incoming.some(b=>b.ready))list.push({label:'استلم الشحنة الجاهزة وابدأ التجهيز',panel:'receiving'});for(const o of s.orders.filter(o=>o.accepted).slice(0,2)){const j=this.orderJourney(o);list.push({label:s.clients[o.client].name+': '+j.label,panel:j.panel})}if(s.invoices.some(v=>!v.settled&&v.type==='sale'&&v.due<=s.day))list.push({label:'راجع الفواتير وحصّل مستحقاتك',panel:'accounts'});if(!s.signed)list.push({label:'وقّع عقد استلام الوكالة',panel:'desk'});if(!s.inventoried)list.push({label:'اعمل جرد أولي للمخزن',panel:'shelf'});if(!s.repaired)list.push({label:'جهّز عربية التوزيع الأولى',panel:'truck'});list.push({label:'راجع الطلبات الجديدة وقدرتك على تنفيذها',panel:'phone'});return list.slice(0,3)};
 p.toggleLoadPlan=function(id){const s=this.s,o=s.orders.find(o=>o.id===Number(id)&&o.accepted);if(!o)return false;const plan=s.business.plans[s.selectedVehicle]=(s.business.plans[s.selectedVehicle]||[]).filter(id=>s.orders.some(o=>o.id===id&&o.accepted));if(plan.includes(o.id)){if(s.cargo.some(b=>b.order===o.id))return this.fail('فرّغ الطلب المحمّل قبل إزالته من الخطة.');plan.splice(plan.indexOf(o.id),1);}else{if(!this.canCarry(o.pid))return this.fail('العربية لا تناسب حفظ هذا الصنف.');if(this.allTrips().some(t=>t.orders.some(x=>x.id===o.id))||this.otherLoads().some(b=>b.order===o.id))return this.fail('الطلب مرتبط بعربية أخرى.');const total=[...new Set([...plan,...s.cargo.map(b=>b.order),o.id])].map(i=>s.orders.find(x=>x.id===i)).filter(Boolean).reduce((n,x)=>n+x.qty,0);if(total>this.vehicle.capacity)return this.fail('الخطة أكبر من حمولة العربية.');for(const key of Object.keys(s.business.plans))if(Number(key)!==s.selectedVehicle)s.business.plans[key]=s.business.plans[key].filter(i=>i!==o.id);plan.push(o.id)}this.change();return true};
 p.loadForecast=function(){const s=this.s,ids=[...new Set([...(s.business.plans[s.selectedVehicle]||[]),...s.cargo.map(b=>b.order)])],orders=s.orders.filter(o=>ids.includes(o.id)&&o.accepted),qty=sum(orders),shortages={};for(const o of orders)shortages[o.pid]=(shortages[o.pid]||0)+o.qty;for(const pid of Object.keys(shortages))shortages[pid]=Math.max(0,shortages[pid]-this.qty(pid)-sum(s.cargo.filter(b=>b.pid===pid))-(s.carry?.pid===pid&&ids.includes(s.carry.order)?s.carry.qty:0)-(s.pickingJob?.batch.pid===pid&&ids.includes(s.pickingJob.batch.order)?s.pickingJob.batch.qty:0));if(!orders.length)return {orders,qty,cost:0,seconds:0,revenue:0,margin:0,shortages,valid:false};const t=this.buildTrip(orders,[],'safe'),km=t.legs.filter(l=>l.points&&!l.yard).reduce((n,l)=>n+l.points.slice(1).reduce((a,v,i)=>a+Math.hypot(v.x-l.points[i].x,v.y-l.points[i].y),0),0)/40,cost=MONEY((orders.some(o=>s.clients[o.client].area==='الدقهلية')?180:70)+Math.max(0,new Set(orders.map(o=>o.client)).size-1)*20+({chilled:40,frozen:65,jumbo:100}[this.vehicle.kind]||0)+(s.weather==='wind'?25:0)+km*4),revenue=MONEY(orders.reduce((n,o)=>n+o.qty*o.price*(1-o.discount/100),0)),goods=MONEY(orders.reduce((n,o)=>n+o.qty*this.cost(o.pid),0));return {orders,qty,cost,seconds:t.total,revenue,margin:MONEY(revenue-goods-cost),shortages,valid:qty<=this.vehicle.capacity&&orders.every(o=>this.canCarry(o.pid))}};
 p.packPlanned=function(){const s=this.s,f=this.loadForecast();if(!f.valid)return this.fail('راجع سعة العربية وتبريد الأصناف أولًا.');const o=f.orders.find(o=>sum(s.cargo.filter(b=>b.order===o.id))<o.qty);return o?this.pack(o.id):this.fail('الخطة محملة بالفعل؛ أرسل العربية.')};
 p.customerDialogue=function(id){const c=CITY_CLIENTS[id],r=Object.entries(SUPPLY_CONTRACTS).find(([,q])=>q.client===id),v=r&&this.s.business.contracts[r[0]];if(v?.active&&v.fulfilled<SUPPLY_CONTRACTS[r[0]].qty)return c.contact+': مستني باقي التوريد قبل نهاية يوم '+v.dueDay+'. '+c.persona;if(this.s.customerCare[id].loyalty<45)return c.contact+': حصل تأخير مؤخرًا. محتاج التزام حقيقي عشان الثقة ترجع.';return c.contact+': '+c.persona};
 p.visitBusiness=function(id,choice){id=Number(id);if(!this.customerUnlocked(id))return this.fail('العميل يتفتح مع تقدم الوكالة.');const s=this.s,last=s.business.visits[id];if(last&&s.day-last.day<3)return this.fail('الزيارة التجارية متاحة كل ٣ أيام.');if(!['service','cash'].includes(choice))return false;if(choice==='service'&&!this.spend(350,true,'متابعة وخدمة '+s.clients[id].name))return this.fail('الخزنة لا تكفي.');if(choice==='service'){s.clients[id].trust=clamp(s.clients[id].trust+4);s.customerCare[id].loyalty=clamp(s.customerCare[id].loyalty+6)}else if(!this.setCredit(id,0))return false;s.business.visits[id]={day:s.day,choice};this.businessLog(choice==='service'?'زيارة خدمة حسّنت علاقة '+s.clients[id].name:'تم الاتفاق على السداد النقدي للطلبات الجديدة مع '+s.clients[id].name+'؛ المديونية القديمة مستمرة.');this.change();return true};
 p.takeTradeDeal=function(choice){const s=this.s;if(!['cash','volume'].includes(choice)||s.business.dealDay===s.day||!s.contracts.bakery)return false;const client=choice==='cash'?0:9;if(!this.customerUnlocked(client)||!this.territories('bakery').includes(s.clients[client].area))return this.fail('افتح العميل وتصريح المنطقة أولًا.');const qty=choice==='cash'?10:50,price=MONEY(this.listPrice('bread')*(choice==='cash'?1:.95));s.orders.push({id:s.seq++,client,pid:'bread',qty,price,accepted:false,discount:0,payment:choice==='cash'?'cash':'credit',expires:s.elapsed+600,first:false,special:true,business:choice==='volume',tradeDeal:choice});s.business.dealDay=s.day;this.businessLog('وصل عرض '+(choice==='cash'?'نقدي صغير':'كميات آجل')+'؛ أكّده في الطلبات بعد مراجعة السيولة.');this.change();return true};
 wrap('accept',function(old,id,discount=0,payment='cash'){const o=this.s.orders.find(x=>x.id===id);if(o?.tradeDeal&&(discount!==0||payment!==(o.tradeDeal==='cash'?'cash':'credit')))return this.fail('عرض اليوم بشروط السداد والسعر المعلنة.');return old.call(this,id,discount,payment)});
 const validate=Simulation.validate;Simulation.validate=function(data){const s=validate({...data,business:data?.business||businessDefaults().business}),b=s.business,bad=()=>{throw Error('بيانات عقود التوريد والتخطيط غير صالحة.')},obj=v=>v&&typeof v==='object'&&!Array.isArray(v),int=(v,min=0,max=1e9)=>Number.isInteger(v)&&v>=min&&v<=max;if(!obj(b)||b.version!==1||!int(b.dealDay,0,s.day))bad();for(const k of ['contracts','plans','visits'])if(!obj(b[k]))bad();if(!Array.isArray(b.history)||b.history.length>60||b.history.some(h=>!int(h.day,1,s.day)||typeof h.text!=='string'||h.text.length>500))bad();for(const [id,r]of Object.entries(b.contracts)){const q=SUPPLY_CONTRACTS[id];if(!q||!obj(r)||typeof r.active!=='boolean'||typeof r.renew!=='boolean'||!int(r.cycle,1)||!int(r.dueDay,1)||!int(r.fulfilled,0,q.qty)||!int(r.successes)||!int(r.misses))bad()}for(const [id,plan]of Object.entries(b.plans))if(!s.vehicles.some(v=>String(v.id)===id)||!Array.isArray(plan)||plan.length>4||new Set(plan).size!==plan.length||plan.some(n=>!int(n,1)))bad();for(const [id,v]of Object.entries(b.visits))if(!CITY_CLIENTS[id]||!int(v.day,1,s.day)||!['service','cash'].includes(v.choice))bad();for(const o of [...s.orders,...[s.trip,...s.fleetTrips].filter(Boolean).flatMap(t=>t.orders)]){if(o.supply!==undefined&&(!SUPPLY_CONTRACTS[o.supply]||!int(o.supplyCycle,1)||o.pid!==SUPPLY_CONTRACTS[o.supply].pid||o.qty!==SUPPLY_CONTRACTS[o.supply].qty))bad();if(o.tradeDeal!==undefined&&!['cash','volume'].includes(o.tradeDeal))bad()}return s};
}
