export const STAGES=[{name:'وكالة الحي',delivered:0,rep:0},{name:'موزع معروف',delivered:5,rep:50},{name:'شركة منظمة',delivered:15,rep:60},{name:'مركز توزيع',delivered:35,rep:70},{name:'شبكة إقليمية',delivered:70,rep:80}];
export const DEVELOPMENTS={
 frontage:{name:'واجهة ولافتة مضيئة',stage:1,cost:1800,benefit:'واجهة جديدة وسمعة +٢ مرة واحدة'},
 jack:{name:'عربة نقل يدوي',stage:1,cost:2500,benefit:'تجهيز واستلام أسرع ٢٠٪ عند اختيارها؛ تتطلب عاملًا'},
 paving:{name:'أرضية صناعية وممرات',stage:2,cost:4200,benefit:'أرضية وخطوط سلامة؛ تجهيز العامل أسرع ١٠٪ إضافية'},
 wash:{name:'محطة غسيل الأسطول',stage:2,cost:3500,benefit:'تفتح الغسيل بـ٨٠ ج للعربية وتزيل التراب بصريًا'},
 uniforms:{name:'هوية الشركات وملابس العمل',stage:2,cost:2200,benefit:'ملابس وشارات شركة؛ معنويات الفريق +٥ مرة واحدة'},
 forklift:{name:'رافعة شوكية كهربائية',stage:3,cost:14500,requires:'jack',benefit:'استلام وتجهيز أسرع ٤٥٪ عند اختيارها؛ تتطلب عاملًا'},
 dispatch:{name:'مكتب تشغيل الخطوط',stage:3,cost:8500,benefit:'مكتب وشاشة تشغيل؛ وقت تفريغ العملاء أقل ١٥٪'},
 landmark:{name:'مقر إقليمي',stage:4,cost:22000,requires:'frontage',benefit:'واجهة كبيرة ومظلات؛ يفتح تحدي الشبكة الإقليمية'}
};
export const DISTRICT_TASKS=[{name:'خدمة حي السوق',stage:1,client:0,qty:40,reward:650},{name:'توريد الحي السكني',stage:2,client:2,qty:90,reward:1500},{name:'تجهيز محلات التوسع',stage:3,client:3,qty:160,reward:2800},{name:'شبكة وكالة سعيد',stage:4,client:4,qty:240,reward:4200,requires:'landmark'}];
export const developmentDefaults=()=>({development:{version:1,stage:0,owned:{},equipment:'manual',branding:{},washedAt:{},districts:{},loadMotion:null}});
export function installDevelopment(Simulation,{PRODUCTS:P}){
 const p=Simulation.prototype,wrap=(name,fn)=>{const old=p[name];p[name]=function(...args){return fn.call(this,old,...args)}};
 p.unlockDevelopment=function(){const d=this.s.development;let stage=d.stage;for(let i=stage+1;i<STAGES.length;i++){const t=STAGES[i];if(this.s.delivered>=t.delivered&&this.s.rep>=t.rep)stage=i;else break}if(stage>d.stage){d.stage=stage;this.notice('مرحلة جديدة: '+STAGES[stage].name+' — افتح تابلت التطوير.')}return stage};
 wrap('change',function(old,...args){this.unlockDevelopment();return old.apply(this,args)});
 p.buyDevelopment=function(id){const s=this.s,d=s.development,u=DEVELOPMENTS[id];this.unlockDevelopment();if(!u||d.owned[id])return false;if(d.stage<u.stage||u.requires&&!d.owned[u.requires])return this.fail('أكمل المرحلة والترقية السابقة أولًا.');if(['jack','forklift'].includes(id)&&!s.staff.worker)return this.fail('عيّن عامل مخزن لتشغيل المعدة.');if(s.workerJob||s.pickingJob)return this.fail('استنى انتهاء النقل الحالي قبل تغيير التجهيزات.');if(!this.spend(u.cost,false,u.name))return this.fail('الخزنة لا تكفي.');d.owned[id]=true;if(id==='frontage')s.rep=Math.min(100,s.rep+2);if(id==='uniforms')for(const m of s.team)m.mood=Math.min(100,m.mood+5);if(['jack','forklift'].includes(id))d.equipment=id;this.notice('تم تركيب '+u.name+'؛ ظهر في المكان وأصبح متاحًا.');this.change();return true};
 p.selectEquipment=function(id){if(!['manual','jack','forklift'].includes(id)||id!=='manual'&&!this.s.development.owned[id])return false;if(this.s.pickingJob||this.s.workerJob)return this.fail('كمّل النقلة الحالية الأول.');this.s.development.equipment=id;this.change();return true};
 for(const action of ['pack','receive'])wrap(action,function(old,...args){const ok=old.apply(this,args),s=this.s,job=action==='pack'?s.pickingJob:s.workerJob;if(ok&&job){job.duration=Math.max(2,job.duration*({manual:1,jack:.8,forklift:.55}[s.development.equipment])*(s.development.owned.paving?.9:1));job.equipment=s.development.equipment;this.change()}return ok});
 wrap('buildTrip',function(old,...args){const t=old.apply(this,args);for(const leg of t.legs)if(leg.yard==='out'){const boarding=this.s?.weather==='rain'?3.6:3;leg.hold=(leg.hold||0)+boarding;leg.duration+=boarding;leg.boarding=boarding;}t.total=t.remaining=t.legs.reduce((a,l)=>a+l.duration,0);if(this.s?.development?.owned.dispatch){for(const leg of t.legs)if(leg.kind==='unload')leg.duration=(leg.windowWait||0)+(leg.duration-(leg.windowWait||0))*.85;t.total=t.remaining=t.legs.reduce((a,l)=>a+l.duration,0)}return t});
 p.assignFleetBrands=function(){const s=this.s;if(!s?.development)return;const brands=s.development.branding,away=new Set(this.allTrips().map(t=>t.vehicleId));for(const cid of ['frozen','dairy','bakery','pantry']){if(!s.contracts[cid]||Object.values(brands).includes(cid))continue;const available=s.vehicles.filter(v=>!Object.hasOwn(brands,v.id)&&!away.has(v.id)&&(cid==='frozen'?v.kind==='frozen':cid==='dairy'?v.kind!=='normal':true)).sort((a,b)=>(a.kind==='normal'?0:1)-(b.kind==='normal'?0:1));if(available.length)brands[available[0].id]=cid;}};
 wrap('change',function(old,...args){this.assignFleetBrands();return old.apply(this,args)});
 p.brandVehicle=function(id,cid){id=Number(id);const s=this.s;if(!s.vehicles.some(v=>v.id===id)||!['agency',...Object.keys(s.contracts)].includes(cid))return false;if(cid!=='agency'&&!s.contracts[cid])return this.fail('وقّع التوكيل قبل استخدام علامته.');if(this.allTrips().some(t=>t.vehicleId===id))return this.fail('العربية لازم ترجع الجراج الأول.');s.development.branding[id]=cid;this.change();return true};
 p.washVehicle=function(id){id=Number(id);const s=this.s;if(!s.development.owned.wash||!s.vehicles.some(v=>v.id===id)||this.allTrips().some(t=>t.vehicleId===id)||s.ops.services.some(j=>j.id===id))return false;const km=this.mechanical(id).km;if(s.development.washedAt[id]===km)return false;if(!this.spend(80,true,'غسيل العربية '+id))return this.fail('الخزنة لا تكفي.');s.development.washedAt[id]=km;this.notice('العربية اتغسلت؛ الغسيل لا يصلح الأعطال الميكانيكية.');this.change();return true};
 p.startDistrict=function(index){index=Number(index);const task=DISTRICT_TASKS[index],s=this.s,d=s.development;this.unlockDevelopment();if(!task||d.districts[index]||d.stage<task.stage||task.requires&&!d.owned[task.requires])return false;if(!s.regions.includes(s.clients[task.client].area))return this.fail('افتح منطقة العميل أولًا.');d.districts[index]={done:0,rewarded:false};this.notice('بدأ '+task.name+'؛ جهّز طلبيات هذا العميل. بدون مهلة أو غرامة.');this.change();return true};
 p.requestDistrictOrder=function(index){index=Number(index);const task=DISTRICT_TASKS[index],s=this.s,progress=s.development.districts[index];if(!task||!progress||progress.rewarded)return false;if(s.orders.some(o=>o.client===task.client)||this.allTrips().some(t=>t.orders.some(o=>o.client===task.client&&!t.deliveredOrders.includes(o.id))))return this.fail('كمّل طلب العميل الحالي الأول.');const pid=Object.keys(P).find(id=>this.enabled(id)&&this.territories(P[id].company).includes(s.clients[task.client].area));if(!pid)return this.fail('تحتاج توكيلًا مصرحًا به في منطقة العميل.');if(s.orders.length>=20)return this.fail('قائمة الطلبات ممتلئة.');const qty=Math.min(20,task.qty-progress.done);s.orders.push({id:s.seq++,client:task.client,pid,qty,price:P[pid].sell,accepted:false,discount:0,payment:'cash',expires:s.elapsed+300,business:true});this.change();return true};
 wrap('deliverOrder',function(old,o,t){const already=t.deliveredOrders.includes(o.id);old.call(this,o,t);if(already||!t.deliveredOrders.includes(o.id)||t.refusedOrders?.includes(o.id))return;for(const [key,progress]of Object.entries(this.s.development.districts)){const task=DISTRICT_TASKS[key];if(progress.rewarded||task.client!==o.client)continue;progress.done=Math.min(task.qty,progress.done+o.qty);if(progress.done>=task.qty){progress.rewarded=true;this.s.money+=task.reward;this.s.expenses-=task.reward;this.log(task.name+' — مكافأة',task.reward);this.notice('اكتمل '+task.name+'؛ اتجدد المحل وكسبت '+task.reward+' ج.');}}this.change()});
 wrap('load',function(old){const s=this.s,b=s.carry?{...s.carry}:null,ok=old.call(this);if(ok&&b){s.development.loadMotion={vehicle:s.selectedVehicle,pid:b.pid,qty:b.qty,start:s.elapsed,x:s.position.x,z:s.position.z};this.change()}return ok});
 wrap('tick',function(old,dt){old.call(this,dt);const d=this.s.development;if(d.loadMotion&&this.s.elapsed-d.loadMotion.start>1.3)d.loadMotion=null});
 const validate=Simulation.validate;Simulation.validate=function(data){const s=validate({...data,development:data?.development||developmentDefaults().development}),d=s.development,bad=()=>{throw Error('بيانات التطوير غير صالحة.')},obj=v=>v&&typeof v==='object'&&!Array.isArray(v),num=(v,min=0,max=1e12)=>Number.isFinite(v)&&v>=min&&v<=max;if(!obj(d)||d.version!==1||!Number.isInteger(d.stage)||!num(d.stage,0,4)||!['manual','jack','forklift'].includes(d.equipment))bad();for(const key of ['owned','branding','washedAt','districts'])if(!obj(d[key]))bad();for(const [id,v]of Object.entries(d.owned))if(!Object.hasOwn(DEVELOPMENTS,id)||v!==true)bad();if(d.equipment!=='manual'&&!d.owned[d.equipment])bad();for(const [id,cid]of Object.entries(d.branding))if(!s.vehicles.some(v=>v.id===Number(id))||!['agency',...Object.keys(s.contracts)].includes(cid)||cid!=='agency'&&!s.contracts[cid])bad();for(const [id,km]of Object.entries(d.washedAt))if(!s.vehicles.some(v=>v.id===Number(id))||!num(km))bad();for(const [id,v]of Object.entries(d.districts)){const task=DISTRICT_TASKS[id];if(!task||!obj(v)||!num(v.done,0,task.qty)||typeof v.rewarded!=='boolean'||v.rewarded&&v.done!==task.qty)bad()}if(d.loadMotion){const m=d.loadMotion;if(!s.vehicles.some(v=>v.id===m.vehicle)||!P[m.pid]||!num(m.qty,1,60)||!num(m.start,0,s.elapsed)||!num(m.x,-14.1,14)||!num(m.z,-7.5,16.3))bad()}for(const job of [s.pickingJob,s.workerJob].filter(Boolean))if(job.equipment!==undefined&&!['manual','jack','forklift'].includes(job.equipment))bad();return s};
}
